Description of addFiber_callback
Home > v08 > Callbacks > addFiber_callback.m
addFiber_callback
PURPOSE
SYNOPSIS
function addFiber_callback(source,eventData,allHandles,allData)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
Fiber1
createTree2
showTree [mtree,treecontainer] = uitree('v0', 'Root',root);
This function is called by:
treeNode_callback
SOURCE CODE
function addFiber_callback(source,eventData,allHandles,allData)
[object,figure]=gcbo
allData = guidata(figure)
%figure
% allFiber_callback : call back function for "add to library" button on "add fiber" window.
% -- copyright 2014-2016 Hong Yu, hongyu.us@gmail.com --
disp 'add to lib button pressed!'
tableHandle = allHandles.materialPropertyTable;
itemData = tableHandle.Data;
newItem = Fiber1();
newItem = newItem.constructFromTable(itemData);
allData.fiberLib = allData.fiberLib.addItem(newItem);
%allData.fiberLib
%root = allData.treeRoot;
[allData.mtree,allData.treeContainer] = createTree2(allData);
showTree(allHandles,allData)
% updateTree(allHandles.mtree)
%     function updateTree(treeHandle)
%
%     end
guidata(figure,allData)
end