Description of addFiber
Home > v08 > Callbacks > addFiber.m
addFiber
PURPOSE
SYNOPSIS
function addFiber(allHandles,allData)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
Fiber1
This function is called by:
createTree2
treeNode_callback
SOURCE CODE
function addFiber(allHandles,allData)
tableHandle =allHandles.materialPropertyTable;
choosePackOrderTable = allHandles.choosePackOrderTable;
chooseFiberTable =allHandles.chooseFiberTable;
%chooseFiberTable =allHandles.chooseFiberTable;
add2LibBtn = allHandles.add2LibBtn;
removeFromLibBtn = allHandles.removeFromLibBtn;
% addLamina used in treeNode_callback
chooseFiberTable.Visible = 'off';
choosePackOrderTable.Visible = 'off';
add2LibBtn.Visible = 'on';% show add2Lib btn. s
removeFromLibBtn.Visible ='off';
defaultFiber = Fiber1()
defaultFiber.showOnGui(tableHandle);
% tableHandle = allHandles.materialPropertyTable;
%                    columnNames = {'Property Value','Property Unit'};
%                    rowNames = {'Fiber Name','Diameter','Electrical Resistivity','Thermal Conductivty',...
%                 'Elastic Modulus','Beta Term'};
tableHandle.ColumnEditable = true;
end