Description of addLaminate
Home > v08 > Callbacks > addLaminate.m
addLaminate
PURPOSE
SYNOPSIS
function addLaminate(selectedNode,allHandles,allData)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
Laminate1
This function is called by:
createTree2
treeNode_callback
SOURCE CODE
function addLaminate(selectedNode,allHandles,allData)
table1 =allHandles.materialPropertyTable;
choosePackOrderTable = allHandles.choosePackOrderTable;
table2 =allHandles.chooseFiberTable;
parameterTable = allHandles.simulationParameterTable;
%chooseFiberTable =allHandles.chooseFiberTable;
add2LibBtn = allHandles.add2LibBtn;
removeFromLibBtn = allHandles.removeFromLibBtn;
% addLamina used in treeNode_callback
table1.Visible ='on';
table2.Visible = 'on';
parameterTable.Visible = 'on';
%choosePackOrderTable.Visible = 'off';
add2LibBtn.Visible = 'on';% show add2Lib btn. s
removeFromLibBtn.Visible ='off';
defaultLaminate = Laminate1();
defaultLaminate.showOnGui(allHandles);
table1.ColumnEditable = true;
table2.ColumnEditable = [true true true];
laminaNames = allData.laminaLib.itemNames
table2.ColumnFormat ={laminaNames,'numeric','numeric'}
end