Description of addLamina_callback
Home > v08 > Callbacks > addLamina_callback.m
addLamina_callback
PURPOSE
SYNOPSIS
function addLamina_callback(source,eventData,allHandles,allData)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
Lamina1
createTree2
showTree [mtree,treecontainer] = uitree('v0', 'Root',root);
This function is called by:
addLamina
SOURCE CODE
function addLamina_callback(source,eventData,allHandles,allData)
[object,figure]=gcbo;
allData = guidata(figure);
%figure
% allFiber_callback : call back function for "add to library" button on "add fiber" window.
% -- copyright 2014-2016 Hong Yu, hongyu.us@gmail.com --
disp 'add to lib button pressed!'
propertyData = allHandles.materialPropertyTable.Data
chooseFiberData = allHandles.chooseFiberTable.Data
choosePackOrderData = allHandles.choosePackOrderTable.Data
tableData = [propertyData;chooseFiberData;choosePackOrderData]
newItem = Lamina1();
fieldNames = fieldnames(newItem.propertyStruct);
newItem.propertyStruct=cell2struct(tableData,fieldNames,1)
%newItem = newItem.constructFromTable(itemData);
allData.laminaLib = allData.laminaLib.addItem(newItem);
%allData.fiberLib
%root = allData.treeRoot;
[allData.mtree,allData.treeContainer] = createTree2(allData);
showTree(allHandles,allData)
% updateTree(allHandles.mtree)
%     function updateTree(treeHandle)
%
%     end
guidata(figure,allData)
end