Description of addLaminate_callback
Home > v08 > Callbacks > addLaminate_callback.m
addLaminate_callback
PURPOSE
SYNOPSIS
function addLaminate_callback(source,eventData,allHandles,allData)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
Laminate1
createTree2
showTree [mtree,treecontainer] = uitree('v0', 'Root',root);
This function is called by:
treeNode_callback
SOURCE CODE
function addLaminate_callback(source,eventData,allHandles,allData)
[object,figure]=gcbo;
allData = guidata(figure);
%figure
% allFiber_callback : call back function for "add to library" button on "add fiber" window.
% -- copyright 2014-2016 Hong Yu, hongyu.us@gmail.com --
disp 'add to lib button pressed!'
table1Data = allHandles.materialPropertyTable.Data
table2Data = allHandles.chooseFiberTable.Data
%propertyData = [table1Data;table2Data];
parameterData = allHandles.simulationParameterTable.Data;
%choosePackOrderData = allHandles.choosePackOrderTable.Data
%tableData = [table1Data;table2Data;choosePackOrderData]
newItem = Laminate1();
propertyNames = fieldnames(newItem.propertyStruct)
table1Names = propertyNames(1:3);
table2Names = propertyNames(4:6);
fieldValue =[]
newItem.propertyStruct.name = table1Data{1};
newItem.propertyStruct.pressure =table1Data{2};
newItem.propertyStruct.dimension=table1Data{3};
newItem.propertyStruct.laminaArray = table2Data(:,1);
newItem.propertyStruct.layupArray = table2Data(:,2);
newItem.propertyStruct.connectivityArray = table2Data(:,3);
% for i = 1:3
%     field = table1Names{i}
%     value = table1Data{i}
%     fieldValue=[fieldValue ',' field ',' value]
% end
% for i=1:3
%     field = table2Names{i}
%     value = table2Data(:,i)
%     fieldValue=[fieldValue ',' field ',' value]
% end
% newItem.propertyStruct = struct(fieldValue)
parameterNames = fieldnames(newItem.parameterStruct)
newItem.parameterStruct = cell2struct(parameterData,parameterNames,1)
% newItem.propertyStruct=cell2struct(tableData,propertyNames,1);
% parameterNames =fieldnames(newItem.parameterStruct)
% newItem.parameterStruct=cell2struct(tableData,parameterNames,1);
%newItem = newItem.constructFromTable(itemData);
allData.laminateLib = allData.laminateLib.addItem(newItem);
%allData.fiberLib
%root = allData.treeRoot;
[allData.mtree,allData.treeContainer] = createTree2(allData);
showTree(allHandles,allData)
% updateTree(allHandles.mtree)
%     function updateTree(treeHandle)
%
%     end
guidata(figure,allData)
end