Description of addLamina
Home > v08 > Callbacks > addLamina.m
addLamina
PURPOSE
SYNOPSIS
function addLamina(allHandles,allData)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
Lamina1
addLamina_callback
set TEMPLATE/SET Edit data stored in a Template object
This function is called by:
createTree2
treeNode_callback
SOURCE CODE
function addLamina(allHandles,allData)
tableHandle =allHandles.materialPropertyTable;
choosePackOrderTable = allHandles.choosePackOrderTable;
chooseFiberTable =allHandles.chooseFiberTable;
%chooseFiberTable =allHandles.chooseFiberTable;
add2LibBtn = allHandles.add2LibBtn;
removeFromLibBtn = allHandles.removeFromLibBtn;
% addLamina used in treeNode_callback
chooseFiberTable.Visible = 'off';
choosePackOrderTable.Visible = 'off';
add2LibBtn.Visible = 'on';% show add2Lib btn. s
removeFromLibBtn.Visible ='off';
add2LibBtn.Callback = {@addLamina_callback,allHandles,allData};
% tableHandle = allHandles.materialPropertyTable;
tableHandle.ColumnEditable = true;
%propertyData =
defaultLamina = Lamina1();
defaultData = struct2cell(defaultLamina.propertyStruct);
tableData = defaultData(1:4,1);
tableHandle.Data=tableData;
rowNames = {'Lamina Name','Volume Fraction','Pressure','Dimension'};
tableHandle.RowName =rowNames;
set(allHandles.materialPropertyLayout,'Height',[200,30,30])
%tableHandle.CellSelectionCallback = @cellSelection_callback;
allHandles.chooseFiberTable.Visible = 'on';
if 1
    fiberNames = allData.fiberLib.itemNames;
    chooseFiberTable.ColumnEditable=true;
    chooseFiberTable.ColumnFormat ={fiberNames};
    chooseFiberTable.RowName = {'Please choose fiber type:'};
    chooseFiberTable.ColumnName =[];
    data = {'AS4'}
    chooseFiberTable.Data = data;
end
choosePackOrderTable = allHandles.choosePackOrderTable;
choosePackOrderTable.Visible = 'on';
if 1
    packOrderData = {'Random'};
    choosePackOrderTable.RowName = {'Please choose Pack Order:'};
    choosePackOrderTable.ColumnName = [];
    choosePackOrderTable.Data=packOrderData;
    choosePackOrderTable.ColumnEditable=true;
    choosePackOrderTable.ColumnFormat ={{'Square','Hexagonal','Random'}};
end
end