Description of LaminaLib
Home > v08 > @LaminaLib > LaminaLib.m
LaminaLib
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
Lamina1
LaminaLib
This function is called by:
LaminaLib
CFRP_GUI_v08 GUI for 3D resistor network
SUBFUNCTIONS
function obj = LaminaLib()
function obj = addItem(obj,itemObj)
function obj = deleteItem(obj,itemName)
function showOnGui(obj,tableHandle)
function itemNames = getNames(obj)
SOURCE CODE
classdef LaminaLib
    %%% table in the form:
    %   Name      AS4        IM7
    % beta           400         350
    % resistivity   1.5e-5   1.6e-5
    %   ...             ....          ....
    %%%
    %     properties %(Dependent)
    %
    %        %libTable =table; % fiberLib is a Table
    %     end
    properties
        itemNames ={}
        itemArray=[]
        % libStruct = struct;
    end
    methods
        %         function obj = FiberLib()
        %             %              fiberAS4 = Fiber1('AS4')
        %             %              fiberIM7 = Fiber1('IM7')
        %             %              fiberLibStruct = [fiberAS4.materialProperty fiberIM7.materialProperty]
        %             obj.fiberLibTable = table
        %         end
        function obj = LaminaLib()
            obj.itemArray = [Lamina1()];
            obj.itemNames = {'AS4 VF=0.5','IM7 VF=0.6'};
            for i=1:length(obj.itemNames)
                itemName = obj.itemNames{i};
                %class(item)
                itemObj=Lamina1(itemName);
                obj.itemArray(i)=itemObj;
            end
        end
        function obj = addItem(obj,itemObj)
            itemName = itemObj.propertyStruct.name;
            [hasItem,~] = ismember(itemName,obj.itemNames);
            errMsg=['NameError: lamina name "' itemName '" already existed; please pick another name!'];
            assert(~hasItem,errMsg);
            obj.itemNames{end+1} = itemName;
            obj.itemArray(end+1) = itemObj;
        end
        function obj = deleteItem(obj,itemName)
            %[~,index]=ismember(fiberc
            %itemName = itemObj.propertyStruct.name;
            [hasItem,index] = ismember(itemName,obj.itemNames);
            errMsg= 'lamina to be deleted is not found in current fiber libary!';
            assert(hasItem,errMsg)
            obj.itemArray(index)=[];
            obj.itemNames(index)=[];
        end
        function showOnGui(obj,tableHandle)
            data = obj.itemNames';
            tableHandle.Data=data;
            tableHandle.RowName = 'numbered';
            tableHandle.ColumnName={'Lamina Name'};
        end
        function itemNames = getNames(obj)
            itemNames = obj.itemNames;
        end
    end
end
%
%             laminaAS4 = Lamina1('Lamina AS4')
%             laminaIM7 = Lamina1('lamina IM7')
%             obj.libStruct = [laminaAS4.propertyStruct laminaIM7.propertyStruct]
%            tableObj =[laminaAS4.propertyTable;laminaIM7.propertyTable]
%            obj.libTable = tableObj(:,1:end-1)
%             %obj.libTable = struct2table(laminaLibStruct);
%         end
%         function obj = set.libTable(obj,tableObj)
%             obj.libTable = tableObj
%         end
%         function value = get.libTable(obj)
%             value = obj.libTable
%         end
%
%         function names = getNames(obj)
%             names = table2cell(obj.libTable(:,1));
%         end
%         function obj = addItem(obj,newItem)
%             prevTable = obj.libTable
%             newItemTable = struct2table(newItem.materialProperty)
%             newTable = [prevTable;newItemTable]
%             obj.libTable = newTable
%         end
%         function obj = deleteItem(obj)
%         end
%
%
%     end
% end