Description of Lamina1
Home > v08 > @Lamina1 > Lamina1.m
Lamina1
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
Lamina1
writeLaminaNetlist function NetListID = WriteNetlist_UD(Netlist_name,fibermat,fiberLen,beta,fiberRadius,rf,Rc)
writeLaminaNetlist function NetListID = WriteNetlist_UD(Netlist_name,fibermat,fiberLen,beta,fiberRadius,rf,Rc)
This function is called by:
Lamina1
LaminaLib
addLamina
addLamina_callback
SUBFUNCTIONS
function obj = Lamina1(val)
function resistivityTensor = clacResistivityTensor(obj)
function showOnGui(obj,tableHandle)
function resistivityTensor = getResistivityTensor(obj)
function xResistivity = getXResistivity(obj)
function yResistivity = getYResistivity(obj)
function zResistivity = getZResistivity(obj)
function R = getRFromSpice(netlistName)
function [Vin,data,data1]=readRaw(infile)
SOURCE CODE
classdef Lamina1
    %% usage example:
    % a=Fiber('AS4')
    % b= Fiber('IM7')
    % AS4prop =a.property
    properties
        propertyStruct ={}
    end
    methods
        function obj = Lamina1(val)
            obj.propertyStruct=struct;
            obj.propertyStruct.name = 'myLamina';
            obj.propertyStruct.volumeFraction = 0.5;
            obj.propertyStruct.pressure = 8e5;
            obj.propertyStruct.dimension = '[1e-2,1e-3,1e-3]';
            %obj.propertyStruct.fiber = Fiber1('AS4');
            obj.propertyStruct.fiber = 'AS4'
            obj.propertyStruct.packOrder = 'Square';
            if nargin>0
                obj.propertyStruct.name = val;
            end
        end
        function resistivityTensor = clacResistivityTensor(obj)
        end
        function showOnGui(obj,tableHandle)
            tempCell = struct2cell(obj.propertyStruct);
            %tempCell{5}=obj.propertyStruct.fiber.propertyStruct.name;
            for i = 1:length(tempCell)
                item = tempCell{i}
                if isnumeric(item)
                    tempCell{i} = mat2str(item,3)
                end
            end
            propertyUnit = {'string','string','number between 0 and 1 ','Pa','choose one','m'}';
            tableHandle.Data=[tempCell,propertyUnit];
            tableHandle.ColumnName ={'Property Value','Unit/Description'}
            colNames = {'Lamina Name','Volume Fraction','Pressure','Dimension','Fiber','Pack Order'};
            tableHandle.RowName =colNames;
        end
        function  resistivityTensor = getResistivityTensor(obj)
            xResistivity = obj.getXResistivity;
            yResistivity = obj.getYResistivity;
            zResistivity =obj.getZResistivity;
            resistivityTensor =[xResistivity yResistivity zResistivity];
        end
        function xResistivity = getXResistivity(obj)
            xResistivity =obj.propertyStruct.fiber.propertyStruct.electricalResistivity/obj.propertyStruct.volumeFraction;
        end
        function yResistivity = getYResistivity(obj)
            if 1
            yResistivity = rand()
            pause(0.9)
            return
            end
            yResistivity = obj.getZResistivity;
        end
        function zResistivity = getZResistivity(obj)
            if 1
            zResistivity = rand()
            waitfor(4)
            return
            end
            %fibermat = get2dStructure(obj)
            fiberMatPath= '2dStructure';
            fiberMatName = 'vf_0.4_spec1.mat';
            fibermat = fullfile(fiberMatPath,fiberMatName);
            netlistName = 'laminaNetlist';
            fiberLength=2e-3;
            beta=300;
            fiberRadius=3e-6;
            fiberResistivity = 1.5e-5;
            obj.writeLaminaNetlist(netlistName,fibermat,fiberLength,beta,fiberRadius,fiberResistivity)
            R = obj.getRFromSpice(netlistName)
            width = 1e-3;
            thickness = 1e-3;
            zResistivity = R*width*thickness/fiberLength
        end
    end
    methods(Static)
        writeLaminaNetlist(netlistName,fibermat,fiberLength,beta,fiberRadius,fiberResistivity);
        function R = getRFromSpice(netlistName)
            filePath = 'SPICE\'
            netlistId= strcat(netlistName,'.cir');
            netlistPathName = [filePath,netlistId];
            systemCMD = ['scad3.exe',' -b -ascii ',netlistPathName];
            p=system(systemCMD);
            rawPathName = [filePath,netlistName,'.raw'];
            [current,~,~]=readRaw(rawPathName);
            R=1.0/abs(current);
            function [Vin,data,data1]=readRaw(infile)
                fidin=fopen(infile,'r'); %
                % fidtmp=fopen(tmpfile,'w');
                data1=[];
                while ~feof(fidin)
                    tline=fgetl(fidin);
                    if ~isempty(tline)
                        str = '[^0-9 | \. | \- | \+ | \s | e | E]';
                        start = regexp(tline,str, 'once');
                        if isempty(start)
                            %% following 2 lined added
                            LocSpace = regexp(tline,'[\s]');
                            if LocSpace(1)~=1
                                Vin1=str2num(tline);
                                Vin=Vin1(2);
                            else
                                data1(end+1)=str2num(tline);
                            end
                        end
                    end
                end
                fclose(fidin);
                % data1=textscan(tmpfile);
                data2 = fliplr(data1);
                data=data2(1:end-1);
            end
        end
    end
end
%         function resistivityTensor = clacResistivityTensor(obj)
%         end
%         function val = get.propertyTable(obj)
%             struct = obj.propertyStruct;
%             struct.fiber = obj.propertyStruct.fiber.propertyStruct.name
%             val= struct2table(struct);
%           function obj= set.propertyTable(obj,tableObj)
%              obj.propertyTable = tableObj;
%         end
%     properties (Dependent)
%         propertyTable=table()
%     end
% property = struct({'Name','Diameter','Electrical Resistivity'
%property = struct
%field='name'
%value='as4'
%property = struct(field,value)
%property.name ='AS4'
%          property.Diameter = 5e-5
%          property.ElectricalResistivity
%          property.ThermalConductivity
%          property.EModulus