Description of get
Home > v08 > m2html > @template > get.m
get
PURPOSE
TEMPLATE/GET Access data stored in a Template object
SYNOPSIS
function varargout = get(tpl,action,varargin)
DESCRIPTION
TEMPLATE/GET Access data stored in a Template object
  TPL = GET(TPL,ACTION,VARARGIN)
     ACTION 'var'
     ACTION 'undefined'
CROSS-REFERENCE INFORMATION
This function calls:
char TEMPLATE Convert a template object in a one line description string
get TEMPLATE/GET Access data stored in a Template object
finish TEMPLATE/FINISH Apply given strategy to unknown fields in a string
loadtpl TEMPLATE/LOADTPL Read a template from file
This function is called by:
CFRP_GUI_v08 GUI for 3D resistor network
Fiber_plott_GUI FIBER_PLOTT_GUI MATLAB code for Fiber_plott_GUI.fig
GUItest1 GUITEST1 MATLAB code for GUItest1.fig
RNetworkGUI RNETWORKGUI MATLAB code for RNetworkGUI.fig
RNetworkGUI1 RNETWORKGUI1 MATLAB code for RNetworkGUI1.fig
SIM_Compare_Combine_GUI SIM_COMPARE_COMBINE_GUI MATLAB code for SIM_Compare_Combine_GUI.fig
SIM_Compare_Combine_GUI_table SIM_COMPARE_COMBINE_GUI_TABLE MATLAB code for SIM_Compare_Combine_GUI_table.fig
SIM_Compare_GUI SIM_COMPARE_GUI MATLAB code for SIM_Compare_GUI.fig
SIM_Compare_Hexagonal_GUI SIM_COMPARE_HEXAGONAL_GUI MATLAB code for SIM_Compare_Hexagonal_GUI.fig
SIM_Compare_Square_GUI SIM_COMPARE_SQUARE_GUI MATLAB code for SIM_Compare_Square_GUI.fig
Test_uitable TEST_UITABLE MATLAB code for Test_uitable.fig
get TEMPLATE/GET Access data stored in a Template object
parse TEMPLATE/PARSE Fill in replacement fields with the class properties
loadtpl TEMPLATE/LOADTPL Read a template from file
subst TEMPLATE/SUBST Substitute a replacement field by its value
set TEMPLATE/SET Edit data stored in a Template object
m2html M2HTML - Documentation Generator for Matlab M-files and Toolboxes in HTML
mwizard MWIZARD - M2HTML Graphical User Interface
mwizard2 MWIZARD - M2HTML Graphical User Interface
SOURCE CODE
function varargout = get(tpl,action,varargin)
%TEMPLATE/GET Access data stored in a Template object
%  TPL = GET(TPL,ACTION,VARARGIN)
%     ACTION 'var'
%     ACTION 'undefined'
%  Copyright (C) 2003 Guillaume Flandin <Guillaume@artefact.tk>
%  $Revision: 1.0 $Date: 2003/05/05 22:19:51 $
error(nargchk(2,3,nargin));
switch lower(action)
    case 'var'
        error(nargchk(2,3,nargin));
        if nargin == 2
            varargout{1} = tpl.varvals;
        elseif iscellstr(varargin{1})
            varargout{1} = {};
            for i=1:length(varargin{1})
                key = find(ismember(tpl.varkeys,varargin{1}{i}));
                if isempty(key)
                    %error('[Template] No such variable name.');
                    varargout{1}{end+1} = '';
                else
                    varargout{1}{end+1} = tpl.varvals{key};
                end
            end
        elseif ischar(varargin{1})
            varargout{1} = char(get(tpl,'var',cellstr(varargin{1})));
        else
            varargout{1} = '';
        end
    case 'undefined'
        error(nargchk(3,3,nargin));
        tpl = loadtpl(tpl,varargin{1});
        str = get(tpl,'var',varargin{1});
        varargout{1} = {};
        %%%%%%%%%%%%%%%%%%%%%%%% WIH REGEXP ONLY %%%%%%%%%%%%%%%%%%%%
        % [b, e] = regexp(str,'{[^ \t\r\n}]+}');
        % for i=1:length(b)
        %     if ~any(ismember(tpl.varkeys,str(b(i)+1:e(i)-1)))
        %         varargout{1}{end+1} = str(b(i)+1:e(i)-1);
        %    end
        % end
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    otherwise
        varargout{1} = finish(get(tpl,'var',action),tpl.unknowns);
end