Description of Fiber1
Home > v08 > @Fiber1 > Fiber1.m
Fiber1
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
Fiber1
This function is called by:
Fiber1
FiberLib
addFiber
addFiber_callback
removeFiber_callback
SUBFUNCTIONS
function obj = Fiber1(val)
function showOnGui(obj,tableHandle)
function obj = constructFromTable(obj,tableData)
SOURCE CODE
classdef Fiber1
    % Fiber : class representing fiber in composite materials.
    % To check properites and methods of fiber, press "tab" button after
    % typing "Fiber1."
    %
    % usage example:
    % a=Fiber('AS4')
    % b=Fiber('IM7')
    % AS4prop =a.property
    %
    % see also FiberLib
    % -- copyright 2014-2016 Hong Yu, hongyu.us@gmail.com --
    properties
        propertyStruct ={};
    end
    methods
        function obj = Fiber1(val)
            obj.propertyStruct=struct;
            obj.propertyStruct.name = 'myFiber';
            obj.propertyStruct.diameter = 7.1e-6;
            obj.propertyStruct.electricalResistivity = 1.7e-5;
            obj.propertyStruct.thermalConductivity = 10;
            obj.propertyStruct.elasticModulus = 271e9;
            obj.propertyStruct.beta = 350;
            if nargin>0
                obj.propertyStruct.name = val;
            end
            switch obj.propertyStruct.name
                case 'AS4'
                    obj.propertyStruct.diameter = 7.1e-6;
                    obj.propertyStruct.electricalResistivity = 1.7e-5;
                    obj.propertyStruct.thermalConductivity = 10;
                    obj.propertyStruct.elasticModulus = 271e9;
                case 'IM7'
                    obj.propertyStruct.diameter = 5.2e-6;
                    obj.propertyStruct.electricalResistivity = 1.5e-5;
                    obj.propertyStruct.thermalConductivity = 10;
                    obj.propertyStruct.elasticModulus = 260e9;
                otherwise
            end
        end
        function showOnGui(obj,tableHandle)
            %data = struct2cell(obj.propertyStruct);
            tempCell = struct2cell(obj.propertyStruct);
            for i = 1:length(tempCell)
                item = tempCell{i};
                if isnumeric(item)
                    tempCell{i} = num2str(item,'%3.5g');
                end
            end
            %propertyValue =
            propertyUnit = {'string','m','ohm*m','W/(mK)','Pa','number'}';
            tableHandle.Data=[tempCell propertyUnit];
            tableHandle.ColumnName ={'Property Value','Property Unit'}
            tableHandle.RowName ={'Fiber Name','Diameter','Electrical Resistivity','Thermal Conductivty',...
                'Elastic Modulus','Beta Term'}
        end
        function obj = constructFromTable(obj,tableData)
            tableData=tableData(:,1);
            fieldNames = fieldnames(obj.propertyStruct);
            obj.propertyStruct = cell2struct(tableData,fieldNames,1);
        end
           % properties =
    end
end
    %     properties (Dependent)
    %         propertyTable = table();
    %     end
%obj.propertyStructTable = struct2table(obj.propertyStruct)
% property = struct({'Name','Diameter','Electrical Resistivity'
%property = struct
%field='name'
%value='as4'
%property = struct(field,value)
%property.name ='AS4'
%          property.Diameter = 5e-5
%          property.ElectricalResistivity
%          property.ThermalConductivity
%          property.EModulus
%             function obj= set.propertyTable(obj,tableObj)
%             obj.propertyTable = tableObj;
%         end
%         function val = get.propertyTable(obj)
%             tempCell = struct2cell(obj.propertyStruct);
%
%             for i = 1:length(tempCell)
%                 item = tempCell{i};
%                 if isnumeric(item)
%                     tempCell{i} = num2str(item,'%3.5g');
%                 end
%             end
%             val = cell2table(tempCell);
%         end