Description of CFRP_GUI_v08
Home > v08 > GUI > CFRP_GUI_v08.m
CFRP_GUI_v08
PURPOSE
GUI for 3D resistor network
SYNOPSIS
function [allHandles,allData] = CFRP_GUI_v08()
DESCRIPTION
 GUI for 3D resistor network
 -- copyright 2014-2016 Hong Yu, hongyu.us@gmail.com --
CROSS-REFERENCE INFORMATION
This function calls:
FiberLib
LaminaLib
LaminateLib
createTree2
showTree [mtree,treecontainer] = uitree('v0', 'Root',root);
get TEMPLATE/GET Access data stored in a Template object
set TEMPLATE/SET Edit data stored in a Template object
This function is called by:
SUBFUNCTIONS
function allData = createData()
function allHandles= createFrame()
function createHeader
function createCopyRight
SOURCE CODE
function [allHandles,allData] = CFRP_GUI_v08()
% GUI for 3D resistor network
% -- copyright 2014-2016 Hong Yu, hongyu.us@gmail.com --
% set working director
[path,filename,extension]=fileparts(which('scad3.exe'));
cd(path);
%cd ..
path = pwd;
addpath(path)
%1. create GUI frame layout
%[Fig_h,treePanel, materialPropertyTable, simulationParameterTable,fig1,fig2,allHandles] = createFrame()
allHandles = createFrame();
allData = createData();
figureHandle = gcf
guidata(figureHandle,allData);
    function allData = createData()
allData = {};
allData.topFolderPath = mfilename('fullpath');
%% load default material lib
fiberLibObj = FiberLib();
laminateLibObj =  LaminateLib();
laminaLibObj = LaminaLib();
allData.fiberLib = fiberLibObj;
allData.laminateLib =laminateLibObj;
allData.laminaLib = laminaLibObj ;
[mtree1,treecontainer1] = createTree2(allData);
allData.mtree = mtree1;
allData.treeContainer = treecontainer1;
    end
%% display tree
showTree(allHandles,allData);
%%
%     function showTree(root,allHandles,allData) %materialBrowserLayout
%         [mtree,treecontainer] = uitree('v0', 'Root',root);
%         set(treecontainer,'Parent',allHandles.treePanel);
%         set(mtree, 'NodeSelectedCallback', {@treeNode_callback,allHandles,allData})
%     end
    function allHandles= createFrame()
        %% create GUI outbox
        scr_size = get(0,'ScreenSize');
        Fig_h = figure( ...
            'MenuBar','none','Name','CFRP 3D Resistor Network Model',...
            'OuterPosition',[(scr_size(1:2)+100) scr_size(3)-500 scr_size(4)-200],...
            'Tag','GUI_Fig','NumberTitle','off');
        movegui(Fig_h,'center')
        allHandles={};
        %% # create header,body,footer
        vertLayout = uix.VBoxFlex('Parent',Fig_h,'Spacing',0);
        if 1
            createHeader;  % create Header with CCM logo in vertLayout
            horzLayout = uix.HBoxFlex('Parent',vertLayout,'Spacing',5);
            if 1
                %% ## create 2 columns for body  (1. material browser and 2. Plot)
                materialBrowserPanel = uix.BoxPanel('Parent',horzLayout,'Title','Material Browser','FontSize',12);
                if 1
                    materialBrowserLayout = uix.HBoxFlex('Parent',materialBrowserPanel,'Spacing',5);
                    allHandles.treePanel = uix.Panel('Parent',materialBrowserLayout,'Tag','treePanel','Title','','FontSize',10);
                    detailPanel = uix.Panel('Parent',materialBrowserLayout,'Title','Material Properties','FontSize',10);
                    % set(materialBrowserLayout,'Widths',[200 -1])
                    detailLayout = uix.VBoxFlex('Parent',detailPanel,'Spacing',5);
                    if 1
                        propertyPanel = uix.Panel('Parent',detailLayout);
                        add2LibBtnPanel = uix.Panel('Parent',detailLayout);
                        parameterPanel = uix.Panel('Parent',detailLayout);
                        runSimBtnPanel = uix.Panel('Parent',detailLayout);
                    end
                    set(detailLayout,'Heights',[-1 35 -1 60])
                end
                viewPanel = uix.BoxPanel('Parent',horzLayout,'Title','Plot','FontSize',12);
                set(horzLayout,'Widths',[-3 -2.5]);
            end
            createCopyRight( );                                  % create copy right box in the bottom
            set(vertLayout,'Heights',[55 -4 35]);            % height of copyright box set to 30
        end
        %% ### create 2 columns in materialBrowserPanel
        %allHandles.chooseFiber
        if 1  % create 2 tables on propertyPanel
            allHandles.materialPropertyLayout = uix.VBoxFlex('Parent',propertyPanel,'Spacing',0);
            if 1
                allHandles.materialPropertyTable = uitable('Parent',allHandles.materialPropertyLayout,'Tag','materialPropertyTable');
                allHandles.chooseFiberTable = uitable('Parent',allHandles.materialPropertyLayout);
                allHandles.choosePackOrderTable = uitable('Parent',allHandles.materialPropertyLayout);
                allHandles.chooseFiberTable.Visible = 'on';
                allHandles.choosePackOrderTable.Visible='off';
            end
            set(allHandles.materialPropertyLayout,'Height',[-5 -1 -1]);
        end
        addToLibBtnLayout = uix.HBoxFlex('Parent',add2LibBtnPanel,'Spacing',5);
        if 1
            allHandles.removeFromLibBtn = uicontrol(addToLibBtnLayout ,'Tag','runSimulationBtn','String','remove from library');
            allHandles.add2LibBtn = uicontrol(addToLibBtnLayout ,'Tag','runSimulationBtn','String','add to library');
        end
        set(addToLibBtnLayout,'Width',[-1 -1])
        % simulationParameterPanel = uix.BoxPanel('Parent',detailLayout,'Tag','simulationParameterPanel','Title','Simulation Parameters','FontSize',12);
        allHandles.simulationParameterTable = uitable('Parent',parameterPanel,'Tag','simulationParameterTable');
        %runSimulationPanel = uix.Panel('Parent',detailLayout);
        runSimBtnLayout = uix.HButtonBox('Parent',runSimBtnPanel);
        allHandles.runSimulationBtn = uicontrol(runSimBtnLayout ,'Tag','runSimulationBtn','String','Run Simulation');
        set( runSimBtnLayout, 'ButtonSize', [300 70], 'Spacing', 5 );
        allHandles.runSimulationBtn.Visible='off';
        % button to calculate
        %ru = uix.HButtonBox('Parent',runSimulationPanel)
        % calculateButton = uicontrol(calculateButtonLayout ,'String','Calculate Resistivity','Callback',@calculateButton_callback)
        % set( calculateButtonLayout, 'ButtonSize', [180 35], 'Spacing', 5 );
        % ### create tabbed plot window
        viewContainer = uicontainer('Parent',viewPanel);
        tabgp = uitabgroup(viewContainer);
        tab1 = uitab(tabgp,'Title','Resistivity');
        plotLayout1 = uix.VBoxFlex('Parent',tab1)
        allHandles.fig1 = axes( 'Parent', plotLayout1, 'ActivePositionProperty', 'outerposition' );
        %set(plotLayout1,'Heights',[35 -1]);
        tab2 = uitab(tabgp,'Title','Voltage and Current');
        plotLayout2 = uix.VBoxFlex('Parent',tab2);
        allHandles.fig2 = axes( 'Parent', plotLayout2,'ActivePositionProperty', 'outerposition' );
        %         rnames = [];
        % cnames = {'Ply Number','Ply Angle','Lamina','Resistivity X','Resistivity Y','Resistivity Z'};
        % detailTable = uitable('Parent',detailLayout,'ColumnName',cnames,'RowName',rnames); %'RowName',rnames
        % detailTable.Position(3) = detailLayout.Position(3);
        % detailTable.ColumnWidth = {150,50,50,'auto'};
        % detailTable.RowStriping = 'on';
        % cNamesTable2 = {'X Resistivity','Y Resistivity','Z Resistivity'};
        %
        % laminaTable2 = uitable('Parent',detailLayout,'ColumnName',cNamesTable2,...
        %     'RowName',[],'Visible','off'); %'RowName',rnames
        %% set window size
        %set(materialBrowserLayout,'Widths',[170 -1])
        %set(vertLayout,'Heights',[50 -4 30]); % height of copyright box set to 30
        set(materialBrowserLayout,'Widths',[200 -1]);
        % set(simulationSettingsLayout,'Heights',[-1 15 -1 60])
        function createHeader
            %header
            headerLayout = uix.HBoxFlex('Parent',vertLayout,'BackgroundColor',[1 1 1]);
            %         axes_UDLogo = axes( 'Parent',headerLayout, ...
            %             'ActivePositionProperty', 'Position' );
            %UDLogo = imshow('images/UDLogo.jpg');
            % blank = uix.Empty('Parent',headerLayout)
            TitleLayout = uix.VBoxFlex('Parent',headerLayout)
            Title = uicontrol(TitleLayout,'Style','text','String','3D Resistor Network Model for CFRP',...
                'BackgroundColor',[1 1 1],...
                'ForegroundColor','b',...
                'FontSize',20);
            %         axes_CCMLogo = axes( 'Parent',headerLayout, ...
            %             'ActivePositionProperty', 'Position' );
            % CCMLogo = imshow('images/CCMLogoName1.png');
            set(headerLayout,'Widths',[ -1]);
        end
        function createCopyRight
            myMessage = ['3D Resistor Network Model for CFRP   |', ...
                '   2014-2016   |',...
                '   hongy@udel.edu, hongyu.us@gmail.com']
            messagePanel = uix.BoxPanel('Parent',vertLayout,'Title',['Copyright ' myMessage],'FontSize',10);
        end
    end
end
%{
what can be done
%}