Description of ContactForce_Exp
Home > v08 > helper > ContactForce_Exp.m
ContactForce_Exp
PURPOSE
SYNOPSIS
function [Fc,Pressure] = ContactForce_Exp(V0,Va,VF,beta,E,fiberRadius)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
RNetworkGUI1 RNETWORKGUI1 MATLAB code for RNetworkGUI1.fig
SIM_Compare_Combine_GUI SIM_COMPARE_COMBINE_GUI MATLAB code for SIM_Compare_Combine_GUI.fig
SIM_Compare_Combine_GUI_table SIM_COMPARE_COMBINE_GUI_TABLE MATLAB code for SIM_Compare_Combine_GUI_table.fig
SIM_Compare_GUI SIM_COMPARE_GUI MATLAB code for SIM_Compare_GUI.fig
SIM_Compare_Hexagonal_GUI SIM_COMPARE_HEXAGONAL_GUI MATLAB code for SIM_Compare_Hexagonal_GUI.fig
SIM_Compare_Square_GUI SIM_COMPARE_SQUARE_GUI MATLAB code for SIM_Compare_Square_GUI.fig
SIM_Comparison_R_VF_AS4 % convergence test: Rz; Square Packing; IM7
SIM_Convergence_Square_IM7 % convergence test: Rz; Square Packing; IM7
SIM_Pressure_IM7_Gutowski % Statistical representation: beta
test % Statistical representation: beta
SOURCE CODE
function [Fc,Pressure] = ContactForce_Exp(V0,Va,VF,beta,E,fiberRadius)
Pressure = abs(3*pi*E/beta^4*(1-sqrt(VF/V0))/(sqrt(Va/VF)-1)^4);
a=fiberRadius*(sqrt(pi/VF)-2); % fiber spacing
Fc=Pressure*(2*fiberRadius+a)*a*beta;