Description of ContactR
Home > v08 > helper > ContactR.m
ContactR
PURPOSE
% contact resistance
SYNOPSIS
function Rc = ContactR(fiberRadius,Fc,E,rf)
DESCRIPTION
% contact resistance
 F is loading at contact point; E is fiber modulus;
 rho is fiber resistivity
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
Function
Interface_layer_simulation % 3D Resistor Network Modle by Hong Yu
RNetworkGUI1 RNETWORKGUI1 MATLAB code for RNetworkGUI1.fig
RvsPressure
SIM_Compare_Combine_GUI SIM_COMPARE_COMBINE_GUI MATLAB code for SIM_Compare_Combine_GUI.fig
SIM_Compare_Combine_GUI_table SIM_COMPARE_COMBINE_GUI_TABLE MATLAB code for SIM_Compare_Combine_GUI_table.fig
SIM_Compare_GUI SIM_COMPARE_GUI MATLAB code for SIM_Compare_GUI.fig
SIM_Compare_Hexagonal_GUI SIM_COMPARE_HEXAGONAL_GUI MATLAB code for SIM_Compare_Hexagonal_GUI.fig
SIM_Compare_Square_GUI SIM_COMPARE_SQUARE_GUI MATLAB code for SIM_Compare_Square_GUI.fig
SIM_Comparison_R_VF_AS4 % convergence test: Rz; Square Packing; IM7
SIM_Convergence_Square_IM7 % convergence test: Rz; Square Packing; IM7
SIM_Convergence_Square_IM7[Conflict 1] % convergence test: Rz; Square Packing; IM7
SIM_Convergence_Square_IM7[Conflict 2] % convergence test: Rz; Square Packing; IM7
SIM_Convergence_Square_IM7[Conflict 3] % convergence test: Rz; Square Packing; IM7
SIM_Convergence_Square_IM7[Conflict] % convergence test: Rz; Square Packing; IM7
SIM_Pressure_IM7 % Statistical representation: beta
SIM_Pressure_IM7_Gutowski % Statistical representation: beta
SIM_beta_Dis_IM7 % Statistical representation: beta
Sensitivity_Study_Taguchi % Sensitivity study of 3D Resistor Network MOdel using Taguchi Technique
SOURCE CODE
function Rc = ContactR(fiberRadius,Fc,E,rf)
%% contact resistance
% F is loading at contact point; E is fiber modulus;
% rho is fiber resistivity
Rc=rf/(1.76*(Fc*fiberRadius/E)^(1/3));