Description of createTree2
Home > v08 > helper > createTree2.m
createTree2
PURPOSE
SYNOPSIS
function [mtree,treecontainer] = createTree2(allData)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
addFiber
addLamina
addLaminate
displayFiberInfo % selectedNode is a string of fiber name, handles and allData are global struct
set TEMPLATE/SET Edit data stored in a Template object
This function is called by:
addFiber_callback
addLamina_callback
addLaminate_callback
removeFiber_callback
removeLamina_callback
CFRP_GUI_v08 GUI for 3D resistor network
SUBFUNCTIONS
function addFiberNodes(FiberNode,fiberLibObj)
function addLaminaNodes(LaminaNode,laminaLibObj);
function addLaminateNodes(LaminateNode,laminateLibObj);
function selected_cb(tree, ev)
function displayFiberInfo(selectedNode)
function displayLaminaInfo(selectedNode)
function displayLaminateInfo(selectedNode)
SOURCE CODE
    function  [mtree,treecontainer] = createTree2(allData)
    fiberLibObj = allData.fiberLib;
    laminaLibObj = allData.laminaLib;
    laminateLibObj =allData.laminateLib;
        root = uitreenode('v0', 'MaterialLib', 'Material Library', [], false);
        FiberNode=uitreenode('v0', 'FiberNode', 'Fiber', [],false);
        LaminaNode= uitreenode('v0', 'LaminaNode', 'Lamina', [],false);
        LaminateNode=uitreenode('v0', 'LaminateNode', 'Laminate', [],false);
        root.add(FiberNode);
        root.add(LaminaNode);
        root.add(LaminateNode);
        addFiberNodes(FiberNode,fiberLibObj);
        addLaminaNodes(LaminaNode,laminaLibObj);
        addLaminateNodes(LaminateNode,laminateLibObj);
        %mtree.expand(FiberNode);
%         LaminaNode.expand;
%         LaminateNode.expand;
        function addFiberNodes(FiberNode,fiberLibObj)
            fiberNames = fiberLibObj.itemNames
            for i = 1:length(fiberNames)
                fiberNodeName = fiberNames{i};
                fiberTagName =['Fiber' num2str(i)];
                fiberNodes(i) =uitreenode('v0',fiberTagName,fiberNodeName,[],true);
                FiberNode.add(fiberNodes(i));
            end
            addFiber = uitreenode('v0', 'addFiber', 'Add Fiber', [],false);
            FiberNode.add(addFiber);
        end
        function addLaminaNodes(LaminaNode,laminaLibObj);
            laminaNames = laminaLibObj.getNames()
            for i = 1:length(laminaNames)
                NodeName = laminaNames{i};
                TagName =['Lamina' num2str(i)];
                laminaNodes(i) =uitreenode('v0',TagName,NodeName,[],true);
                LaminaNode.add(laminaNodes(i));
            end
            addLamina = uitreenode('v0', 'addLamina', 'Add Lamina', [],false);
            LaminaNode.add(addLamina);
        end
        function addLaminateNodes(LaminateNode,laminateLibObj);
            laminateNames = laminateLibObj.getNames()
            for i = 1:length(laminateNames)
                NodeName = laminateNames{i};
                TagName =['Laminate' num2str(i)];
                laminateNodes(i) =uitreenode('v0',TagName,NodeName,[],true);
                LaminateNode.add(laminateNodes(i));
            end
            addLaminate = uitreenode('v0', 'addLaminate', 'Add Laminate', [],false);
            LaminateNode.add(addLaminate);
        end
    [mtree,treecontainer] = uitree('v0', 'Root',root);
    end
%         [mtree treecontainer] = uitree('v0', 'Root',root);
%         mtree.expand(root);
%        set(mtree, 'NodeSelectedCallback', @selected_cb)
%{
        function selected_cb( tree, ev )
            nodes = tree.getSelectedNodes;
            if length(nodes)
                node = nodes(1);
                p = node2path(node);
                if length(p)==3
                    selectedNode =p{end};
                    switch p{2}
                        case 'Fiber'
                            displayFiberInfo(selectedNode);
                        case 'Lamina'
                            displayLaminaInfo(selectedNode);
                        case 'Laminate'
                            displayLaminateInfo(selectedNode);
                    end
                end
            end
        end
        function displayFiberInfo(selectedNode)
            [~,index] = ismember(selectedNode,fiberNames);
            if index
                detailTable.ColumnWidth = {80,80,50,'auto'};
                calcRhoBtn.Visible = 'off'
                laminaTable2.Visible ='off'
                set(detailLayout,'Heights',[200 -1 -1 -1])
                detailTable.ColumnFormat = ({[],[],[],[],[]});
                selectedData = struct2cell(fiberLib(index));
                fiberPropertyNames = fieldnames(fiberLib);
                tableData = [fiberPropertyNames selectedData fiberUnits fiberDiscriptions];
                detailTable.Data = tableData;
                detailTable.RowName = [];
                detailTable.ColumnName = {'Properties','Value', 'Unit','Description'}';
                detailTable.ColumnFormat = ({[],[],[],[],[]});
                % updateMaterialTable(selectedData);
                add2ModelBtn.Visible ='off';
            end
            if strcmp(selectedNode,'Add Fiber')
                detailTable.ColumnWidth = {80,80,50,'auto'};
                detailTable.ColumnEditable = [false true false true]
                calcRhoBtn.Visible = 'off'
                add2ModelBtn.Visible ='on';
                laminaTable2.Visible ='off'
                set(detailLayout,'Heights',[200 15 35 -1])
                detailTable.ColumnFormat = ({[],[],[],[]});
                setappdata(detailTable,'materialLevel','Fiber')
            end
            if strcmp(selectedNode,'Add Laminate')
                add2ModelBtn.Visible ='on';
                setappdata(detailTable,'materialLevel','Laminate')
            end
        end
        function displayLaminaInfo(selectedNode)
            [~,index] = ismember(selectedNode,laminaNames)
            if index
                detailTable.ColumnWidth = {80,80,50,'auto'};
                calcRhoBtn.Visible = 'off'
                laminaTable2.Visible ='off'
                set(detailLayout,'Heights',[300 -1 -1 -1])
                detailTable.ColumnFormat = ({[],[],[],[],[]});
                disp('Look here!!!!!')
                index
                laminaLib(index)
                selectedData = struct2cell(laminaLib(index))
                PropertyNames = fieldnames(laminaLib)
                tableData = [PropertyNames selectedData laminaUnits laminaDiscriptions];
                detailTable.Data = tableData;
                detailTable.RowName = [];
                detailTable.ColumnName = {'Properties','Value', 'Unit','Description'}';
                % updateMaterialTable(selectedData);
                add2ModelBtn.Visible ='off';
            end
            if strcmp(selectedNode,'Add Lamina')
                add2ModelBtn.Visible ='on';
                calcRhoBtn.Visible = 'on'
                laminaTable2.Visible ='on'
                %detailTable.ColumnWidth = [100 100 100]
                set(detailLayout,'Heights',[100 100 40 -1])
                detailTable.ColumnWidth = {100,100,100,100};
                laminaTable2.ColumnWidth = {133,133,134};
                setappdata(detailTable,'materialLevel','Lamina')
                newLamina.Name = 'new Lamina';
                newLamina.Fiber = 'AS4';
                newLamina.VF = 0.55;
                newLamina.PackingOrder = 'Square';
                PackingOrderSelections = {'Square','Hexagon','Random'}
                detailTable.ColumnName = fieldnames(newLamina)
                detailTable.Data = struct2cell(newLamina)'%{'new Lamina','AS4'}
                detailTable.ColumnFormat = ({[],fiberNames','numeric',PackingOrderSelections});
                laminaTable2.Visible ='on'
                laminaTable2.Data ={[] [] []}
                %                 cNamesTable2 = {'X Resistivity','Y Resistivity','Z Resistivity'};
                %
                %                 laminaTable2 = uitable('Parent',detailLayout,'ColumnName',cNamesTable2); %'RowName',rnames
                %
            end
        end
        function displayLaminateInfo(selectedNode)
            [~,index] = ismember(selectedNode,laminateNames);
            if index
                detailTable.ColumnWidth = {80,80,'auto'};
                calcRhoBtn.Visible = 'off'
                laminaTable2.Visible ='off'
                set(detailLayout,'Heights',[300 35 35 -1])
                LaminaSelections = laminaNames';
                cnames = {'Ply #','Ply Angle','Lamina'}
                detailTable.ColumnName = cnames
                detailTable.RowName =[];
                detailTable.ColumnFormat = ({[],[],LaminaSelections});
                detailTable.ColumnEditable = [false,true,true]
                % selectedData = struct2cell(laminateLib(index))'
                %PropertyNames = fieldnames(laminateLib);
                T1 = struct2table(laminateLib(index))
                C1=table2cell(T1)
                detailTable.Data =C1
                %tableData = [selectedData']
                %                 data1= struct2cell(laminateLib(index))
                %                 tableData = [data1.PlyNumber data1.PlyAngle data1.Lamina]
                %                 detailTable.Data = data1;
                %detailTable.RowName = [];
                %  detailTable.ColumnName = {'Ply #','Ply Angle', 'Lamina','Resistivity X','Resistivity Y','Resistivity Z'}';
                % updateMaterialTable(selectedData);
                add2ModelBtn.Visible ='off';
            end
            if strcmp(selectedNode,'Add Laminate')
                set(detailLayout,'Heights',[300 35 35 -1])
                add2ModelBtn.Visible ='on';
                setappdata(detailTable,'materialLevel','Laminate')
            end
        end
 %}