Description of createnode
Home > v08 > helper > createnode.m
createnode
PURPOSE
UNTITLED2 Summary of this function goes here
SYNOPSIS
function [ nodes ] = createnode(fiber,ref,perc,N)
DESCRIPTION
UNTITLED2 Summary of this function goes here
   Detailed explanation goes here
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
Func_RhoZ_LTspice % example usage: copy the code inside " if 1==0 ... end" and run.
writeLaminaNetlist function NetListID = WriteNetlist_UD(Netlist_name,fibermat,fiberLen,beta,fiberRadius,rf,Rc)
FiberStructure % fiberData=FiberStructure(fibermat,perc,fiberLen,Beta,fiberRadius,NumBreak,RBreakage)
Func_RNetwork %
Func_RNetwork1 % this function is used when the input fibermat is from generated fiber data (not from SEM).
Func_RNetwork2 % this function is used when the input fibermat is from generated fiber data (not from SEM).
Func_RNetwork_X % this function is used when the input fibermat is from generated fiber data (not from SEM).
Func_RNetwork_Z % this function is used when the input fibermat is from generated fiber data (not from SEM).
Func_RhoZ_LTspice % example usage: copy the code inside " if 1==0 ... end" and run.
Func_fiber %
Hex_IM7_SEM3 %%% Hong Yu, 09/2013
RNetwork_Hex % this function is used when the input fibermat is from generated fiber data (not from SEM).
RNetwork_IMG % this function is used when the input fibermat is from generated fiber data (not from SEM).
RNetwork_Labview % this function is used when the input fibermat is from generated fiber data (not from SEM).
RNetwork_Random % this function is used when the input fibermat is from generated fiber data (not from SEM).
RNetwork_Random2 % this function is used when the input fibermat is from generated fiber data (not from SEM).
RNetwork_Random3 % this function is used when the input fibermat is from generated fiber data (not from SEM).
RNetwork_Square % this function is used when the input fibermat is from generated fiber data (not from SEM).
RNetwork_beta_Dis % Important!!! Before use, check in which direction the rho is calculated. (longitudinal or through-thickness)
ResistorNetwork_COMSOL % Resistor Network Model in COMSOL
TestMatlab2LTspice % write Model head
ThreeDNetwork aa=[1 2 3 5 9]
ThreeDNetwork2 aa=[1 2 3 5 9]
ThreeDNetwork4 aa=[1 2 3 5 9]
ThreeDNetwork5 aa=[1 2 3 5 9]
ThreeDNetwork6 aa=[1 2 3 5 9]
ThreeDNetwork7 aa=[1 2 3 5 9]
ThreeDNetworkR %
ThreeDNetwork_Hex_IM7_Para aa=[1 2 3 5 9]
ThreeDNetwork_Hex_IM7_SEM %%% Hong Yu, 09/2013
ThreeDNetwork_Hex_IM7_SEM2 %%% Hong Yu, 09/2013
ThreeDNetwork_Hex_IM7_SEM4 %%% Hong Yu, 09/2013
ThreeDNetwork_Hex_IM7_SEM5 %%% Hong Yu, 09/2013
ThreeDNetwork_Hex_IM7_SEM6 %%% Hong Yu, 09/2013
ThreeDNetwork_Hex_IM7_SEM[Conflict] %%% Hong Yu, 09/2013
ThreeDNetwork_Square_IM7_Para aa=[1 2 3 5 9]
ThreeDNetwork_hex_AS4 aa=[1 2 3 5 9]
ThreeDNetwork_square_AS4 aa=[1 2 3 5 9]
ThreeDNetwork_square_IM7 aa=[1 2 3 5 9]
ThreeDNetwork_triag aa=[1 2 3 5 9]
ThreeDNetwork_triag_IM7 aa=[1 2 3 5 9]
ThreeDNetwork_triag_IM7_para aa=[1 2 3 5 9]
ThreeD_IM7_generatedFibers %%% Hong Yu, 09/2013
WriteNetlist_UD % write Model head
kirchoff Script to solve a complicated KVL network
writeLaminaNetlist function NetListID = WriteNetlist_UD(Netlist_name,fibermat,fiberLen,beta,fiberRadius,rf,Rc)
SOURCE CODE
function [ nodes ] = createnode(fiber,ref,perc,N)
%UNTITLED2 Summary of this function goes here
%   Detailed explanation goes here
nodes=[];
k=1;
for i=1:N
    fiber_d=sqrt((fiber(i).center(1)-fiber(ref).center(1))^2+(fiber(i).center(2)-fiber(ref).center(2))^2);
    if (fiber_d<fiber(i).radius+fiber(ref).radius+perc) && (i~=ref)
        nodes(k)=i;
        k=k+1;
    end
end