Description of degtorad
Home > v08 > helper > degtorad.m
degtorad
PURPOSE
SYNOPSIS
function y = degtorad(x)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
transientNetlist TRANSIENTNETLIST Summary of this function goes here
transientNetlist1 TRANSIENTNETLIST1 Summary of this function goes here
transientNetlist10 TRANSIENTNETLIST10 Summary of this function goes here
transientNetlist11 TRANSIENTNETLIST1 Summary of this function goes here
CrossPly3 % Generate SPICE netlist
SOURCE CODE
function y = degtorad(x)
y = x * pi/180;