Description of deletenode
Home > v08 > helper > deletenode.m
deletenode
PURPOSE
UNTITLED Summary of this function goes here
SYNOPSIS
function [ new_fiber ] = deletenode(fiber,node,N)
DESCRIPTION
UNTITLED Summary of this function goes here
   Detailed explanation goes here
 new_fiber=[fiber(1:node-1) fiber(node+1:N)]; %deleting the node
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
ThreeDNetwork aa=[1 2 3 5 9]
ThreeDNetwork2 aa=[1 2 3 5 9]
kirchoff Script to solve a complicated KVL network
SOURCE CODE
function [ new_fiber ] = deletenode(fiber,node,N)
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here
% new_fiber=[fiber(1:node-1) fiber(node+1:N)]; %deleting the node
for i=1:N
    temp=fiber(i).nodes;
    fiber(i).nodes=temp(temp~=node); %deleting connections
end
fiber(node).nodes=[]; %deleting connections.
new_fiber=fiber;