Description of Func_RNetwork_Z
Home > v08 > helper > Func_RNetwork_Z.m
Func_RNetwork_Z
PURPOSE
% this function is used when the input fibermat is from generated fiber data (not from SEM).
SYNOPSIS
function [rho,fiber,VF,NumContacts]=Func_RNetwork_Z(fibermat,fiberLen,beta,fiberRadius,NumBreak,Rc,rf,RBreakage)
DESCRIPTION
% this function is used when the input fibermat is from generated fiber data (not from SEM).
  fibermat data structure: fiber.x, fiber.y,fiber.radius
% load data; scale data.
CROSS-REFERENCE INFORMATION
This function calls:
createnode UNTITLED2 Summary of this function goes here
This function is called by:
Interface_layer_simulation % 3D Resistor Network Modle by Hong Yu
RNetworkGUI1 RNETWORKGUI1 MATLAB code for RNetworkGUI1.fig
RvsPressure2 % convergence test: Rz; Square Packing; IM7
SIM_Compare_Combine_GUI SIM_COMPARE_COMBINE_GUI MATLAB code for SIM_Compare_Combine_GUI.fig
SIM_Compare_Combine_GUI_table SIM_COMPARE_COMBINE_GUI_TABLE MATLAB code for SIM_Compare_Combine_GUI_table.fig
SIM_Compare_GUI SIM_COMPARE_GUI MATLAB code for SIM_Compare_GUI.fig
SIM_Compare_Hexagonal_GUI SIM_COMPARE_HEXAGONAL_GUI MATLAB code for SIM_Compare_Hexagonal_GUI.fig
SIM_Compare_Square_GUI SIM_COMPARE_SQUARE_GUI MATLAB code for SIM_Compare_Square_GUI.fig
SIM_Comparison_R_VF_AS4 % convergence test: Rz; Square Packing; IM7
SIM_Convergence_Square_IM7 % convergence test: Rz; Square Packing; IM7
SIM_Convergence_Square_IM7[Conflict 1] % convergence test: Rz; Square Packing; IM7
SIM_Convergence_Square_IM7[Conflict 2] % convergence test: Rz; Square Packing; IM7
SIM_Convergence_Square_IM7[Conflict 3] % convergence test: Rz; Square Packing; IM7
SIM_Convergence_Square_IM7[Conflict] % convergence test: Rz; Square Packing; IM7
Sensitivity_Study_Taguchi % Sensitivity study of 3D Resistor Network MOdel using Taguchi Technique
SOURCE CODE
function [rho,fiber,VF,NumContacts]=Func_RNetwork_Z(fibermat,fiberLen,beta,fiberRadius,NumBreak,Rc,rf,RBreakage)
%% this function is used when the input fibermat is from generated fiber data (not from SEM).
%  fibermat data structure: fiber.x, fiber.y,fiber.radius
%% load data; scale data.
NumContacts=0;
%load('vf_0.6_spec2.mat'); % changed from fibermat to 'vf_0.6_spec2.mat'
% Note: after load(fibermat), fiber.x fiber.y fiber.z are all row vectors.
% Code below change row vectors into column vectors.
fiber.x=fiber.x';
fiber.y=fiber.y';
fiber.radius=fiber.radius';
% Now fiber.x fiber.y and fiber.radius are column vectors.
N=size(fiber.radius,1);%
% !!! be careful, depending on the fiber.radius being a row vector or
% column vector, this command can be size(...,2) for row vector
%or size(...,1) for column vectors.
fiber1= struct('center',[], 'radius',[], 'nodes', []);
aveRad=mean(fiber.radius);
scale=aveRad/fiberRadius;
fiber.x=fiber.x/scale;
fiber.y=fiber.y/scale;
fiber.radius=fiber.radius/scale;
%% get VF and a
minx=min(fiber.x)-fiberRadius;
miny=min(fiber.y)-fiberRadius;
maxx=max(fiber.x)+fiberRadius;
maxy=max(fiber.y)+fiberRadius;
xlen=maxx-minx;
ylen=maxy-miny;
% xlen=maxx-minx-2*fiberRadius;
% ylen=maxy-miny-2*fiberRadius;
Rsquare=fiber.radius'*fiber.radius;
VF=pi*Rsquare/(xlen*ylen);
%a=fiberRadius*(sqrt(pi/(VF))-2); % square packing
% a=fiberRadius*(sqrt(2*pi/(sqrt(3)*VF))-2); % hex packing
%% plot
% clf
% hold on
% viscircles([fiber.x fiber.y],fiber.radius,'LineWidth',2);
% axis([minx maxx miny maxy]);
%% restruct data
for i=1:N
    fiber1(i).center(1)=fiber.x(i);
    fiber1(i).center(2)=fiber.y(i);
    fiber1(i).radius=fiber.radius(i);
end
fiber=fiber1;
%% find fiber neigbbors
perc=1.8*fiberRadius;
for i=1:N
    fiber(i).nodes=createnode(fiber,i,perc,N);
end
% finish creating neighbors
% find floating fibers that are not connected to any fibers
nullnodes=[];
for i=1:N
    if size(fiber(i).nodes,2)==0
        nullnodes(end+1)=i;
    end
end
while ~isempty(nullnodes)
    fiber(nullnodes(1))=[];
    N1=size(fiber,2)
    for i=1:N1
        fiber(i).nodes=createnode(fiber,i,perc,N1);
    end
    nullnodes=[];
    for i=1:N1
        if size(fiber(i).nodes,2)==0
            nullnodes(end+1)=i;
        end
    end
end
%% Boundary
BoundX1=[];
BoundX2=[];
BoundY1=[];
BoundY2=[];
BoundZ1=[];
BoundZ2=[];
N=size(fiber,2);
% BoundZ1=[1:N];
% BoundZ2=[1:N];
for i=1:N
    if (fiber(i).center(1)<=minx+2*fiber(i).radius)
%     if (fiber(i).center(1)<=1.0*(2*a+fiber(i).radius))
        %fiber1(i).nodes=[fiber1(i).nodes 0]; %left boundary
        BoundX1(end+1)=i;
    end
    if (fiber(i).center(1)>=maxx-2*fiber(i).radius)
        %fiber1(i).nodes=[fiber1(i).nodes N+1]; % right boundary
        BoundX2(end+1)=i;
    end
    if (fiber(i).center(2)<=miny+2*fiber(i).radius)
        %fiber1(i).nodes=[fiber1(i).nodes 0]; %left boundary
        BoundY1(end+1)=i;
    end
    if (fiber(i).center(2)>=maxy-2*fiber(i).radius)
        %fiber1(i).nodes=[fiber1(i).nodes N+1]; % right boundary
        BoundY2(end+1)=i;
    end
end
%% Plot Left-Right BC
% for xbound=1:size(BoundX1,2)
%     node=BoundX1(xbound);
%     plot([minx-fiberRadius fiber(node).center(1)],[fiber(node).center(2) fiber(node).center(2)],'r*-','LineWidth',3);
% end
% for xbound=1:size(BoundX2,2)
%     node=BoundX2(xbound);
%     plot([maxx+fiberRadius fiber(node).center(1)],[fiber(node).center(2) fiber(node).center(2)],'g*-','LineWidth',3);
% end
% %% Plot Top-Bottom BC
% axis equal
% for xbound=1:size(BoundY1,2)
%     node=BoundY1(xbound);
%     plot([fiber(node).center(1) fiber(node).center(1)],[miny-fiberRadius fiber(node).center(2)],'r*-','LineWidth',3);
% %     plot([minx-fiberRadius fiber(node).center(1)],[fiber(node).center(2) fiber(node).center(2)],'r*-','LineWidth',3);
% end
% for xbound=1:size(BoundY2,2)
%     node=BoundY2(xbound);
%     plot([fiber(node).center(1) fiber(node).center(1)],[maxy+fiberRadius fiber(node).center(2)],'g*-','LineWidth',3);
% %     plot([maxx+fiberRadius fiber(node).center(1)],[fiber(node).center(2) fiber(node).center(2)],'g*-','LineWidth',3);
% end
%
fiber(1).contactNeighbor=[];
fiber(1).Contacts=[];
fiber(1).pts=[];
N=size(fiber,2);
%ContactLen=beta*a;
% NumSections=floor(fiberLen/ContactLen);
%%
% calculate a using average distance
distances=[];
for i=1:N
    NumNeighbor=size(fiber(i).nodes,2);
    nbdistance=[];
    for j=1:NumNeighbor    %contact pts with each neighbor
        NeighborNode=fiber(i).nodes(j);
        %% neighbor distance
        fiber_d=sqrt((fiber(i).center(1)-fiber(NeighborNode).center(1))^2+(fiber(i).center(2)-fiber(NeighborNode).center(2))^2)-fiber(i).radius-fiber(NeighborNode).radius;
        nbdistance=[nbdistance fiber_d];
    end
    fiber(i).nodes_dist=nbdistance;
    ave_nbdistance=mean(nbdistance);
    fiber(i).ave_dist=ave_nbdistance;
    distances=[distances fiber(i).nodes_dist];
end
%max_a=max(distances);
%fiberLen=ContactsPerFiber*beta*max_a;
L=fiberLen;
%%
%L=fiberLen; % fiber length in m
for i=1:N
    NumNeighbor=size(fiber(i).nodes,2);
    allcontact=[];
    for j=1:NumNeighbor    %contact pts with each neighbor
        contact=[];
        NeighborNode=fiber(i).nodes(j);
        % NeighborNode=fiber(i).nodes(j);
        % contact=[];
        %a=fiber(i).nodes_dist(j);
        % a=sqrt((fiber(i).center(1)-fiber(NeighborNode).center(1))^2+(fiber(i).center(2)-fiber(NeighborNode).center(2))^2)-fiber(i).radius-fiber(NeighborNode).radius;
        %NeighborNode=fiber(i).nodes(j);
        if NeighborNode>i
            a=0.5*(fiber(i).ave_dist+fiber(NeighborNode).ave_dist);
            ContactLen=beta*a;
            startpt=rand*ContactLen;
            endpt=startpt;
            while endpt<=L
                contact(end+1)=endpt;
                endpt=endpt+ContactLen;
            end
%             NumContacts=floor(L/ContactLen);
%             previous=rand*ContactLen;
%             contact(1)=previous;
%             if NumContacts>=2
%                 for m=2:NumContacts
%                     contact(m)=previous+ContactLen; %contact(m)=previous+ContactLen*normrnd(0,0.01);
%                     previous=contact(m);
%                 end
%             end
            sizeb=size(contact,2);
            NumContacts=sizeb;
            allcontact=[allcontact,contact];  % all contact points on fiber i
            fiber(i).contactNeighbor(end+1:end+sizeb)=NeighborNode;  %
            fiber(NeighborNode).Contacts(end+1:end+sizeb)=contact;
            fiber(NeighborNode).contactNeighbor(end+1:end+sizeb)=i;
        end
    end
    allcontact=[fiber(i).Contacts,allcontact];  % all contact pts including those inherited from previous fibers (NeighborNode<i)
    allcontact1=unique(allcontact);
    fiber(i).Contacts=allcontact1;
    if size(allcontact1,1)~=0
        for m=1:size(allcontact1,2)   % find contact neighbors for each contact point.
            loc=find(allcontact==allcontact1(m));
            fiber(i).pts{m}=fiber(i).contactNeighbor(loc);
        end
    end
end    %all fibers built
%             end
%             if curr_node==N+1
%                  plot([fiber(i).center(1) max_x],[fiber(i).center(2) fiber(i).center(2)],'r*-','LineWidth',3);
%
%             end
% fiber.BoundX1=BoundX1;
% fiber.BoundX2=BoundX2;
% fiber.BoundY1=BoundY1;
% fiber.BoundY2=BoundY2;
% finish finding BC nodes
%%% consider fiber breakage
if NumBreak~=0
for i=1:N
    iNumBreak=randi(NumBreak,1);
    ContactVec=fiber(i).Contacts;
    BreakPts=min(ContactVec)+(max(ContactVec)-min(ContactVec))*rand(iNumBreak,1);
    BreakPts=unique(BreakPts);
    locBP=zeros(iNumBreak,1);
    for NumBP=1:iNumBreak
        locBP(NumBP,1)=find(ContactVec>BreakPts(NumBP),1);
    end
    fiber(i).Breakage=locBP;
end
end
%%
R=cell(N,N);
for i=1:N
    for j=1:N
        NumRows=size(fiber(i).Contacts,2);
        NumColumns=size(fiber(j).Contacts,2);
        R{i,j}=zeros(NumRows,NumColumns);
    end
end
G=R;       % GV=K
% finish initializing
%%% build fibers resistors and contact resistors
for i=1:N
    NumContacts=size(fiber(i).Contacts,2); % note Contacts is a row vector
    ContactVec=fiber(i).Contacts;
    % R matrix
    % R for fiber sections
    for j=1:NumContacts-1
         RLen=fiber(i).Contacts(j+1)-fiber(i).Contacts(j);
            A=pi*fiber(i).radius^2;
            R{i,i}(j,j+1)=rf*RLen/A;
            R{i,i}(j+1,j)=rf*RLen/A;    % resistance between two sections on one fiber
            G{i,i}(j,j+1)=-1/R{i,i}(j,j+1);% G(i,j)=-1/R
            G{i,i}(j+1,j)=-1/R{i,i}(j+1,j);% G(i,j)=-1/R
    end
     %%%% change R into a large value where fiber breakage happens.
     if NumBreak
     for NumBP=1:size(fiber(i).Breakage,1)
         BreakLoc=fiber(i).Breakage(NumBP);
         R{i,i}(BreakLoc-1,BreakLoc)=RBreakage;
         R{i,i}(BreakLoc,BreakLoc-1)=RBreakage;
         G{i,i}(BreakLoc-1,BreakLoc)=-1/RBreakage;% G(i,j)=-1/R
         G{i,i}(BreakLoc,BreakLoc-1)=-1/RBreakage;% G(i,j)=-1/R
     end
     end
    % R for contacts
    for j=1:NumContacts
                  num_pt=size(fiber(i).pts{j},2);
            for k=1:num_pt
                neighbor_pt=fiber(i).pts{j}(k);
                ind=find(fiber(neighbor_pt).Contacts==ContactVec(j));
                R{i,neighbor_pt}(j,ind)=Rc; %Contact Resistance between fibers
                G{i,neighbor_pt}(j,ind)=-1/Rc;
            end
            fiberi=R{i,i}(j,:);
            fiberi=fiberi(fiberi~=0);
            sum=0;
            for m=1:size(fiberi,2)
                sum=sum+1/fiberi(m);
            end
            Gfiberi=sum;
            sum1=0;
            for n=1:num_pt
                neighbor_pt=fiber(i).pts{j}(n);
                ind=find(fiber(neighbor_pt).Contacts==ContactVec(j));
                sum1=sum1+1/R{i,neighbor_pt}(j,ind);
            end
            Gfiberj=sum1;
            G{i,i}(j,j)=Gfiberi+Gfiberj;
    end
end
%%%% change R into a large value where fiber breakage happens.
% change R into a matrix to apply Kirchoff's Law.
%% Apply longitudinal BC
% BC1=5;
% BC2=0;
% for i=1:N
%     K{i,1}=zeros(size(fiber(i).Contacts,2),1);
% end
% for i=1:N %size(BoundZ1,2)
%     Ki=zeros(size(fiber(i).Contacts,2),1);
%     Ki(1)=BC1;
%     Ki(end)=BC2; %% boundary condition
%     K{i,1}=Ki;
% end
% for i=1:N
%     %Ncontacts=size(fiber(i).Contacts,2);
%     for j=1:N
%         G{i,j}(1,:)=0;
%         G{i,j}(end,:)=0;
%     end
% end
% for i=1:N
%     G{i,i}(1,1)=1;
%     G{i,i}(end,end)=1;
% end
%% Apply through-thickness BC
rous=[];
K=cell(N,1);
BC1=5;
BC2=0;
for i=1:N
    K{i,1}=zeros(size(fiber(i).Contacts,2),1);
end
% K=zeros(size(R,1),1)
%% Apply V from top to bottom
for i=1:size(BoundY1,2)
    K{BoundY1(i),1}=BC1*ones(size(fiber(BoundY1(i)).Contacts,2),1);%% boundary condition
    fiberlabel=BoundY1(i);
    for j=1:N
        if j==fiberlabel
            G{fiberlabel,j}=eye(size(fiber(fiberlabel).Contacts,2));
        else
            G{fiberlabel,j}=zeros(size(fiber(fiberlabel).Contacts,2),size(fiber(j).Contacts,2));
        end
    end
    %     for j=1:size(fiber(BoundX1(i)).Contacts,1)
    %     G{fiberlabel,fiberlabel}(j,j)=1;
    %     end
end
for i=1:size(BoundY2,2)
    K{BoundY2(i),1}=BC2*ones(size(fiber(BoundY2(i)).Contacts,2),1);
    fiberlabel=BoundY2(i);
    for j=1:N
        if j==fiberlabel
            G{fiberlabel,j}=eye(size(fiber(fiberlabel).Contacts,2));
        else
            G{fiberlabel,j}=zeros(size(fiber(fiberlabel).Contacts,2),size(fiber(j).Contacts,2));
        end
    end
    %     for j=1:size(fiber(BoundX2(i)).Contacts,1)
    %     G{fiberlabel,fiberlabel}(j,j)=1;
    %     end
end
%% Apply V from left to right
% for i=1:size(BoundX1,2)
%     K{BoundX1(i),1}=BC1*ones(size(fiber(BoundX1(i)).Contacts,2),1);%% boundary condition
%     fiberlabel=BoundX1(i);
%     for j=1:N
%         if j==fiberlabel
%             G{fiberlabel,j}=eye(size(fiber(fiberlabel).Contacts,2));
%         else
%             G{fiberlabel,j}=zeros(size(fiber(fiberlabel).Contacts,2),size(fiber(j).Contacts,2));
%         end
%     end
%     %     for j=1:size(fiber(BoundX1(i)).Contacts,1)
%     %     G{fiberlabel,fiberlabel}(j,j)=1;
%     %     end
% end
% for i=1:size(BoundX2,2)
%     K{BoundX2(i),1}=BC2*ones(size(fiber(BoundX2(i)).Contacts,2),1);
%     fiberlabel=BoundX2(i);
%     for j=1:N
%         if j==fiberlabel
%             G{fiberlabel,j}=eye(size(fiber(fiberlabel).Contacts,2));
%         else
%             G{fiberlabel,j}=zeros(size(fiber(fiberlabel).Contacts,2),size(fiber(j).Contacts,2));
%         end
%     end
%     %     for j=1:size(fiber(BoundX2(i)).Contacts,1)
%     %     G{fiberlabel,fiberlabel}(j,j)=1;
%     %     end
% end
%% Solve GV=K
K=cell2mat(K);
%R=cell2mat(R);
G=cell2mat(G);
Voltage2=G\K;
Mrow=zeros(N,1);
for i=1:N
    Mrow(i)=size(fiber(i).Contacts,2);
end
Voltage3=mat2cell(Voltage2,Mrow);
%% calculate longitudinal currents
% totcur1=0;
% totcur2=0;
% cur1=[];
% cur2=[];
% for i=1:N
%     Res1=R{i,i}(1,2);
%     Vdiff1=BC1-Voltage3{i}(2);
%     cur1(end+1)=Vdiff1/Res1;
%     % injecting current
%     Res2=R{i,i}(end-1,end);
%     Vdiff2=Voltage3{i}(end)-BC2;
%     cur2(end+1)=Vdiff2/Res2;
%     % outgoing current
%     totcur1=totcur1+cur1(end);
%     totcur2=totcur2+cur2(end);
% end
% Res=(BC1-BC2)/totcur1;
% rho=xlen*Res*ylen/fiberLen;
%% calculate inplane transverse (Y) currents
% 1. incoming currents
totcur1=0;
totcur2=0;
cur1=[];
cur2=[];
for i=1:size(BoundY1,2)
    fiberlabel=BoundY1(i);
    num_pt=size(fiber(fiberlabel).Contacts,2);
    for j=1:num_pt
        %Vdiff=BC1-Voltage3{j}
        num_contact=size(fiber(fiberlabel).pts{j},2);
        for k=1:num_contact
            neighbor_fiber=fiber(fiberlabel).pts{j}(k);
            neighbor_pt=find(fiber(neighbor_fiber).Contacts==fiber(fiberlabel).Contacts(j));
            Vdiff=BC1-Voltage3{neighbor_fiber}(neighbor_pt);
            Res=R{fiberlabel,neighbor_fiber}(j,neighbor_pt);
            cur1(end+1)=Vdiff/Res;
            totcur1=totcur1+cur1(end);
        end
    end
end
% 2. outgoing current
for i=1:size(BoundY2,2)
    fiberlabel=BoundY2(i);
    num_pt=size(fiber(fiberlabel).Contacts,2);
    for j=1:num_pt
        %Vdiff=BC1-Voltage3{j}
        num_contact=size(fiber(fiberlabel).pts{j},2);
        for k=1:num_contact
            neighbor_fiber=fiber(fiberlabel).pts{j}(k);
            neighbor_pt=find(fiber(neighbor_fiber).Contacts==fiber(fiberlabel).Contacts(j));
            Vdiff=Voltage3{neighbor_fiber}(neighbor_pt)-BC2;
            Res=R{fiberlabel,neighbor_fiber}(j,neighbor_pt);
            cur2(end+1)=Vdiff/Res;
            totcur2=totcur2+cur2(end);
        end
    end
end
totcur1;
totcur2;
Res=(BC1-BC2)/totcur1;
rho=fiberLen*Res*xlen/ylen;
%% calculate through-thickness (Z) currents
% % 1. outgoing currents
% totcur1=0;
% totcur2=0;
% cur1=[];
% cur2=[];
% for i=1:size(BoundX1,2)
%     fiberlabel=BoundX1(i);
%     num_pt=size(fiber(fiberlabel).Contacts,2);
%     for j=1:num_pt
%         %Vdiff=BC1-Voltage3{j}
%         num_contact=size(fiber(fiberlabel).pts{j},2);
%         for k=1:num_contact
%             neighbor_fiber=fiber(fiberlabel).pts{j}(k);
%             neighbor_pt=find(fiber(neighbor_fiber).Contacts==fiber(fiberlabel).Contacts(j));
%             Vdiff=BC1-Voltage3{neighbor_fiber}(neighbor_pt);
%             Res=R{fiberlabel,neighbor_fiber}(j,neighbor_pt);
%             cur1(end+1)=Vdiff/Res;
%             totcur1=totcur1+cur1(end);
%         end
%     end
% end
% for i=1:size(BoundX2,2)
%     fiberlabel=BoundX2(i);
%     num_pt=size(fiber(fiberlabel).Contacts,2);
%     for j=1:num_pt
%         %Vdiff=BC1-Voltage3{j}
%         num_contact=size(fiber(fiberlabel).pts{j},2);
%         for k=1:num_contact
%             neighbor_fiber=fiber(fiberlabel).pts{j}(k);
%             neighbor_pt=find(fiber(neighbor_fiber).Contacts==fiber(fiberlabel).Contacts(j));
%             Vdiff=Voltage3{neighbor_fiber}(neighbor_pt)-BC2;
%             Res=R{fiberlabel,neighbor_fiber}(j,neighbor_pt);
%             cur2(end+1)=Vdiff/Res;
%             totcur2=totcur2+cur2(end);
%         end
%     end
% end
% totcur1;
% totcur2;
% Res=5/totcur1;
% rho=fiberLen*Res*ylen/xlen;
% % save ResData