Description of Func_RhoZ_LTspice
Home > v08 > helper > Func_RhoZ_LTspice.m
Func_RhoZ_LTspice
PURPOSE
% example usage: copy the code inside " if 1==0 ... end" and run.
SYNOPSIS
function rho = Func_RhoZ_LTspice(NetList,fibermat,fiberLen,beta,fiberRadius,NumBreak,Rc,rf,RBreakage)
DESCRIPTION
% example usage: copy the code inside " if 1==0  ... end" and run.
CROSS-REFERENCE INFORMATION
This function calls:
Func_RhoZ_LTspice % example usage: copy the code inside " if 1==0 ... end" and run.
ReadRAW function [LineContent,NVariables, NValues] = ReadRAW(filepath)
Func_RhoZ_LTspice % example usage: copy the code inside " if 1==0 ... end" and run.
ReadRAW function [LineContent,NVariables, NValues] = ReadRAW(filepath)
createnode UNTITLED2 Summary of this function goes here
This function is called by:
Func_RhoZ_LTspice % example usage: copy the code inside " if 1==0 ... end" and run.
Function
Func_RhoZ_LTspice % example usage: copy the code inside " if 1==0 ... end" and run.
RNetworkGUI1 RNETWORKGUI1 MATLAB code for RNetworkGUI1.fig
SOURCE CODE
function rho = Func_RhoZ_LTspice(NetList,fibermat,fiberLen,beta,fiberRadius,NumBreak,Rc,rf,RBreakage)
%% example usage: copy the code inside " if 1==0  ... end" and run.
if 1==0
    clear all
    NetList='testFunc_RhoZ_LTspice3';
    fiberLen=1e-3;
    beta=350;
    fiberRadius=7e-6;
    NumBreak=0;
    Rc=10;
    rf=1.5e-5;
    RBreakage=10000;
    fibermat='vf_0.6_spec2.mat';
    rho =Func_RhoZ_LTspice(NetList,fibermat,fiberLen,beta,fiberRadius,NumBreak,Rc,rf,RBreakage)
end
%% write Model head
%NetList='testMatlab2LTspice8';
NetListID= [NetList,'.cir'];
fid=fopen(NetListID,'wt'); % wt means overwrite existing file named with NetListID
% To open a file in text mode, append 't' to the permission string,
fprintf(fid,'%s  \n','Resistor Network for Cross-Ply CFRP');
fclose(fid);
NetListMatrix = [];
%fiberLen=1e-3;
%beta=350;
%fiberRadius=7e-6;
%NumBreak=0;
%Rc=10;
%rf=1.5e-5;
%RBreakage=10000;
NumContacts=0;
%load('vf_0.6_spec2.mat'); % changed from fibermat to 'vf_0.6_spec2.mat'
<<<<<<< HEAD
load (fibermat);
=======
load(fibermat);
%fiber=fibermat;
>>>>>>> 558d32ba490f1fcd4af42dcc54ca0581b61ef031
% Note: after load(fibermat), fiber.x fiber.y fiber.z are all row vectors.
% Code below change row vectors into column vectors.
fiber.x=fiber.x';
fiber.y=fiber.y';
fiber.radius=fiber.radius';
% Now fiber.x fiber.y and fiber.radius are column vectors.
N=size(fiber.radius,1);%
% !!! be careful, depending on the fiber.radius being a row vector or
% column vector, this command can be size(...,2) for row vector
%or size(...,1) for column vectors.
fiber1= struct('center',[], 'radius',[], 'nodes', []);
aveRad=mean(fiber.radius);
scale=aveRad/fiberRadius;
fiber.x=fiber.x/scale;
fiber.y=fiber.y/scale;
fiber.radius=fiber.radius/scale;
%% get VF and a
minx=min(fiber.x)-fiberRadius;
miny=min(fiber.y)-fiberRadius;
maxx=max(fiber.x)+fiberRadius;
maxy=max(fiber.y)+fiberRadius;
xlen=maxx-minx;
ylen=maxy-miny;
% xlen=maxx-minx-2*fiberRadius;
% ylen=maxy-miny-2*fiberRadius;
Rsquare=fiber.radius'*fiber.radius;
VF=pi*Rsquare/(xlen*ylen);
%a=fiberRadius*(sqrt(pi/(VF))-2); % square packing
% a=fiberRadius*(sqrt(2*pi/(sqrt(3)*VF))-2); % hex packing
%% plot
% clf
% hold on
% viscircles([fiber.x fiber.y],fiber.radius,'LineWidth',2);
% axis([minx maxx miny maxy]);
%% restruct data
for i=1:N
    fiber1(i).center(1)=fiber.x(i);
    fiber1(i).center(2)=fiber.y(i);
    fiber1(i).radius=fiber.radius(i);
end
fiber=fiber1;
%% find fiber neigbbors
perc=1.8*fiberRadius;
for i=1:N
    fiber(i).nodes=createnode(fiber,i,perc,N);
end
% finish creating neighbors
% find floating fibers that are not connected to any fibers
nullnodes=[];
for i=1:N
    if size(fiber(i).nodes,2)==0
        nullnodes(end+1)=i;
    end
end
while ~isempty(nullnodes)
    fiber(nullnodes(1))=[];
    N1=size(fiber,2);
    for i=1:N1
        fiber(i).nodes=createnode(fiber,i,perc,N1);
    end
    nullnodes=[];
    for i=1:N1
        if size(fiber(i).nodes,2)==0
            nullnodes(end+1)=i;
        end
    end
end
%% Boundary
BoundX1=[];
BoundX2=[];
BoundY1=[];
BoundY2=[];
BoundZ1=[];
BoundZ2=[];
N=size(fiber,2);
% BoundZ1=[1:N];
% BoundZ2=[1:N];
for i=1:N
    if (fiber(i).center(1)<=minx+2*fiber(i).radius)
        %     if (fiber(i).center(1)<=1.0*(2*a+fiber(i).radius))
        %fiber1(i).nodes=[fiber1(i).nodes 0]; %left boundary
        BoundX1(end+1)=i;
    end
    if (fiber(i).center(1)>=maxx-2*fiber(i).radius)
        %fiber1(i).nodes=[fiber1(i).nodes N+1]; % right boundary
        BoundX2(end+1)=i;
    end
    if (fiber(i).center(2)<=miny+2*fiber(i).radius)
        %fiber1(i).nodes=[fiber1(i).nodes 0]; %left boundary
        BoundY1(end+1)=i;
    end
    if (fiber(i).center(2)>=maxy-2*fiber(i).radius)
        %fiber1(i).nodes=[fiber1(i).nodes N+1]; % right boundary
        BoundY2(end+1)=i;
    end
end
%% Plot Left-Right BC
% for xbound=1:size(BoundX1,2)
%     node=BoundX1(xbound);
%     plot([minx-fiberRadius fiber(node).center(1)],[fiber(node).center(2) fiber(node).center(2)],'r*-','LineWidth',3);
% end
% for xbound=1:size(BoundX2,2)
%     node=BoundX2(xbound);
%     plot([maxx+fiberRadius fiber(node).center(1)],[fiber(node).center(2) fiber(node).center(2)],'g*-','LineWidth',3);
% end
% %% Plot Top-Bottom BC
% axis equal
% for xbound=1:size(BoundY1,2)
%     node=BoundY1(xbound);
%     plot([fiber(node).center(1) fiber(node).center(1)],[miny-fiberRadius fiber(node).center(2)],'r*-','LineWidth',3);
% %     plot([minx-fiberRadius fiber(node).center(1)],[fiber(node).center(2) fiber(node).center(2)],'r*-','LineWidth',3);
% end
% for xbound=1:size(BoundY2,2)
%     node=BoundY2(xbound);
%     plot([fiber(node).center(1) fiber(node).center(1)],[maxy+fiberRadius fiber(node).center(2)],'g*-','LineWidth',3);
% %     plot([maxx+fiberRadius fiber(node).center(1)],[fiber(node).center(2) fiber(node).center(2)],'g*-','LineWidth',3);
% end
%
fiber(1).contactNeighbor=[];
fiber(1).Contacts=[];
fiber(1).pts=[];
N=size(fiber,2);
%ContactLen=beta*a;
% NumSections=floor(fiberLen/ContactLen);
%%
% calculate a using average distance
distances=[];
for i=1:N
    NumNeighbor=size(fiber(i).nodes,2);
    nbdistance=[];
    for j=1:NumNeighbor    %contact pts with each neighbor
        NeighborNode=fiber(i).nodes(j);
        %% neighbor distance
        fiber_d=sqrt((fiber(i).center(1)-fiber(NeighborNode).center(1))^2+(fiber(i).center(2)-fiber(NeighborNode).center(2))^2)-fiber(i).radius-fiber(NeighborNode).radius;
        nbdistance=[nbdistance fiber_d];
    end
    fiber(i).nodes_dist=nbdistance;
    ave_nbdistance=mean(nbdistance);
    fiber(i).ave_dist=ave_nbdistance;
    distances=[distances fiber(i).nodes_dist];
end
%max_a=max(distances);
%fiberLen=ContactsPerFiber*beta*max_a;
L=fiberLen;
%%
%L=fiberLen; % fiber length in m
for i=1:N
    NumNeighbor=size(fiber(i).nodes,2);
    allcontact=[];
    for j=1:NumNeighbor    %contact pts with each neighbor
        contact=[];
        NeighborNode=fiber(i).nodes(j);
        % NeighborNode=fiber(i).nodes(j);
        % contact=[];
        %a=fiber(i).nodes_dist(j);
        % a=sqrt((fiber(i).center(1)-fiber(NeighborNode).center(1))^2+(fiber(i).center(2)-fiber(NeighborNode).center(2))^2)-fiber(i).radius-fiber(NeighborNode).radius;
        %NeighborNode=fiber(i).nodes(j);
        if NeighborNode>i
            a=0.5*(fiber(i).ave_dist+fiber(NeighborNode).ave_dist);
            ContactLen=beta*a;
            startpt=rand*ContactLen;
            endpt=startpt;
            while endpt<=L
                contact(end+1)=endpt;
                endpt=endpt+ContactLen;
            end
            %             NumContacts=floor(L/ContactLen);
            %             previous=rand*ContactLen;
            %             contact(1)=previous;
            %             if NumContacts>=2
            %                 for m=2:NumContacts
            %                     contact(m)=previous+ContactLen; %contact(m)=previous+ContactLen*normrnd(0,0.01);
            %                     previous=contact(m);
            %                 end
            %             end
            sizeb=size(contact,2);
            NumContacts=sizeb;
            allcontact=[allcontact,contact];  % all contact points on fiber i
            fiber(i).contactNeighbor(end+1:end+sizeb)=NeighborNode;  %
            fiber(NeighborNode).Contacts(end+1:end+sizeb)=contact;
            fiber(NeighborNode).contactNeighbor(end+1:end+sizeb)=i;
        end
    end
    allcontact=[fiber(i).Contacts,allcontact];  % all contact pts including those inherited from previous fibers (NeighborNode<i)
    allcontact1=unique(allcontact);
    fiber(i).Contacts=allcontact1;
    if size(allcontact1,1)~=0
        for m=1:size(allcontact1,2)   % find contact neighbors for each contact point.
            loc=find(allcontact==allcontact1(m));
            fiber(i).pts{m}=fiber(i).contactNeighbor(loc);
        end
    end
end
%all fibers built
%% consider fiber breakage
if NumBreak~=0
    for i=1:N
        iNumBreak=randi(NumBreak,1);
        ContactVec=fiber(i).Contacts;
        BreakPts=min(ContactVec)+(max(ContactVec)-min(ContactVec))*rand(iNumBreak,1);
        BreakPts=unique(BreakPts);
        locBP=zeros(iNumBreak,1);
        for NumBP=1:iNumBreak
            locBP(NumBP,1)=find(ContactVec>BreakPts(NumBP),1);
        end
        fiber(i).Breakage=locBP;
    end
end
%%
R=cell(N,N);
for i=1:N
    for j=1:N
        NumRows=size(fiber(i).Contacts,2);
        NumColumns=size(fiber(j).Contacts,2);
        R{i,j}=zeros(NumRows,NumColumns);
    end
end
G=R;       % GV=K
% finish initializing
%%% build fibers resistors and contact resistors
fid=fopen(NetListID,'a');
% ground
for i=1:size(BoundY2,2)
    fibernum=BoundY2(i);
    for j=1:size(fiber( fibernum).Contacts,2)
        Rvalue=0.000001;
        RID=['Rg_F' num2str(fibernum) 'C' num2str(j)];
        Node1=['F' num2str(fibernum) 'C' num2str(j)];
        Node2=[num2str(0)];
        fprintf(fid,'%s %s %s %f \n',RID,Node1,Node2,Rvalue);
    end
end
% electrode
for i=1:size(BoundY1,2)
        fibernum=BoundY1(i);
    for j=1:size(fiber( fibernum).Contacts,2)
        %fibernum=BoundY2(i);
        Rvalue=0.000001;
        RID=['Re_F' num2str(fibernum) 'C' num2str(j)];
        Node1=['Electrode'];
        Node2=['F' num2str(fibernum) 'C' num2str(j)];
        fprintf(fid,'%s %s %s %f \n',RID,Node1,Node2,Rvalue);
    end
end
% fiber resistors
for i=1:N
    NumContacts=size(fiber(i).Contacts,2); % note Contacts is a row vector
    ContactVec=fiber(i).Contacts;
    % R matrix
    % R for fiber sections
    for j=1:NumContacts-1
        RLen=fiber(i).Contacts(j+1)-fiber(i).Contacts(j);
        A=pi*fiber(i).radius^2;
        Rvalue=rf*RLen/A;
        RID=['R_F' num2str(i) 'C' num2str(j)];
        Node1=['F' num2str(i) 'C' num2str(j)];
        Node2=['F' num2str(i) 'C' num2str(j+1)];
        fprintf(fid,'%s %s %s %f \n',RID,Node1,Node2,Rvalue);
    end
    % contact resistors
    for j=1:NumContacts
        num_pt=size(fiber(i).pts{j},2);
        for k=1:num_pt
            neighbor_pt=fiber(i).pts{j}(k);
            if neighbor_pt<i
            ind=find(fiber(neighbor_pt).Contacts==ContactVec(j));
            Rvalue=Rc;
            RID=['Rc_F' num2str(i) 'C' num2str(j)];
            Node1=['F' num2str(i) 'C' num2str(j)];
            Node2=['F' num2str(neighbor_pt) 'C' num2str(ind)];
            fprintf(fid,'%s %s %s %f \n',RID,Node1,Node2,Rvalue);
            end
        end
    end
end
%% write analysis command
%fid=fopen(NetListID,'a');
fprintf(fid,'%s \n','Vin Electrode 0 1');
fprintf(fid,'%s \n','.OP');
% fprintf(fid,'%s \n','.DC Vinput 1 1 1');
fprintf(fid,'%s \n','.PRINT I(Vin)');
fprintf(fid,'%s \n','.END');
ST = fclose(fid);
rho=1;
if 1==1
%% run LTspice and get results
SystemCMD = ['scad3.exe',' -b -ascii ',NetListID];
p=system(SystemCMD);
%waitfor(p);
filepath = [NetList,'.raw'];
[Iin,Is,data1]=ReadRAW(filepath);
Res=1/abs(Iin)
rho=Res*fiberLen*xlen/ylen
<<<<<<< HEAD
end
=======
end
>>>>>>> 558d32ba490f1fcd4af42dcc54ca0581b61ef031