Description of GenerateFiber2D
Home > v08 > helper > GenerateFiber2D.m
GenerateFiber2D
PURPOSE
% Example usage:
SYNOPSIS
function fiber2D = GenerateFiber2D(Spec_Wid,Spec_Th,VF,fiberRadius,PackOrder)
DESCRIPTION
% Example usage:
CROSS-REFERENCE INFORMATION
This function calls:
GenerateFiber2D % Example usage:
GenerateFiber2D % Example usage:
HexPacking % square packing
RandomPacking
SquarePacking % square packing
This function is called by:
Function
GenerateFiber2D % Example usage:
GenerateFiber2D % Example usage:
SUBFUNCTIONS
function fiber2D = SquarePacking(Spec_Wid,Spec_Th,VF,fiberRadius);
function fiber2D=HexPacking(Spec_Wid,Spec_Th,VF,fiberRadius);
function RandomPacking
SOURCE CODE
function fiber2D = GenerateFiber2D(Spec_Wid,Spec_Th,VF,fiberRadius,PackOrder)
%% Example usage:
if 0
    Spec_Wid=1e-4
    Spec_Th=1e-4
    VF=0.5
    fiberRadius=3.5e-6
    PackOrder = 'Square'
    fiber2D = GenerateFiber2D(Spec_Wid,Spec_Th,VF,fiberRadius,PackOrder)
end
%% Beginning of code
switch PackOrder
    case 'Hexagon'
        fiber2D=HexPacking(Spec_Wid,Spec_Th,VF,fiberRadius);
    case 'Square'
         fiber2D=SquarePacking(Spec_Wid,Spec_Th,VF,fiberRadius);
    case 'Random'
         fiber2D=RandomPacking(Spec_Wid,Spec_Th,VF,fiberRadius);
    otherwise
       warning('please choose one of the four packing orders: Hexagon, Square, Random')
end
function fiber2D = SquarePacking(Spec_Wid,Spec_Th,VF,fiberRadius);
%% square packing
nRow=round(Spec_Th/fiberRadius*sqrt(VF/pi));
nColumn=round(nRow*Spec_Wid/Spec_Th);
a=fiberRadius*(sqrt(pi/(VF))-2); % square packingfiber= struct('x',[], 'y',[], 'radius', []);
for i=1:nRow
    for j=1:nColumn
        fnum=(i-1)*nColumn+j;
        fiber.x(1,fnum)=(j-1)*(2*fiberRadius+a);
        fiber.y(1,fnum)=(i-1)*(2*fiberRadius+a); % square packing
        %fiber.radius(1,fnum)=fiberRadius;
    end
end
fiber.radius=fiberRadius*ones(1,nRow*nColumn);
fiber2D=fiber;
save fiber2D
%PerfectFiber=fiber;
%save PerfectFiber
function fiber2D=HexPacking(Spec_Wid,Spec_Th,VF,fiberRadius);
B=((nColumn-1)*sqrt(3)/2+nRow-1)*2*fiberRadius;
A=(nRow-1)*(nColumn-1)*sqrt(3)/2;
C=4*fiberRadius^2-(nRow*nColumn*pi*fiberRadius^2)/VF;
a=-2*fiberRadius+(-B+sqrt(B^2-4*A*C))/(2*A);  %hex packing
for i=1:nRow
    for j=1:nColumn
        fnum=(i-1)*nColumn+j;
        fiber.x(1,fnum)=sqrt(3)*(j-1)*(fiberRadius+a/2);
        fiber.y(1,fnum)=(1-mod(j,2))*(fiberRadius+a/2)+(i-1)*2*(fiberRadius+a/2); %hex packing
        fiber.radius(1,fnum)=fiberRadius;
    end
end
function RandomPacking
  fiber2D = SquarePacking(Spec_Wid,Spec_Th,VF,fiberRadius);