Description of Interface_layer_simulation
Home > v08 > helper > Interface_layer_simulation.m
Interface_layer_simulation
PURPOSE
% 3D Resistor Network Modle by Hong Yu
SYNOPSIS
This is a script file.
DESCRIPTION
% 3D Resistor Network Modle by Hong Yu
% copyright: Hong Yu,hongy@udel.edu 2013
CROSS-REFERENCE INFORMATION
This function calls:
ContactForce % Force at each contact point.
ContactR % contact resistance
ContactForce % Force at each contact point.
ContactR % contact resistance
Func_RNetwork_Z % this function is used when the input fibermat is from generated fiber data (not from SEM).
Interface_layer fiberRadius=3.5e-6
This function is called by:
SOURCE CODE
%% 3D Resistor Network Modle by Hong Yu
%% copyright: Hong Yu,hongy@udel.edu 2013
for iter=1:1
clear all
clf
%% input parameters
Resfid1='InterfaceLayer.txt' % Results file name
% Resfid2='Test_ave.txt'
% fid=fopen(Resfid2,'a');
%         fprintf(fid,'%s\n','T700SC')
fiberRadius=3.405e-6; % radius of fiber, 2.6um for IM7; 3.5 for AS4
fiberLen=5e-3;
beta=500;
NumBreak=0;
%Rc=1; % contact resistance
rf=2.35e-5; % fiber resistivity
fiberRadius=3.5e-6;
RBreakage=1e10;
Pressure=1e6;
E=230*1e9;
%% parameters for interface layer
VF=0.5;
connectivity=0.6;
% N_connect=round(connectivity*fcolumn);
frow=2;
fcolumn=30;
%% Get fiber arrangement for interface layer
Interface_layer(fiberRadius,VF,connectivity,frow,fcolumn);
Fc = ContactForce(VF,beta,Pressure,fiberRadius);
Rc = ContactR(fiberRadius,Fc,E,rf);
%% calculate rho
fibermat='fiber.mat'
[rho,fiber,VF,NumContacts]=Func_RNetwork_Z(fibermat,fiberLen,beta,fiberRadius,NumBreak,Rc,rf,RBreakage);
fid=fopen(Resfid1,'a');
fprintf(fid,...
    '%1.4f %f %f %f %f %2.10f %d %f \n',...
    VF,rho,connectivity,Rc,fiberLen,fiberRadius,NumContacts,beta);
end