Description of kirchoff
Home > v08 > helper > kirchoff.m
kirchoff
PURPOSE
Script to solve a complicated KVL network
SYNOPSIS
This is a script file.
DESCRIPTION
Script to solve a complicated KVL network
CROSS-REFERENCE INFORMATION
This function calls:
createnode UNTITLED2 Summary of this function goes here
dangling UNTITLED2 Summary of this function goes here
deletenode UNTITLED Summary of this function goes here
removezeros UNTITLED3 Summary of this function goes here
test % Statistical representation: beta
traverse UNTITLED3 Summary of this function goes here
This function is called by:
SOURCE CODE
%Script to solve a complicated KVL network
clear all
vfmatrix=[0.55]; %volume fractions
tempsimsize=size(vfmatrix);
simsize=tempsimsize(2);
final_result=zeros(10*simsize,2); %first column is vf second column is resistance
average_result=zeros(simsize,3);
runcount=0;
for simnumber=1:simsize
for specimen=1:1
vf=vfmatrix(simnumber);
filen=strcat('vf_',num2str(vf),'_spec',num2str(specimen),'.mat');
load(filen);
viscircles([fiber.x' fiber.y'],fiber.radius);
axis([0 20 0 20]);
Np=size(fiber.x);
N=Np(2);
perc=0.7*fiber.radius(1); %percolation distance PARAMETER
V_left=1; %left Voltage PARAMETER
V_right=0;  %right voltage PARAMETER
max_x=20; %Left boundary coordinates
fiber1(N) = struct('center',[], 'radius',[], 'nodes', []);
xmat=fiber.x;
ymat=fiber.y;
rmat=fiber.radius;
for i=1:N
    fiber1(i).center(1)=xmat(i);
    fiber1(i).center(2)=ymat(i);
    fiber1(i).radius=rmat(i);
end
for i=1:N
    fiber1(i).nodes=createnode(fiber1,i,perc,N);
end
hold on
% deleting dangling bonds within electrodes:
while(dangling(fiber1,N,max_x))
for i=1:N
     num=size(fiber1(i).nodes);
    num_nodes=num(2);
    if(num_nodes==1) && (fiber1(i).center(1)>2*fiber1(i).radius) && (fiber1(i).center(1)<max_x-2*fiber1(i).radius)
        fiber1=deletenode(fiber1,i,N);
    end
end
end
% defining boundary elements
leftnodes=[];
rightnodes=[];
for i=1:N
    if (fiber1(i).center(1)<=2*fiber1(i).radius)
        fiber1(i).nodes=[fiber1(i).nodes 0]; %left boundary
        leftnodes(end+1)=i;
    end
    if (fiber1(i).center(1)>=max_x-2*fiber1(i).radius)
        fiber1(i).nodes=[fiber1(i).nodes N+1]; % right boundary
        rightnodes(end+1)=i;
    end
end
%deleting elements not connected to boundary.
global isconnected;
isconnected=zeros(1,N);
Nleft=max(size(leftnodes));
Nright=max(size(rightnodes));
for i=1:Nleft
  traverse(leftnodes(i),fiber1,N);
end
for i=1:Nright
  traverse(rightnodes(i),fiber1,N);
end
% traverse(rightnodes,fiber1);
% Deleting elements not connected to left or right ends:
for i=1:N
    if (isconnected(i)==0)
        fiber1=deletenode(fiber1,i,N);
    end
end
%plotting the node
count=1;
for i=1:N
    num=size(fiber1(i).nodes);
    num_nodes=num(2);
    if(num_nodes)
        for j=1:num_nodes
            curr_node=fiber1(i).nodes(j);
            if ((curr_node>0) && (curr_node<=N)) %skipping boundary nodes
             plot([fiber1(i).center(1) fiber1(curr_node).center(1)],[fiber1(i).center(2) fiber1(curr_node).center(2)],'r*-','LineWidth',3);
            end
            if curr_node==0
                 plot([0 fiber1(i).center(1)],[fiber1(i).center(2) fiber1(i).center(2)],'r*-','LineWidth',3);
            end
            if curr_node==N+1
                 plot([fiber1(i).center(1) max_x],[fiber1(i).center(2) fiber1(i).center(2)],'r*-','LineWidth',3);
            end
        end
        count=count+1;
    end
end
%applying KVL
%[G]{V}={K}
G=zeros(N);
K=zeros(1,N);
test=0;
for i=1:N
    isleft=sum(fiber1(i).nodes==0); %left node
    isright=sum(fiber1(i).nodes==N+1); %right node
%      isnextleft=sum([fiber(fiber(i).nodes).nodes]==0); %connected to left node
%     isnextright=sum([fiber(fiber(i).nodes).nodes]==N+1); %connected to left node
    num=size(fiber1(i).nodes);
    num_nodes=num(2);
    if(num_nodes)
       if(~(isleft || isright))
           sum_coeff=0;
        for j=1:num_nodes
            ref=fiber1(i).nodes(j);
            fiber_d=sqrt((fiber1(i).center(1)-fiber1(ref).center(1))^2+(fiber1(i).center(2)-fiber1(ref).center(2))^2);
            G(i,fiber1(i).nodes(j))=-1/(exp(fiber_d));
            sum_coeff=sum_coeff+(1/(exp(fiber_d)));
        end
%          G(i,i)=num_nodes;
           G(i,i)=sum_coeff;
       end
       if (isleft)
       G(i,i)=1;
       K(i)=V_left; % Left Voltage
       end
       if(isright)
           G(i,i)=1;
           K(i)=V_right; %Right Voltage
       end
    end
end
G1=G;
[G1 indices]=removezeros(G1);
[G1 indices2]=removezeros(G1');
G1=G1';
voltages=(G1^-1)*(K(indices))';
Final_Voltages=zeros(1,N);
j=1;
% for i=1:N
%     if i==indices(j);
%   Final_Voltage(i)=voltages(j);
%     end
% end
Final_Voltages(indices)=voltages;
% Figure
text(max_x/2,10,'Nodal Voltage Distribution','FontSize',18,'Color','red','BackgroundColor','White');
for i=1:N
 num=size(fiber1(i).nodes);
num_nodes=num(2);
if(num_nodes)
text(fiber1(i).center(1),fiber1(i).center(2),num2str(Final_Voltages(i)),'FontSize',12);
end
end
%Computing incoming and outgoing current
incoming_curr=0;
outgoing_curr=0;
for i=1:N
    isleft=sum(fiber1(i).nodes==0); %left node
    isright=sum(fiber1(i).nodes==N+1); %right node
    if (isleft)
        temp_arr=fiber1(i).nodes;
        loc_curr=Final_Voltages(temp_arr(1:end-1));
        loc_curr=V_left-loc_curr;
        incoming_curr=incoming_curr+sum(loc_curr);
    end
    if (isright)
        temp_arr=fiber1(i).nodes;
        loc_curr=Final_Voltages(temp_arr(1:end-1));
        loc_curr=loc_curr-V_right;
        outgoing_curr=outgoing_curr+sum(loc_curr);
    end
end
runcount=runcount+1;
final_result(runcount,1)=vf;
final_result(runcount,2)=incoming_curr;
close all;
end
% average_result (simnumber,1)=vf;
% average_result (simnumber,2)=mean(final_result(runcount-9:runcount,2));
% average_result (simnumber,3)=std(final_result(runcount-9:runcount,2));
end