Description of RandomPacking
Home > v08 > helper > RandomPacking.m
RandomPacking
PURPOSE
SYNOPSIS
function PerfectFiber = RandomPacking(VF,fiberRadius)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
GenerateFiber2D % Example usage:
GenerateFiber2D % Example usage:
RNetworkGUI1 RNETWORKGUI1 MATLAB code for RNetworkGUI1.fig
SOURCE CODE
function PerfectFiber = RandomPacking(VF,fiberRadius)
VF=0.5
specimen = 1;
fibermat=strcat('vf_',num2str(VF),'_spec',num2str(specimen),'.mat');
load(fibermat)
fiber.x=fiber.x';
fiber.y=fiber.y';
fiber.radius=fiber.radius';
% Now fiber.x fiber.y and fiber.radius are column vectors.
N=size(fiber.radius,1); %
% !!! be careful, depending on the fiber.radius being a row vector or
% column vector, this command can be size(...,2) for row vector
%or size(...,1) for column vectors.
%fiber1= struct('center',[], 'radius',[], 'nodes', []);
aveRad=mean(fiber.radius);
scale=aveRad/fiberRadius;
fiber.x=fiber.x/scale;
fiber.y=fiber.y/scale;
fiber.radius=fiber.radius/scale;
PerfectFiber=fiber;
save PerfectFiber