Description of ReadRAW
Home > v08 > helper > ReadRAW.m
ReadRAW
PURPOSE
function [LineContent,NVariables, NValues] = ReadRAW(filepath)
SYNOPSIS
function [Vin,data,data1]=ReadRAW(infile)
DESCRIPTION
 function [LineContent,NVariables, NValues] = ReadRAW(filepath)
 fid = fopen(filepath);
 % lines = []
 % fid1 = fopen(filepath,'rt')
 % % fid2 = fopen
 line = 0;
 while 1
     line =line+1
     LineContent = fgetl(fid)
     disp(LineContent)
     if LineContent == 'Variables:\n'
          NVariables = line;
     elseif LineContent == 'Values:\n'
         NValues = line;
     end
      if ~ischar(LineContent), break, end
 end
     if LineContent
     lines{end+1} = line
     if pline == 'Variables:'
         nline = fgetl(fid)
         fprintf(fid1,nline)
 %     if ~ischar(line)
 %         break;
 %     end
     end
     pline = line;
 end
 fclose(fid);
 end
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
Func_RhoZ_LTspice % example usage: copy the code inside " if 1==0 ... end" and run.
Function
Func_RhoZ_LTspice % example usage: copy the code inside " if 1==0 ... end" and run.
TestMatlab2LTspice % write Model head
runLTspice % Run LTSpice and reduce data
SOURCE CODE
% function [LineContent,NVariables, NValues] = ReadRAW(filepath)
% fid = fopen(filepath);
% % lines = []
% % fid1 = fopen(filepath,'rt')
% % % fid2 = fopen
% line = 0;
% while 1
%     line =line+1
%     LineContent = fgetl(fid)
%     disp(LineContent)
%     if LineContent == 'Variables:\n'
%          NVariables = line;
%     elseif LineContent == 'Values:\n'
%         NValues = line;
%     end
%      if ~ischar(LineContent), break, end
% end
%     if LineContent
%     lines{end+1} = line
%     if pline == 'Variables:'
%
%         nline = fgetl(fid)
%         fprintf(fid1,nline)
%
%
%
% %     if ~ischar(line)
% %         break;
% %     end
%     end
%
%     pline = line;
% end
% fclose(fid);
% end
function [Vin,data,data1]=ReadRAW(infile)
%?????
%?????????????????????data????????????
%?????
% infile——???????;
% data=????
% tmpfile='tmp2.mat';
fidin=fopen(infile,'r'); % ?????????.list?
% fidtmp=fopen(tmpfile,'w'); % ????????????????
data1=[];
while ~feof(fidin) % ?????????
    tline=fgetl(fidin); % ????????????????
    if ~isempty(tline) % ??????
        str = '[^0-9 | \. | \- | \+ | \s | e | E]'; %??????????????? - . E e ?? ? ???? ??????
        start = regexp(tline,str, 'once');
        if isempty(start)
            %% following 2 lined added
            LocSpace = regexp(tline,'[\s]');
            if LocSpace(1)~=1
                Vin1=str2num(tline);
                Vin=Vin1(2);
            else
                data1(end+1)=str2num(tline);
%                 fprintf(fidtmp,'%f\n',data3);
            end
        end
    end
end
fclose(fidin);
% fclose(fidtmp);
% data1=textscan(tmpfile);
data2 = fliplr(data1);
data=data2(1:end-1);
% delete(tmpfile)