Description of readIMG
Home > v08 > helper > readIMG.m
readIMG
PURPOSE
%
SYNOPSIS
function readIMG(imgname,xmin_ratio,xmax_ratio,ymin_ratio,ymax_ratio)
DESCRIPTION
%
 imgname='laser4.png'
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
SIM_Convergence_Square_IM7 % convergence test: Rz; Square Packing; IM7
SIM_Convergence_Square_IM7[Conflict] % convergence test: Rz; Square Packing; IM7
SIM_IM7_img
SIM_ReadIMG
test2
SOURCE CODE
function readIMG(imgname,xmin_ratio,xmax_ratio,ymin_ratio,ymax_ratio)
%%
% imgname='laser4.png'
A=imread(imgname);
% A=imread('8ply-CFRP0063(x2.0k).tif');
b=im2bw(A);
I = rgb2gray(A);
threshold = graythresh(I);
bw = im2bw(I,threshold);
imshow(bw)
bw = bwareaopen(bw,30);
[centers r]= imfindcircles(bw,[5 20]);  %PARAMETER  [radius range]
% imshow(bw);
% viscircles(centers, r,'EdgeColor','r');
% figure;
% imshow(A)
% viscircles(centers, r,'EdgeColor','r','LineWidth',1);
im_dimensions=size(bw);
%%
max_x=im_dimensions(2); %Left boundary coordinates
max_y=im_dimensions(1);
winXmin=xmin_ratio*max_x;
winXmax=xmax_ratio*max_x;
winYmin=ymin_ratio*max_y;
winYmax=ymax_ratio*max_y;
ind1=centers(:,1)>=winXmin & centers(:,1)<=winXmax;
centers1=centers(ind1,:);
r1=r(ind1);
ind2=centers1(:,2)>=winYmin & centers1(:,2)<=winYmax;
centers2=centers1(ind2,:);
r2=r1(ind2);
viscircles(centers2, r2,'EdgeColor','r','LineWidth',1);
% filename=['c:\directory\subdirectory\Database\matrix'
fiber=struct('x',[],'y',[],'radius',[]);
xcolumn=centers2(:,1);
ycolumn=centers2(:,2);
rcolumn=r2;
fiber.x=xcolumn';
fiber.y=ycolumn';
fiber.radius=rcolumn';
save fiberSEM2 fiber