Description of RNetworkGUI1
Home > v08 > helper > RNetworkGUI1.m
RNetworkGUI1
PURPOSE
RNETWORKGUI1 MATLAB code for RNetworkGUI1.fig
SYNOPSIS
function varargout = RNetworkGUI1(varargin)
DESCRIPTION
 RNETWORKGUI1 MATLAB code for RNetworkGUI1.fig
      RNETWORKGUI1, by itself, creates a new RNETWORKGUI1 or raises the existing
      singleton*.
      H = RNETWORKGUI1 returns the handle to a new RNETWORKGUI1 or the handle to
      the existing singleton*.
      RNETWORKGUI1('CALLBACK',hObject,eventData,handles,...) calls the local
      function named CALLBACK in RNETWORKGUI1.M with the given input arguments.
      RNETWORKGUI1('Property','Value',...) creates a new RNETWORKGUI1 or raises the
      existing singleton*.  Starting from the left, property value pairs are
      applied to the GUI before RNetworkGUI1_OpeningFcn gets called.  An
      unrecognized property name or invalid value makes property application
      stop.  All inputs are passed to RNetworkGUI1_OpeningFcn via varargin.
      *See GUI Options on GUIDE's Tools menu.  Choose "GUI allows only one
      instance to run (singleton)".
 See also: GUIDE, GUIDATA, GUIHANDLES
CROSS-REFERENCE INFORMATION
This function calls:
ContactForce_Exp
ContactR % contact resistance
Func_RhoZ_LTspice % example usage: copy the code inside " if 1==0 ... end" and run.
ContactForce_Exp
ContactR % contact resistance
Func_RNetwork_Z % this function is used when the input fibermat is from generated fiber data (not from SEM).
Func_RhoZ_LTspice % example usage: copy the code inside " if 1==0 ... end" and run.
HexPacking % square packing
RandomPacking
SquarePacking % square packing
display TEMPLATE Display a template object in Matlab window
get TEMPLATE/GET Access data stored in a Template object
set TEMPLATE/SET Edit data stored in a Template object
This function is called by:
SUBFUNCTIONS
function RNetworkGUI1_OpeningFcn(hObject, eventdata, handles, varargin)
function varargout = RNetworkGUI1_OutputFcn(hObject, eventdata, handles)
function vfs_Callback(hObject, eventdata, handles)
function vfs_CreateFcn(hObject, eventdata, handles)
function v0_Callback(hObject, eventdata, handles)
function v0_CreateFcn(hObject, eventdata, handles)
function va_Callback(hObject, eventdata, handles)
function va_CreateFcn(hObject, eventdata, handles)
function beta_Callback(hObject, eventdata, handles)
function beta_CreateFcn(hObject, eventdata, handles)
function e_Callback(hObject, eventdata, handles)
function e_CreateFcn(hObject, eventdata, handles)
function fiberradius_Callback(hObject, eventdata, handles)
function fiberradius_CreateFcn(hObject, eventdata, handles)
function rf_Callback(hObject, eventdata, handles)
function rf_CreateFcn(hObject, eventdata, handles)
function fiberrad_Callback(hObject, eventdata, handles)
function fiberrad_CreateFcn(hObject, eventdata, handles)
function solve1_Callback(hObject, eventdata, handles)
function uitable10_CellEditCallback(hObject, eventdata, handles)
function edit_vfs_Callback(hObject, eventdata, handles)
function edit_vfs_CreateFcn(hObject, eventdata, handles)
function edit_fiberradius_Callback(hObject, eventdata, handles)
function edit_fiberradius_CreateFcn(hObject, eventdata, handles)
function edit_fiberrad_Callback(hObject, eventdata, handles)
function edit_fiberrad_CreateFcn(hObject, eventdata, handles)
function edit_beta_Callback(hObject, eventdata, handles)
function edit_beta_CreateFcn(hObject, eventdata, handles)
function edit_va_Callback(hObject, eventdata, handles)
function edit_va_CreateFcn(hObject, eventdata, handles)
function edit_e_Callback(hObject, eventdata, handles)
function edit_e_CreateFcn(hObject, eventdata, handles)
function edit_v0_Callback(hObject, eventdata, handles)
function edit_v0_CreateFcn(hObject, eventdata, handles)
function edit_rf_Callback(hObject, eventdata, handles)
function edit_rf_CreateFcn(hObject, eventdata, handles)
function uitable11_CellEditCallback(hObject, eventdata, handles)
function table_Callback(hObject, eventdata, handles)
function edit18_Callback(hObject, eventdata, handles)
function edit18_CreateFcn(hObject, eventdata, handles)
function edit19_Callback(hObject, eventdata, handles)
function edit19_CreateFcn(hObject, eventdata, handles)
function edit20_Callback(hObject, eventdata, handles)
function edit20_CreateFcn(hObject, eventdata, handles)
function numbreak_Callback(hObject, eventdata, handles)
function numbreak_CreateFcn(hObject, eventdata, handles)
function rbreakage_Callback(hObject, eventdata, handles)
function rbreakage_CreateFcn(hObject, eventdata, handles)
function fiberlen_Callback(hObject, eventdata, handles)
function fiberlen_CreateFcn(hObject, eventdata, handles)
function edit24_Callback(hObject, eventdata, handles)
function edit24_CreateFcn(hObject, eventdata, handles)
function betamean_Callback(hObject, eventdata, handles)
function betamean_CreateFcn(hObject, eventdata, handles)
function edit27_Callback(hObject, eventdata, handles)
function edit27_CreateFcn(hObject, eventdata, handles)
function betadev_Callback(hObject, eventdata, handles)
function betadev_CreateFcn(hObject, eventdata, handles)
function edit29_Callback(hObject, eventdata, handles)
function edit29_CreateFcn(hObject, eventdata, handles)
function edit30_Callback(hObject, eventdata, handles)
function edit30_CreateFcn(hObject, eventdata, handles)
function fcolumntag_Callback(hObject, eventdata, handles)
function fcolumntag_CreateFcn(hObject, eventdata, handles)
function frowtag_Callback(hObject, eventdata, handles)
function frowtag_CreateFcn(hObject, eventdata, handles)
function enter_Callback(hObject, eventdata, handles)
function enter_CreateFcn(hObject, eventdata, handles)
function popup_Callback(hObject, eventdata, handles)
function popup_CreateFcn(hObject, eventdata, handles)
function Untitled_1_Callback(hObject, eventdata, handles)
function axes2_CreateFcn(hObject, eventdata, handles)
function pushbutton5_Callback(hObject, eventdata, handles)
function popup1_Callback(hObject, eventdata, handles)
function popup1_CreateFcn(hObject, eventdata, handles)
function uitable1_CellEditCallback(hObject, eventdata, handles)
SOURCE CODE
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            function varargout = RNetworkGUI1(varargin)
% RNETWORKGUI1 MATLAB code for RNetworkGUI1.fig
%      RNETWORKGUI1, by itself, creates a new RNETWORKGUI1 or raises the existing
%      singleton*.
%
%      H = RNETWORKGUI1 returns the handle to a new RNETWORKGUI1 or the handle to
%      the existing singleton*.
%
%      RNETWORKGUI1('CALLBACK',hObject,eventData,handles,...) calls the local
%      function named CALLBACK in RNETWORKGUI1.M with the given input arguments.
%
%      RNETWORKGUI1('Property','Value',...) creates a new RNETWORKGUI1 or raises the
%      existing singleton*.  Starting from the left, property value pairs are
%      applied to the GUI before RNetworkGUI1_OpeningFcn gets called.  An
%      unrecognized property name or invalid value makes property application
%      stop.  All inputs are passed to RNetworkGUI1_OpeningFcn via varargin.
%
%      *See GUI Options on GUIDE's Tools menu.  Choose "GUI allows only one
%      instance to run (singleton)".
%
% See also: GUIDE, GUIDATA, GUIHANDLES
% Edit the above text to modify the response to help RNetworkGUI1
% Last Modified by GUIDE v2.5 22-Jul-2015 17:22:37
% Begin initialization code - DO NOT EDIT
gui_Singleton = 1;
gui_State = struct('gui_Name',       mfilename, ...
                   'gui_Singleton',  gui_Singleton, ...
                   'gui_OpeningFcn', @RNetworkGUI1_OpeningFcn, ...
                   'gui_OutputFcn',  @RNetworkGUI1_OutputFcn, ...
                   'gui_LayoutFcn',  [] , ...
                   'gui_Callback',   []);
if nargin && ischar(varargin{1})
    gui_State.gui_Callback = str2func(varargin{1});
end
if nargout
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});
else
    gui_mainfcn(gui_State, varargin{:});
end
% End initialization code - DO NOT EDIT
% --- Executes just before RNetworkGUI1 is made visible.
function RNetworkGUI1_OpeningFcn(hObject, eventdata, handles, varargin)
% This function has no output args, see OutputFcn.
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% varargin   command line arguments to RNetworkGUI1 (see VARARGIN)
% Choose default command line output for RNetworkGUI1
handles.output = hObject;
% data = get(handles.uitable1 ,'Data');
% %display(data)
% %data=str2num(data);
% data = cell2mat(data);
% %display(data)
% data = reshape(strtrim(cellstr(num2str(data(:)))), size(data));
% data(:,1) = cellfun(@(x) ['<html><table border=0 width=400 bgcolor=#FFF0000><TR><TD>' x '</TD></TR> </table></html>'], data(:,1), 'UniformOutput', false);
% data(1,:) = cellfun(@(x) ['<html><table border=0 width=400 bgcolor=#FFF0000><TR><TD>' x '</TD></TR> </table></html>'], data(1,:), 'UniformOutput', false);
%
% %set(handles.uitable1,'Data',data);
axes(handles.axes1)
xlabel('x')
ylabel('y')
grid on
title('y vs x')
% Update handles structure
guidata(hObject, handles);
% UIWAIT makes RNetworkGUI1 wait for user response (see UIRESUME)
% uiwait(handles.figure1);
% --- Outputs from this function are returned to the command line.
function varargout = RNetworkGUI1_OutputFcn(hObject, eventdata, handles)
% varargout  cell array for returning output args (see VARARGOUT);
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Get default command line output from handles structure
varargout{1} = handles.output;
function vfs_Callback(hObject, eventdata, handles)
% hObject    handle to vfs (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of vfs as text
%        str2double(get(hObject,'String')) returns contents of vfs as a double
% --- Executes during object creation, after setting all properties.
function vfs_CreateFcn(hObject, eventdata, handles)
% hObject    handle to vfs (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function v0_Callback(hObject, eventdata, handles)
% hObject    handle to v0 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of v0 as text
%        str2double(get(hObject,'String')) returns contents of v0 as a double
% --- Executes during object creation, after setting all properties.
function v0_CreateFcn(hObject, eventdata, handles)
% hObject    handle to v0 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function va_Callback(hObject, eventdata, handles)
% hObject    handle to va (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of va as text
%        str2double(get(hObject,'String')) returns contents of va as a double
% --- Executes during object creation, after setting all properties.
function va_CreateFcn(hObject, eventdata, handles)
% hObject    handle to va (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function beta_Callback(hObject, eventdata, handles)
% hObject    handle to beta (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of beta as text
%        str2double(get(hObject,'String')) returns contents of beta as a double
% --- Executes during object creation, after setting all properties.
function beta_CreateFcn(hObject, eventdata, handles)
% hObject    handle to beta (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function e_Callback(hObject, eventdata, handles)
% hObject    handle to e (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of e as text
%        str2double(get(hObject,'String')) returns contents of e as a double
% --- Executes during object creation, after setting all properties.
function e_CreateFcn(hObject, eventdata, handles)
% hObject    handle to e (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function fiberradius_Callback(hObject, eventdata, handles)
% hObject    handle to fiberradius (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of fiberradius as text
%        str2double(get(hObject,'String')) returns contents of fiberradius as a double
% --- Executes during object creation, after setting all properties.
function fiberradius_CreateFcn(hObject, eventdata, handles)
% hObject    handle to fiberradius (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function rf_Callback(hObject, eventdata, handles)
% hObject    handle to rf (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of rf as text
%        str2double(get(hObject,'String')) returns contents of rf as a double
% --- Executes during object creation, after setting all properties.
function rf_CreateFcn(hObject, eventdata, handles)
% hObject    handle to rf (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function fiberrad_Callback(hObject, eventdata, handles)
% hObject    handle to fiberrad (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of fiberrad as text
%        str2double(get(hObject,'String')) returns contents of fiberrad as a double
% --- Executes during object creation, after setting all properties.
function fiberrad_CreateFcn(hObject, eventdata, handles)
% hObject    handle to fiberrad (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
% --- Executes on button press in solve1.
function solve1_Callback(hObject, eventdata, handles)
% hObject    handle to solve1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
data0 = get(handles.uitable1 ,'Data');
%display(data)
data=cell2mat(data0);
display(data)
%data=str2num(data);
allVF = data(:,1);
allV0 = data(:,2);
% v0_1=V0(1);
allVa = data(:,3);
allbeta = data(:,4);
allE = data(:,5);
allfiberRadius = data(:,6);
allFiberRad = data(:,7);
allrf = data(:,8);
allNumBreak = data(:,9);
allRBreakage =data(:,10);
allfiberLen =data(:,11);
allbeta_mean = data(:,12);
allbeta_dev =data(:,13);
allfrow = data(:,14);
allfcolumn = data(:,15);
Enter = get(handles.enter,'String');
%% bulid 3d structure based on various packing order (choose from GUI)
% popup-menu to choose the functions
Packing = get(handles.popup,'Value');
switch Packing
    case 1 %% blank
        h = msgbox('Please Choose a function', 'Error','error');
    case 2 %% Random packing
        GenerateFibermat=@RandomPacking; % Now GenerateFibermat function is the same as SquarePakcing function. Will use function GenerateFibermat later on.
       % specimen=1;
        %fibermat=strcat('vf_',num2str(VF),'_spec',num2str(specimen),'.mat');
    case 3  % Square Packing
        GenerateFibermat=@SquarePacking; % Now GenerateFibermat function is the same as SquarePakcing function. Will use function GenerateFibermat later on.
        %SquarePacking(frow,fcolumn,VF,fiberRadius);
        %fibermat='PerfectFiber.mat';
    case 4        %Hexagonal Packing
        GenerateFibermat=@HexPacking; % Now GenerateFibermat function is the same as HexPakcing function. Will use function GenerateFibermat later on.
        %HexPacking(frow,fcolumn,VF,fiberRadius);
        %fibermat='PerfectFiber.mat';
    otherwise
end
%% Now choose input that will be used in calculation
% initialize input. Select the first value for all inputs by default
VF=allVF(1);
V0=allV0(1);
Va=allVa(1);
beta=allbeta(1);
E=allE(1);
FiberRad=allFiberRad(1);
rf=allrf(1);
NumBreak=allNumBreak(1);
RBreakage=allRBreakage(1);
fiberLen=allfiberLen(1);
beta_mean=allbeta_mean(1);
beta_dev=allbeta_dev(1);
frow=allfrow(1);
fcolumn=allfcolumn(1);
% create a vector to store calculation results
rhos=[];
% % create Table and Define Axes
axes(handles.axes1)
grid on
%% popup-menu to choose plotting
Variable= get(handles.popup1,'Value');
switch Variable
    case 1           % VF vs rho
        for i=1:length(allVF)
            VF=allVF(i)  % update VF here
            %% get fiber structure (fibermat)
            if (Packing==2)
                GenerateFibermat(VF,FiberRad);
            else
                GenerateFibermat(frow,fcolumn,VF,FiberRad); % Note that GenerateFibermat can be different functions based on the functions we selected before
            end
            fibermat='PerfectFiber.mat';
            %% calculate Rc
            [Fc,Pressure] = ContactForce_Exp(V0,Va,VF,beta,E,FiberRad);
            Rc = ContactR(FiberRad,Fc,E,rf);
            %% calculate rho
            NetList='Temp';
            rho =Func_RhoZ_LTspice(NetList,fibermat,fiberLen,beta_mean,FiberRad,NumBreak,Rc,rf,RBreakage);
           % [rho,fiber,VF,NumContacts]=Func_RNetwork_Z(fibermat,fiberLen,beta_mean,FiberRad,NumBreak,Rc,rf,RBreakage);
            rhos(end+1)=rho;
        end
        % plotting
        plot(allVF,rhos)   %% be careful of the sequence of rhos and VFs! proper use of plot: plot(X,Y)
        ylabel('rho')
        xlabel('Volum fraction')
        title('rho vs Volum fraction')
    case 2       % V0 vs rho
        for i=1:length(allV0)
            V0=allV0(i)  % update V0 here
            %% get fiber structure (fibermat)
            GenerateFibermat(frow,fcolumn,VF,FiberRad); % Note that GenerateFibermat can be different functions based on the functions we selected before
            fibermat='PerfectFiber.mat';
            %% calculate Rc
            [Fc,Pressure] = ContactForce_Exp(V0,Va,VF,beta,E,FiberRad);
            Rc = ContactR(FiberRad,Fc,E,rf);
            %% calculate rho
            [rho,fiber,VF,NumContacts]=Func_RNetwork_Z(fibermat,fiberLen,beta_mean,FiberRad,NumBreak,Rc,rf,RBreakage);
            rhos(end+1)=rho;
        end
        plot(allV0,rhos)   %% be careful of the sequence of X and Y!  proper use of plot: plot(X,Y), X should be first
        ylabel('rho')
        xlabel('V0')
        title('rho vs V0')
    case 3           % Va vs rho
        for i=1:length(allVa)
            Va=allVa(i)  % update Va here
            %% get fiber structure (fibermat)
            GenerateFibermat(frow,fcolumn,VF,FiberRad); % Note that GenerateFibermat can be different functions based on the functions we selected before
            fibermat='PerfectFiber.mat';
            %% calculate Rc
            [Fc,Pressure] = ContactForce_Exp(V0,Va,VF,beta,E,FiberRad);
            Rc = ContactR(FiberRad,Fc,E,rf);
            %% calculate rho
            [rho,fiber,VF,NumContacts]=Func_RNetwork_Z(fibermat,fiberLen,beta_mean,FiberRad,NumBreak,Rc,rf,RBreakage);
            rhos(end+1)=rho;
        end
        plot(allVa,rhos)   %% be careful of the sequence of rhos and VFs! proper use of plot: plot(X,Y)
        ylabel('rho')
        xlabel('Va')
        title('rho vs Va')
        case 4
            for i=1:length(allbeta)
            beta=allbeta(i)  % update beta here
            %% get fiber structure (fibermat)
            GenerateFibermat(frow,fcolumn,VF,FiberRad); % Note that GenerateFibermat can be different functions based on the functions we selected before
            fibermat='PerfectFiber.mat';
            %% calculate Rc
            [Fc,Pressure] = ContactForce_Exp(V0,Va,VF,beta,E,FiberRad);
            Rc = ContactR(FiberRad,Fc,E,rf);
            %% calculate rho
            [rho,fiber,VF,NumContacts]=Func_RNetwork_Z(fibermat,fiberLen,beta_mean,FiberRad,NumBreak,Rc,rf,RBreakage);
            rhos(end+1)=rho;
        end
        plot(allbeta,rhos)   %% be careful of the sequence of rhos and VFs! proper use of plot: plot(X,Y)
        ylabel('rho')
        xlabel('beta')
        title('rho vs beta')
    case 5
           for i=1:length(allE)
            E=allE(i)  % update E here
            %% get fiber structure (fibermat)
            GenerateFibermat(frow,fcolumn,VF,FiberRad); % Note that GenerateFibermat can be different functions based on the functions we selected before
            fibermat='PerfectFiber.mat';
            %% calculate Rc
            [Fc,Pressure] = ContactForce_Exp(V0,Va,VF,beta,E,FiberRad);
            Rc = ContactR(FiberRad,Fc,E,rf);
            %% calculate rho
            [rho,fiber,VF,NumContacts]=Func_RNetwork_Z(fibermat,fiberLen,beta_mean,FiberRad,NumBreak,Rc,rf,RBreakage);
            rhos(end+1)=rho;
        end
        plot(allE,rhos)   %% be careful of the sequence of rhos and VFs! proper use of plot: plot(X,Y)
        ylabel('rho')
        xlabel('E')
        title('rho vs E')
    case 6
           for i=1:length(allFiberRad)
            FiberRad=allFiberRad(i)  % update beta here
            %% get fiber structure (fibermat)
            GenerateFibermat(frow,fcolumn,VF,FiberRad); % Note that GenerateFibermat can be different functions based on the functions we selected before
            fibermat='PerfectFiber.mat';
            %% calculate Rc
            [Fc,Pressure] = ContactForce_Exp(V0,Va,VF,beta,E,FiberRad);
            Rc = ContactR(FiberRad,Fc,E,rf);
            %% calculate rho
            [rho,fiber,VF,NumContacts]=Func_RNetwork_Z(fibermat,fiberLen,beta_mean,FiberRad,NumBreak,Rc,rf,RBreakage);
            rhos(end+1)=rho;
        end
        plot(allFiberRad,rhos)   %% be careful of the sequence of rhos and VFs! proper use of plot: plot(X,Y)
        ylabel('rho')
        xlabel('FiberRad')
        title('rho vs FiberRad')
    case 7
        for i=1:length(allNumBreak)
         NumBreak=allNumBreak(i)  % update beta here
            %% get fiber structure (fibermat)
            GenerateFibermat(frow,fcolumn,VF,FiberRad); % Note that GenerateFibermat can be different functions based on the functions we selected before
            fibermat='PerfectFiber.mat';
            %% calculate Rc
            [Fc,Pressure] = ContactForce_Exp(V0,Va,VF,beta,E,FiberRad);
            Rc = ContactR(FiberRad,Fc,E,rf);
            %% calculate rho
            [rho,fiber,VF,NumContacts]=Func_RNetwork_Z(fibermat,fiberLen,beta_mean,FiberRad,NumBreak,Rc,rf,RBreakage);
            rhos(end+1)=rho;
        end
        plot(allNumBreak,rhos)   %% be careful of the sequence of rhos and VFs! proper use of plot: plot(X,Y)
        ylabel('rho')
        xlabel('NumBreak')
        title('rho vs NumBreak')
    case 8
        for i=1:length(allrf)
        rf=allrf(i)  % update beta here
            %% get fiber structure (fibermat)
            GenerateFibermat(frow,fcolumn,VF,FiberRad); % Note that GenerateFibermat can be different functions based on the functions we selected before
            fibermat='PerfectFiber.mat';
            %% calculate Rc
            [Fc,Pressure] = ContactForce_Exp(V0,Va,VF,beta,E,FiberRad);
            Rc = ContactR(FiberRad,Fc,E,rf);
            %% calculate rho
            [rho,fiber,VF,NumContacts]=Func_RNetwork_Z(fibermat,fiberLen,beta_mean,FiberRad,NumBreak,Rc,rf,RBreakage);
            rhos(end+1)=rho;
        end
        plot(allrf,rhos)   %% be careful of the sequence of rhos and VFs! proper use of plot: plot(X,Y)
        ylabel('rho')
        xlabel('rf')
        title('rho vs rf')
    case 9
        for i=1:length(allRBreakage)
        RBreakage=allRBreakage(i)  % update beta here
            %% get fiber structure (fibermat)
            GenerateFibermat(frow,fcolumn,VF,FiberRad); % Note that GenerateFibermat can be different functions based on the functions we selected before
            fibermat='PerfectFiber.mat';
            %% calculate Rc
            [Fc,Pressure] = ContactForce_Exp(V0,Va,VF,beta,E,FiberRad);
            Rc = ContactR(FiberRad,Fc,E,rf);
            %% calculate rho
            [rho,fiber,VF,NumContacts]=Func_RNetwork_Z(fibermat,fiberLen,beta_mean,FiberRad,NumBreak,Rc,rf,RBreakage);
            rhos(end+1)=rho;
        end
        plot(allRBreakage,rhos)   %% be careful of the sequence of rhos and VFs! proper use of plot: plot(X,Y)
        ylabel('rho')
        xlabel('RBreakage')
        title('rho vs RBreakage')
        case 10
            for i=1:length(allfiberLen)
        fiberLen=allfiberLen(i)  % update beta here
            %% get fiber structure (fibermat)
            GenerateFibermat(frow,fcolumn,VF,FiberRad); % Note that GenerateFibermat can be different functions based on the functions we selected before
            fibermat='PerfectFiber.mat';
            %% calculate Rc
            [Fc,Pressure] = ContactForce_Exp(V0,Va,VF,beta,E,FiberRad);
            Rc = ContactR(FiberRad,Fc,E,rf);
            %% calculate rho
            [rho,fiber,VF,NumContacts]=Func_RNetwork_Z(fibermat,fiberLen,beta_mean,FiberRad,NumBreak,Rc,rf,RBreakage);
            rhos(end+1)=rho;
        end
        plot(allfiberLen,rhos)   %% be careful of the sequence of rhos and VFs! proper use of plot: plot(X,Y)
        ylabel('rho')
        xlabel('fiberLen')
        title('rho vs fiberLen')
        case 11
            for i=1:length(allbeta_mean)
        beta_mean=allbeta_mean(i)  % update beta here
            %% get fiber structure (fibermat)
            GenerateFibermat(frow,fcolumn,VF,FiberRad); % Note that GenerateFibermat can be different functions based on the functions we selected before
            fibermat='PerfectFiber.mat';
            %% calculate Rc
            [Fc,Pressure] = ContactForce_Exp(V0,Va,VF,beta,E,FiberRad);
            Rc = ContactR(FiberRad,Fc,E,rf);
            %% calculate rho
            [rho,fiber,VF,NumContacts]=Func_RNetwork_Z(fibermat,fiberLen,beta_mean,FiberRad,NumBreak,Rc,rf,RBreakage);
            rhos(end+1)=rho;
        end
        plot(allbeta_mean,rhos)   %% be careful of the sequence of rhos and VFs! proper use of plot: plot(X,Y)
        ylabel('rho')
        xlabel('beta_mean')
        title('rho vs beta_mean')
        case 12
            for i=1:length(allbeta_dev)
        beta_dev=allbeta_dev(i)  % update beta here
            %% get fiber structure (fibermat)
            GenerateFibermat(frow,fcolumn,VF,FiberRad); % Note that GenerateFibermat can be different functions based on the functions we selected before
            fibermat='PerfectFiber.mat';
            %% calculate Rc
            [Fc,Pressure] = ContactForce_Exp(V0,Va,VF,beta,E,FiberRad);
            Rc = ContactR(FiberRad,Fc,E,rf);
            %% calculate rho
            [rho,fiber,VF,NumContacts]=Func_RNetwork_Z(fibermat,fiberLen,beta_mean,FiberRad,NumBreak,Rc,rf,RBreakage);
            rhos(end+1)=rho;
        end
        plot(allbeta_dev,rhos)   %% be careful of the sequence of rhos and VFs! proper use of plot: plot(X,Y)
        ylabel('rho')
        xlabel('beta_dev')
        title('rho vs beta_dev')
        case 13
            for i=1:length(allfrow)
        frow=allfrow(i)  % update beta here
            %% get fiber structure (fibermat)
            GenerateFibermat(frow,fcolumn,VF,FiberRad); % Note that GenerateFibermat can be different functions based on the functions we selected before
            fibermat='PerfectFiber.mat';
            %% calculate Rc
            [Fc,Pressure] = ContactForce_Exp(V0,Va,VF,beta,E,FiberRad);
            Rc = ContactR(FiberRad,Fc,E,rf);
            %% calculate rho
            [rho,fiber,VF,NumContacts]=Func_RNetwork_Z(fibermat,fiberLen,beta_mean,FiberRad,NumBreak,Rc,rf,RBreakage);
            rhos(end+1)=rho;
        end
        plot(allfrow,rhos)   %% be careful of the sequence of rhos and VFs! proper use of plot: plot(X,Y)
        ylabel('rho')
        xlabel('frow')
        title('rho vs frow')
        case 14
            for i=1:length(allfcolumn)
        fcolumn=allfcolumn(i)  % update beta here
            %% get fiber structure (fibermat)
            GenerateFibermat(frow,fcolumn,VF,FiberRad); % Note that GenerateFibermat can be different functions based on the functions we selected before
            fibermat='PerfectFiber.mat';
            %% calculate Rc
            [Fc,Pressure] = ContactForce_Exp(V0,Va,VF,beta,E,FiberRad);
            Rc = ContactR(FiberRad,Fc,E,rf);
            %% calculate rho
            [rho,fiber,VF,NumContacts]=Func_RNetwork_Z(fibermat,fiberLen,beta_mean,FiberRad,NumBreak,Rc,rf,RBreakage);
            rhos(end+1)=rho;
        end
        plot(allfcolumn,rhos)   %% be careful of the sequence of rhos and VFs! proper use of plot: plot(X,Y)
        ylabel('rho')
        xlabel('fcolumn')
        title('rho vs fcolumn')
end
guidata(hObject,handles);
%
% %call the Inputs from the uitable
%
% data = get(handles.uitable1 ,'Data');
% allVFs = cell2mat(data(:,1));
% V0 = cell2mat(data(:,2));
% % v0_1=V0(1);
% Va = cell2mat(data(:,3));
% beta = cell2mat(data(:,4));
% E = cell2mat(data(:,5));
% fiberRadius = cell2mat(data(:,6));
% FiberRad = cell2mat(data(:,7));
% rf = cell2mat(data(:,8));
% NumBreak = cell2mat(data(:,9));
% RBreakage = cell2mat(data(:,10));
% fiberLen = cell2mat(data(:,11));
% beta_mean = cell2mat(data(:,12));
% beta_dev = cell2mat(data(:,13));
% frow = cell2mat(data(:,14));
% fcolumn = cell2mat(data(:,15));
%
% Enter = get(handles.enter,'String');
% % inputs for editbox
%
% % VFs = str2num(get(handles.vfs, 'String'));
% % V0 = get(handles.uitable1, 'Data');
% % Va = str2num (get(handles.va, 'String'));
% % beta = str2num (get(handles.beta, 'String'));
% % E = str2num (get(handles.e, 'String'));
% % fiberRadius = str2num (get(handles.fiberradius, 'String'));
% % FiberRad = str2num (get(handles.fiberrad, 'String'));
% % rf = str2num (get(handles.rf, 'String'));
% % NumBreak = str2num (get(handles.numbreak, 'String'));
% % RBreakage = str2num (get(handles.rbreakage, 'String'));
% % fiberLen = str2num (get(handles.fiberlen, 'String'));
% % beta_mean = str2num (get(handles.betamean, 'String'));
% % beta_dev = str2num (get(handles.betadev, 'String'));
% % frow = str2num (get(handles.frowtag, 'String'));
% % fcolumn = str2num (get(handles.fcolumntag, 'String'));
%
%
%
% % popup-menu to choose the functions
% rhos=[];
% for i=1:length(VFs)
%     VF=VFs(i);
%
%    x = get(handles.popup,'Value');
%
% switch x
%
%     case 1
%         h = msgbox('Please Choose a function', 'Error','error');
%
%
%     case 2
%
%
%         [Fc,Pressure] = ContactForce_Exp(V0,Va,VF,beta,E,fiberRadius);
%
% Rc = ContactR(fiberRadius,Fc,E,rf);
% %1. Random Packing
%
% specimen=1;
% fibermat=strcat('vf_',num2str(VF),'_spec',num2str(specimen),'.mat');
%
%     case 3
%
%         [Fc,Pressure] = ContactForce_Exp(V0,Va,VF,beta,E,fiberRadius);
% Rc = ContactR(fiberRadius,Fc,E,rf);
% %3. Square Packing
% SquarePacking(frow,fcolumn,VF,fiberRadius);
% fibermat='PerfectFiber.mat';
%
%     case 4
%
%         [Fc,Pressure] = ContactForce_Exp(V0,Va,VF,beta,E,fiberRadius);
% Rc = ContactR(fiberRadius,Fc,E,rf);
% %3. Hexagonal Packing
% HexPacking(frow,fcolumn,VF,fiberRadius);
% fibermat='PerfectFiber.mat';
%
%     otherwise
% end
%
% [rho,fiber,VF,NumContacts]=Func_RNetwork_Z(fibermat,fiberLen,beta_mean,fiberRadius,NumBreak,Rc,rf,RBreakage);
% rhos(end+1)=rho;
% end
%
%
% % % % create the Table
% V0_1  = V0.*ones(1,length(VFs));
% Va_1 = Va.*ones(1,length(VFs));
% beta_1 = beta.*ones(1,length(VFs));
% E_1 = E.*ones(1,length(VFs));
% fiberRadius_1 = fiberRadius.*ones(1,length(VFs));
% FiberRad_1 = FiberRad.*ones(1,length(VFs));
% rf_1 = rf.*ones(1,length(VFs));
% fiberLen_1 = fiberLen.*ones(1,length(VFs));
% RBreakage_1 = RBreakage.*ones(1,length(VFs));
% NumBreak_1 = NumBreak.*ones(1,length(VFs));
% beta_mean_1 = beta_mean.*ones(1,length(VFs));
% beta_dev_1 = beta_dev.*ones(1,length(VFs));
% frow_1 = frow.*ones(1,length(VFs));
% fcolumn_1 = fcolumn.*ones(1,length(VFs));
A = [V0;Va;beta;E;fiberRadius;FiberRad;rf;fiberLen;RBreakage;NumBreak;beta_mean;beta_dev;frow;fcolumn;VF;rhos];
fileID = fopen(Enter,'w');
fprintf(fileID,'%6s,%6s,%6s,%6s,%6s,%6s,%6s,%6s,%6s,%6s,%6s,%6s,%6s,%6s,%6s,%12s\r\n','V0','Va','beta','E',...
'fiberRadius','FiberRad','rf','fiberLen','Rbreakage','NumBreak','beta_mean','beta_dev','frow','fcolumn','VFs','rhos');
% fprintf(fileID,'%6s %6s %6s %6s %6s %6s %6s %6s %6s %6s %6s %6s %6s %12s\n','V0','Va','beta','E',...
% 'fiberRadius','FiberRad','rf','fiberLen','RBreakage','NumBreak','beta_mean','beta_dev','VFs','rhoz');
fprintf(fileID,'%6.2f,%6.2f,%6.2f,%2.10f,%2.10f,%2.20f,%2.20f,%6.2f,%6.2f,%6.2f,%6.2f,%6.2f,%6.2f,%6.2f,%6.2f,%12.8f\r\n' ,A);
fclose(fileID);
% % % create Table end
% %
% % % Define Axes
%
% axes(handles.axes1)
%
% % popup-menu to choose plotting
%
% s = get(handles.popup1,'Value');
%
% switch s
%
%     case 1
%         plot(rhos,VFs)
%         xlabel('rho')
%         ylabel('Volumfraction')
%         title('Volumfraction vs rho')
%
%     case 2
%         plot(rhos,V0)
%         xlabel('rho')
%         ylabel('V0')
%         title('V0 vs rho')
%
%     case 3
%         plot(rhos,Va_1)
%         xlabel('rho')
%         ylabel('Va')
%         title('Va vs rho')
%
%
%     otherwise
% end
%
% grid on
% % xlabel('rho')
% % ylabel('Volumfraction')
% % title('Volumfraction vs rho')
% guidata(hObject,handles);
% end Define Axes
% --- Executes when entered data in editable cell(s) in uitable10.
function uitable10_CellEditCallback(hObject, eventdata, handles)
% hObject    handle to uitable10 (see GCBO)
% eventdata  structure with the following fields (see MATLAB.UI.CONTROL.TABLE)
%    Indices: row and column indices of the cell(s) edited
%    PreviousData: previous data for the cell(s) edited
%    EditData: string(s) entered by the user
%    NewData: EditData or its converted form set on the Data property. Empty if Data was not changed
%    Error: error string when failed to convert EditData to appropriate value for Data
% handles    structure with handles and user data (see GUIDATA)
data = get(hObject, 'data');
function edit_vfs_Callback(hObject, eventdata, handles)
% hObject    handle to edit_vfs (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of edit_vfs as text
%        str2double(get(hObject,'String')) returns contents of edit_vfs as a double
% --- Executes during object creation, after setting all properties.
function edit_vfs_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit_vfs (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function edit_fiberradius_Callback(hObject, eventdata, handles)
% hObject    handle to edit_fiberradius (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of edit_fiberradius as text
%        str2double(get(hObject,'String')) returns contents of edit_fiberradius as a double
% --- Executes during object creation, after setting all properties.
function edit_fiberradius_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit_fiberradius (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function edit_fiberrad_Callback(hObject, eventdata, handles)
% hObject    handle to edit_fiberrad (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of edit_fiberrad as text
%        str2double(get(hObject,'String')) returns contents of edit_fiberrad as a double
% --- Executes during object creation, after setting all properties.
function edit_fiberrad_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit_fiberrad (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function edit_beta_Callback(hObject, eventdata, handles)
% hObject    handle to edit_beta (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of edit_beta as text
%        str2double(get(hObject,'String')) returns contents of edit_beta as a double
% --- Executes during object creation, after setting all properties.
function edit_beta_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit_beta (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function edit_va_Callback(hObject, eventdata, handles)
% hObject    handle to edit_va (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of edit_va as text
%        str2double(get(hObject,'String')) returns contents of edit_va as a double
% --- Executes during object creation, after setting all properties.
function edit_va_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit_va (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function edit_e_Callback(hObject, eventdata, handles)
% hObject    handle to edit_e (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of edit_e as text
%        str2double(get(hObject,'String')) returns contents of edit_e as a double
% --- Executes during object creation, after setting all properties.
function edit_e_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit_e (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function edit_v0_Callback(hObject, eventdata, handles)
% hObject    handle to edit_v0 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of edit_v0 as text
%        str2double(get(hObject,'String')) returns contents of edit_v0 as a double
% --- Executes during object creation, after setting all properties.
function edit_v0_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit_v0 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function edit_rf_Callback(hObject, eventdata, handles)
% hObject    handle to edit_rf (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of edit_rf as text
%        str2double(get(hObject,'String')) returns contents of edit_rf as a double
% --- Executes during object creation, after setting all properties.
function edit_rf_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit_rf (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
% --- Executes when entered data in editable cell(s) in uitable11.
function uitable11_CellEditCallback(hObject, eventdata, handles)
% hObject    handle to uitable11 (see GCBO)
% eventdata  structure with the following fields (see MATLAB.UI.CONTROL.TABLE)
%    Indices: row and column indices of the cell(s) edited
%    PreviousData: previous data for the cell(s) edited
1000 %    EditData: string(s) entered by the user
1001 %    NewData: EditData or its converted form set on the Data property. Empty if Data was not changed
1002 %    Error: error string when failed to convert EditData to appropriate value for Data
1003 % handles    structure with handles and user data (see GUIDATA)
1004
1005
1006 % --- Executes on button press in table.
1007 function table_Callback(hObject, eventdata, handles)
1008 % hObject    handle to table (see GCBO)
1009 % eventdata  reserved - to be defined in a future version of MATLAB
1010 % handles    structure with handles and user data (see GUIDATA)
1011
1012
1013
1014 function edit18_Callback(hObject, eventdata, handles)
1015 % hObject    handle to edit18 (see GCBO)
1016 % eventdata  reserved - to be defined in a future version of MATLAB
1017 % handles    structure with handles and user data (see GUIDATA)
1018
1019 % Hints: get(hObject,'String') returns contents of edit18 as text
1020 %        str2double(get(hObject,'String')) returns contents of edit18 as a double
1021
1022
1023
1024
1025 % --- Executes during object creation, after setting all properties.
1026 function edit18_CreateFcn(hObject, eventdata, handles)
1027 % hObject    handle to edit18 (see GCBO)
1028 % eventdata  reserved - to be defined in a future version of MATLAB
1029 % handles    empty - handles not created until after all CreateFcns called
1030
1031 % Hint: edit controls usually have a white background on Windows.
1032 %       See ISPC and COMPUTER.
1033 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1034     set(hObject,'BackgroundColor','white');
1035 end
1036
1037
1038
1039 function edit19_Callback(hObject, eventdata, handles)
1040 % hObject    handle to edit19 (see GCBO)
1041 % eventdata  reserved - to be defined in a future version of MATLAB
1042 % handles    structure with handles and user data (see GUIDATA)
1043
1044 % Hints: get(hObject,'String') returns contents of edit19 as text
1045 %        str2double(get(hObject,'String')) returns contents of edit19 as a double
1046
1047
1048 % --- Executes during object creation, after setting all properties.
1049 function edit19_CreateFcn(hObject, eventdata, handles)
1050 % hObject    handle to edit19 (see GCBO)
1051 % eventdata  reserved - to be defined in a future version of MATLAB
1052 % handles    empty - handles not created until after all CreateFcns called
1053
1054 % Hint: edit controls usually have a white background on Windows.
1055 %       See ISPC and COMPUTER.
1056 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1057     set(hObject,'BackgroundColor','white');
1058 end
1059
1060
1061
1062 function edit20_Callback(hObject, eventdata, handles)
1063 % hObject    handle to edit20 (see GCBO)
1064 % eventdata  reserved - to be defined in a future version of MATLAB
1065 % handles    structure with handles and user data (see GUIDATA)
1066
1067 % Hints: get(hObject,'String') returns contents of edit20 as text
1068 %        str2double(get(hObject,'String')) returns contents of edit20 as a double
1069
1070
1071 % --- Executes during object creation, after setting all properties.
1072 function edit20_CreateFcn(hObject, eventdata, handles)
1073 % hObject    handle to edit20 (see GCBO)
1074 % eventdata  reserved - to be defined in a future version of MATLAB
1075 % handles    empty - handles not created until after all CreateFcns called
1076
1077 % Hint: edit controls usually have a white background on Windows.
1078 %       See ISPC and COMPUTER.
1079 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1080     set(hObject,'BackgroundColor','white');
1081 end
1082
1083
1084
1085 function numbreak_Callback(hObject, eventdata, handles)
1086 % hObject    handle to numbreak (see GCBO)
1087 % eventdata  reserved - to be defined in a future version of MATLAB
1088 % handles    structure with handles and user data (see GUIDATA)
1089
1090 % Hints: get(hObject,'String') returns contents of numbreak as text
1091 %        str2double(get(hObject,'String')) returns contents of numbreak as a double
1092
1093
1094 % --- Executes during object creation, after setting all properties.
1095 function numbreak_CreateFcn(hObject, eventdata, handles)
1096 % hObject    handle to numbreak (see GCBO)
1097 % eventdata  reserved - to be defined in a future version of MATLAB
1098 % handles    empty - handles not created until after all CreateFcns called
1099
1100 % Hint: edit controls usually have a white background on Windows.
1101 %       See ISPC and COMPUTER.
1102 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1103     set(hObject,'BackgroundColor','white');
1104 end
1105
1106
1107
1108 function rbreakage_Callback(hObject, eventdata, handles)
1109 % hObject    handle to rbreakage (see GCBO)
1110 % eventdata  reserved - to be defined in a future version of MATLAB
1111 % handles    structure with handles and user data (see GUIDATA)
1112
1113 % Hints: get(hObject,'String') returns contents of rbreakage as text
1114 %        str2double(get(hObject,'String')) returns contents of rbreakage as a double
1115
1116
1117 % --- Executes during object creation, after setting all properties.
1118 function rbreakage_CreateFcn(hObject, eventdata, handles)
1119 % hObject    handle to rbreakage (see GCBO)
1120 % eventdata  reserved - to be defined in a future version of MATLAB
1121 % handles    empty - handles not created until after all CreateFcns called
1122
1123 % Hint: edit controls usually have a white background on Windows.
1124 %       See ISPC and COMPUTER.
1125 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1126     set(hObject,'BackgroundColor','white');
1127 end
1128
1129
1130
1131 function fiberlen_Callback(hObject, eventdata, handles)
1132 % hObject    handle to fiberlen (see GCBO)
1133 % eventdata  reserved - to be defined in a future version of MATLAB
1134 % handles    structure with handles and user data (see GUIDATA)
1135
1136 % Hints: get(hObject,'String') returns contents of fiberlen as text
1137 %        str2double(get(hObject,'String')) returns contents of fiberlen as a double
1138
1139
1140 % --- Executes during object creation, after setting all properties.
1141 function fiberlen_CreateFcn(hObject, eventdata, handles)
1142 % hObject    handle to fiberlen (see GCBO)
1143 % eventdata  reserved - to be defined in a future version of MATLAB
1144 % handles    empty - handles not created until after all CreateFcns called
1145
1146 % Hint: edit controls usually have a white background on Windows.
1147 %       See ISPC and COMPUTER.
1148 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1149     set(hObject,'BackgroundColor','white');
1150 end
1151
1152
1153
1154 function edit24_Callback(hObject, eventdata, handles)
1155 % hObject    handle to edit24 (see GCBO)
1156 % eventdata  reserved - to be defined in a future version of MATLAB
1157 % handles    structure with handles and user data (see GUIDATA)
1158
1159 % Hints: get(hObject,'String') returns contents of edit24 as text
1160 %        str2double(get(hObject,'String')) returns contents of edit24 as a double
1161
1162
1163 % --- Executes during object creation, after setting all properties.
1164 function edit24_CreateFcn(hObject, eventdata, handles)
1165 % hObject    handle to edit24 (see GCBO)
1166 % eventdata  reserved - to be defined in a future version of MATLAB
1167 % handles    empty - handles not created until after all CreateFcns called
1168
1169 % Hint: edit controls usually have a white background on Windows.
1170 %       See ISPC and COMPUTER.
1171 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1172     set(hObject,'BackgroundColor','white');
1173 end
1174
1175
1176
1177 function betamean_Callback(hObject, eventdata, handles)
1178 % hObject    handle to betamean (see GCBO)
1179 % eventdata  reserved - to be defined in a future version of MATLAB
1180 % handles    structure with handles and user data (see GUIDATA)
1181
1182 % Hints: get(hObject,'String') returns contents of betamean as text
1183 %        str2double(get(hObject,'String')) returns contents of betamean as a double
1184
1185
1186 % --- Executes during object creation, after setting all properties.
1187 function betamean_CreateFcn(hObject, eventdata, handles)
1188 % hObject    handle to betamean (see GCBO)
1189 % eventdata  reserved - to be defined in a future version of MATLAB
1190 % handles    empty - handles not created until after all CreateFcns called
1191
1192 % Hint: edit controls usually have a white background on Windows.
1193 %       See ISPC and COMPUTER.
1194 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1195     set(hObject,'BackgroundColor','white');
1196 end
1197
1198
1199
1200 function edit27_Callback(hObject, eventdata, handles)
1201 % hObject    handle to edit27 (see GCBO)
1202 % eventdata  reserved - to be defined in a future version of MATLAB
1203 % handles    structure with handles and user data (see GUIDATA)
1204
1205 % Hints: get(hObject,'String') returns contents of edit27 as text
1206 %        str2double(get(hObject,'String')) returns contents of edit27 as a double
1207
1208
1209 % --- Executes during object creation, after setting all properties.
1210 function edit27_CreateFcn(hObject, eventdata, handles)
1211 % hObject    handle to edit27 (see GCBO)
1212 % eventdata  reserved - to be defined in a future version of MATLAB
1213 % handles    empty - handles not created until after all CreateFcns called
1214
1215 % Hint: edit controls usually have a white background on Windows.
1216 %       See ISPC and COMPUTER.
1217 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1218     set(hObject,'BackgroundColor','white');
1219 end
1220
1221
1222
1223 function betadev_Callback(hObject, eventdata, handles)
1224 % hObject    handle to betadev (see GCBO)
1225 % eventdata  reserved - to be defined in a future version of MATLAB
1226 % handles    structure with handles and user data (see GUIDATA)
1227
1228 % Hints: get(hObject,'String') returns contents of betadev as text
1229 %        str2double(get(hObject,'String')) returns contents of betadev as a double
1230
1231
1232 % --- Executes during object creation, after setting all properties.
1233 function betadev_CreateFcn(hObject, eventdata, handles)
1234 % hObject    handle to betadev (see GCBO)
1235 % eventdata  reserved - to be defined in a future version of MATLAB
1236 % handles    empty - handles not created until after all CreateFcns called
1237
1238 % Hint: edit controls usually have a white background on Windows.
1239 %       See ISPC and COMPUTER.
1240 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1241     set(hObject,'BackgroundColor','white');
1242 end
1243
1244
1245
1246 function edit29_Callback(hObject, eventdata, handles)
1247 % hObject    handle to edit29 (see GCBO)
1248 % eventdata  reserved - to be defined in a future version of MATLAB
1249 % handles    structure with handles and user data (see GUIDATA)
1250
1251 % Hints: get(hObject,'String') returns contents of edit29 as text
1252 %        str2double(get(hObject,'String')) returns contents of edit29 as a double
1253
1254
1255 % --- Executes during object creation, after setting all properties.
1256 function edit29_CreateFcn(hObject, eventdata, handles)
1257 % hObject    handle to edit29 (see GCBO)
1258 % eventdata  reserved - to be defined in a future version of MATLAB
1259 % handles    empty - handles not created until after all CreateFcns called
1260
1261 % Hint: edit controls usually have a white background on Windows.
1262 %       See ISPC and COMPUTER.
1263 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1264     set(hObject,'BackgroundColor','white');
1265 end
1266
1267
1268
1269 function edit30_Callback(hObject, eventdata, handles)
1270 % hObject    handle to edit30 (see GCBO)
1271 % eventdata  reserved - to be defined in a future version of MATLAB
1272 % handles    structure with handles and user data (see GUIDATA)
1273
1274 % Hints: get(hObject,'String') returns contents of edit30 as text
1275 %        str2double(get(hObject,'String')) returns contents of edit30 as a double
1276
1277
1278 % --- Executes during object creation, after setting all properties.
1279 function edit30_CreateFcn(hObject, eventdata, handles)
1280 % hObject    handle to edit30 (see GCBO)
1281 % eventdata  reserved - to be defined in a future version of MATLAB
1282 % handles    empty - handles not created until after all CreateFcns called
1283
1284 % Hint: edit controls usually have a white background on Windows.
1285 %       See ISPC and COMPUTER.
1286 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1287     set(hObject,'BackgroundColor','white');
1288 end
1289
1290
1291
1292 function fcolumntag_Callback(hObject, eventdata, handles)
1293 % hObject    handle to fcolumntag (see GCBO)
1294 % eventdata  reserved - to be defined in a future version of MATLAB
1295 % handles    structure with handles and user data (see GUIDATA)
1296
1297 % Hints: get(hObject,'String') returns contents of fcolumntag as text
1298 %        str2double(get(hObject,'String')) returns contents of fcolumntag as a double
1299
1300
1301 % --- Executes during object creation, after setting all properties.
1302 function fcolumntag_CreateFcn(hObject, eventdata, handles)
1303 % hObject    handle to fcolumntag (see GCBO)
1304 % eventdata  reserved - to be defined in a future version of MATLAB
1305 % handles    empty - handles not created until after all CreateFcns called
1306
1307 % Hint: edit controls usually have a white background on Windows.
1308 %       See ISPC and COMPUTER.
1309 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1310     set(hObject,'BackgroundColor','white');
1311 end
1312
1313
1314
1315 function frowtag_Callback(hObject, eventdata, handles)
1316 % hObject    handle to frowtag (see GCBO)
1317 % eventdata  reserved - to be defined in a future version of MATLAB
1318 % handles    structure with handles and user data (see GUIDATA)
1319
1320 % Hints: get(hObject,'String') returns contents of frowtag as text
1321 %        str2double(get(hObject,'String')) returns contents of frowtag as a double
1322
1323
1324 % --- Executes during object creation, after setting all properties.
1325 function frowtag_CreateFcn(hObject, eventdata, handles)
1326 % hObject    handle to frowtag (see GCBO)
1327 % eventdata  reserved - to be defined in a future version of MATLAB
1328 % handles    empty - handles not created until after all CreateFcns called
1329
1330 % Hint: edit controls usually have a white background on Windows.
1331 %       See ISPC and COMPUTER.
1332 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1333     set(hObject,'BackgroundColor','white');
1334 end
1335
1336
1337
1338 function enter_Callback(hObject, eventdata, handles)
1339 % hObject    handle to enter (see GCBO)
1340 % eventdata  reserved - to be defined in a future version of MATLAB
1341 % handles    structure with handles and user data (see GUIDATA)
1342
1343 % Hints: get(hObject,'String') returns contents of enter as text
1344 %        str2double(get(hObject,'String')) returns contents of enter as a double
1345
1346
1347 % --- Executes during object creation, after setting all properties.
1348 function enter_CreateFcn(hObject, eventdata, handles)
1349 % hObject    handle to enter (see GCBO)
1350 % eventdata  reserved - to be defined in a future version of MATLAB
1351 % handles    empty - handles not created until after all CreateFcns called
1352
1353 % Hint: edit controls usually have a white background on Windows.
1354 %       See ISPC and COMPUTER.
1355 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1356     set(hObject,'BackgroundColor','white');
1357 end
1358
1359
1360 % --- Executes on selection change in popup.
1361 function popup_Callback(hObject, eventdata, handles)
1362 % hObject    handle to popup (see GCBO)
1363 % eventdata  reserved - to be defined in a future version of MATLAB
1364 % handles    structure with handles and user data (see GUIDATA)
1365
1366 % Hints: contents = cellstr(get(hObject,'String')) returns popup contents as cell array
1367 %        contents{get(hObject,'Value')} returns selected item from popup
1368 %
1369 val=get(hObject,'value');
1370 axes(handles.axes2);
1371
1372 switch val
1373
1374     case 1
1375
1376          cla(handles.axes2);
1377          cla(handles.axes1);
1378
1379     case 2
1380
1381         imshow('Random.jpg');
1382         cla(handles.axes1);
1383
1384     case 3
1385
1386          imshow('Square.jpg');
1387          cla(handles.axes1);
1388
1389     case 4
1390
1391         imshow('Hexagonal.jpg');
1392         cla(handles.axes1);
1393
1394     otherwise
1395 end
1396
1397         guidata(hObject,handles);
1398
1399
1400
1401
1402 % --- Executes during object creation, after setting all properties.
1403 function popup_CreateFcn(hObject, eventdata, handles)
1404 % hObject    handle to popup (see GCBO)
1405 % eventdata  reserved - to be defined in a future version of MATLAB
1406 % handles    empty - handles not created until after all CreateFcns called
1407
1408 % Hint: popupmenu controls usually have a white background on Windows.
1409 %       See ISPC and COMPUTER.
1410 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1411     set(hObject,'BackgroundColor','white');
1412 end
1413
1414
1415 % --------------------------------------------------------------------
1416 function Untitled_1_Callback(hObject, eventdata, handles)
1417 % hObject    handle to Untitled_1 (see GCBO)
1418 % eventdata  reserved - to be defined in a future version of MATLAB
1419 % handles    structure with handles and user data (see GUIDATA)
1420
1421
1422
1423 % --- Executes during object creation, after setting all properties.
1424 function axes2_CreateFcn(hObject, eventdata, handles)
1425 % hObject    handle to axes2 (see GCBO)
1426 % eventdata  reserved - to be defined in a future version of MATLAB
1427 % handles    empty - handles not created until after all CreateFcns called
1428
1429 % Hint: place code in OpeningFcn to populate axes2
1430
1431
1432 % end
1433
1434
1435 % --- Executes on button press in pushbutton5.
1436 function pushbutton5_Callback(hObject, eventdata, handles)
1437 % hObject    handle to pushbutton5 (see GCBO)
1438 % eventdata  reserved - to be defined in a future version of MATLAB
1439 % handles    structure with handles and user data (see GUIDATA)
1440 cla(handles.axes1);
1441
1442
1443 % --- Executes on selection change in popup1.
1444 function popup1_Callback(hObject, eventdata, handles)
1445 % hObject    handle to popup1 (see GCBO)
1446 % eventdata  reserved - to be defined in a future version of MATLAB
1447 % handles    structure with handles and user data (see GUIDATA)
1448
1449 % Hints: contents = cellstr(get(hObject,'String')) returns popup1 contents as cell array
1450 %        contents{get(hObject,'Value')} returns selected item from popup1
1451
1452
1453 % --- Executes during object creation, after setting all properties.
1454 function popup1_CreateFcn(hObject, eventdata, handles)
1455 % hObject    handle to popup1 (see GCBO)
1456 % eventdata  reserved - to be defined in a future version of MATLAB
1457 % handles    empty - handles not created until after all CreateFcns called
1458
1459 % Hint: popupmenu controls usually have a white background on Windows.
1460 %       See ISPC and COMPUTER.
1461 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1462     set(hObject,'BackgroundColor','white');
1463 end
1464
1465
1466 % --- Executes when entered data in editable cell(s) in uitable1.
1467 function uitable1_CellEditCallback(hObject, eventdata, handles)
1468 % hObject    handle to uitable1 (see GCBO)
1469 % eventdata  structure with the following fields (see MATLAB.UI.CONTROL.TABLE)
1470 %    Indices: row and column indices of the cell(s) edited
1471 %    PreviousData: previous data for the cell(s) edited
1472 %    EditData: string(s) entered by the user
1473 %    NewData: EditData or its converted form set on the Data property. Empty if Data was not changed
1474 %    Error: error string when failed to convert EditData to appropriate value for Data
1475 % handles    structure with handles and user data (see GUIDATA)
1476
1477
1478 q=eventdata.Indices;
1479 X=get(handles.uitable1,'Data');
1480 if q(1)== 1 || q(2) == 1
1481     X(q(1),q(2)) = cellfun(@(x) ['<html><table border=0 width=400 bgcolor=#FFF000><TR><TD>' x '</TD></TR> </table></html>'], X(q(1),q(2)), 'UniformOutput', false);
1482     set(handles.uitable1,'Data', X);
1483 end
1484
1485