Description of RNetwork_beta_Dis
Home > v08 > helper > RNetwork_beta_Dis.m
RNetwork_beta_Dis
PURPOSE
% Important!!! Before use, check in which direction the rho is calculated. (longitudinal or through-thickness)
SYNOPSIS
function [rho,fiber,VF,NumContacts,betas]=RNetwork_beta_Dis(fibermat,fiberLen,beta_mean,beta_dev,fiberRadius,NumBreak,Rc,rf,RBreakage)
DESCRIPTION
% Important!!!  Before use, check in which direction the rho is calculated. (longitudinal or through-thickness)
% this function is used when the input fibermat is from generated fiber data (not from SEM).
  fibermat data structure: fiber.x, fiber.y,fiber.radius
% load data; scale data.
CROSS-REFERENCE INFORMATION
This function calls:
createnode UNTITLED2 Summary of this function goes here
This function is called by:
SIM_Pressure_IM7_Gutowski % Statistical representation: beta
SIM_beta_Dis_IM7 % Statistical representation: beta
test % Statistical representation: beta
SOURCE CODE
function [rho,fiber,VF,NumContacts,betas]=RNetwork_beta_Dis(fibermat,fiberLen,beta_mean,beta_dev,fiberRadius,NumBreak,Rc,rf,RBreakage)
%% Important!!!  Before use, check in which direction the rho is calculated. (longitudinal or through-thickness)
%% this function is used when the input fibermat is from generated fiber data (not from SEM).
%  fibermat data structure: fiber.x, fiber.y,fiber.radius
%% load data; scale data.
betas=[];
NumContacts=0;
load(fibermat);
% Note: after load(fibermat), fiber.x fiber.y fiber.z are all row vectors.
% Code below change row vectors into column vectors.
fiber.x=fiber.x';
fiber.y=fiber.y';
fiber.radius=fiber.radius';
% Now fiber.x fiber.y and fiber.radius are column vectors.
N=size(fiber.radius,1) %
% !!! be careful, depending on the fiber.radius being a row vector or
% column vector, this command can be size(...,2) for row vector
%or size(...,1) for column vectors.
fiber1= struct('center',[], 'radius',[], 'nodes', []);
aveRad=mean(fiber.radius);
scale=aveRad/fiberRadius;
fiber.x=fiber.x/scale;
fiber.y=fiber.y/scale;
fiber.radius=fiber.radius/scale;
%% get VF and a
minx=min(fiber.x)-fiberRadius;
miny=min(fiber.y)-fiberRadius;
maxx=max(fiber.x)+fiberRadius;
maxy=max(fiber.y)+fiberRadius;
xlen=maxx-minx;
ylen=maxy-miny;
Rsquare=fiber.radius'*fiber.radius;
VF=pi*Rsquare/(xlen*ylen);
a=fiberRadius*(sqrt(pi/(VF))-2); % square packing
% a=fiberRadius*(sqrt(2*pi/(sqrt(3)*VF))-2); % hex packing
%% plot
clf
hold on
viscircles([fiber.x fiber.y],fiber.radius,'LineWidth',2);
% axis([minx maxx miny maxy]);
%% restruct data
for i=1:N
    fiber1(i).center(1)=fiber.x(i);
    fiber1(i).center(2)=fiber.y(i);
    fiber1(i).radius=fiber.radius(i);
end
fiber=fiber1;
%% find fiber neigbbors
perc=2*fiberRadius;
for i=1:N
    fiber(i).nodes=createnode(fiber,i,perc,N);
end
% finish creating neighbors
% find floating fibers that are not connected to any fibers
nullnodes=[];
for i=1:N
    if size(fiber(i).nodes,2)==0
        nullnodes(end+1)=i;
    end
end
while ~isempty(nullnodes)
    fiber(nullnodes(1))=[];
    N1=size(fiber,2)
    for i=1:N1
        fiber(i).nodes=createnode(fiber,i,perc,N1);
    end
    nullnodes=[];
    for i=1:N1
        if size(fiber(i).nodes,2)==0
            nullnodes(end+1)=i;
        end
    end
end
%%
% fiber1=fiber
%%
% load(fibermat);
% N=size(fiber,2);
% radius=zeros(N,1);
% xloc=zeros(N,1);
% yloc=zeros(N,1);
% for i=1:N
%     radius(i)=fiber(i).radius;
% end
% aveRad=mean(radius);
% scale=aveRad/fiberRadius;
% fiber1= struct('center',[], 'radius',[], 'nodes', [],'Contacts',[],'contactNeighbor',[],'pts',{});
% FiberArea=0;
% for i=1:N
%     xloc(i)=fiber(i).center(1)/scale;
%     yloc(i)=fiber(i).center(2)/scale;
%     fiber1(i).center(1)=fiber(i).center(1)/scale;
%     fiber1(i).center(2)=fiber(i).center(2)/scale;
%     fiber1(i).radius=fiber(i).radius/scale;
%     fiber1(i).nodes=fiber(i).nodes;
%     FiberArea=FiberArea+pi*fiber1(i).radius^2;
% end
% fiber=fiber1;
% max_x=max(xloc)-min(xloc);
% max_y=max(yloc)-min(yloc);
% %%
% % Calculate VF and a
% VF=FiberArea/(max_x*max_y);
% a=fiberRadius*(sqrt(2*pi/(sqrt(3)*VF))-2);
% %%
% N=size(fiber,2);
% for i=1:N
%     fiber(i).nodes=createnode(fiber,i,perc,N);
% end
% % finish creating neighbors
% % find floating fibers that are not connected to any fibers
% nullnodes=[];
% for i=1:N
%     if size(fiber(i).nodes,2)==0
%         nullnodes(end+1)=i;
%     end
% end
% while ~isempty(nullnodes)
%     fiber(nullnodes(1))=[];
%     N=size(fiber,2);
%     for i=1:N
%         fiber(i).nodes=createnode(fiber,i,perc,N);
%     end
%     nullnodes=[];
%     for i=1:N
%         if size(fiber(i).nodes,2)==0
%             nullnodes(end+1)=i;
%         end
%     end
% end
% Boundary
BoundX1=[];
BoundX2=[];
BoundY1=[];
BoundY2=[];
BoundZ1=[];
BoundZ2=[];
N=size(fiber,2);
% BoundZ1=[1:N];
% BoundZ2=[1:N];
for i=1:N
    if (fiber(i).center(1)<=minx+2*fiber(i).radius)
%     if (fiber(i).center(1)<=1.0*(2*a+fiber(i).radius))
        %fiber1(i).nodes=[fiber1(i).nodes 0]; %left boundary
        BoundX1(end+1)=i;
    end
    if (fiber(i).center(1)>=maxx-2*fiber(i).radius)
        %fiber1(i).nodes=[fiber1(i).nodes N+1]; % right boundary
        BoundX2(end+1)=i;
    end
    if (fiber(i).center(2)<=miny+2*fiber(i).radius)
        %fiber1(i).nodes=[fiber1(i).nodes 0]; %left boundary
        BoundY1(end+1)=i;
    end
    if (fiber(i).center(2)>=maxy-2*fiber(i).radius)
        %fiber1(i).nodes=[fiber1(i).nodes N+1]; % right boundary
        BoundY2(end+1)=i;
    end
end
% %% Plot
% for xbound=1:size(BoundX1,2)
%     node=BoundX1(xbound);
%     plot([minx-fiberRadius fiber(node).center(1)],[fiber(node).center(2) fiber(node).center(2)],'r*-','LineWidth',3);
% end
% for xbound=1:size(BoundX2,2)
%     node=BoundX2(xbound);
%     plot([maxx+fiberRadius fiber(node).center(1)],[fiber(node).center(2) fiber(node).center(2)],'g*-','LineWidth',3);
% end
%%
fiber(1).contactNeighbor=[];
fiber(1).Contacts=[];
fiber(1).pts=[];
N=size(fiber,2);
% beta=abs(normrnd(beta_mean,beta_dev));
% ContactLen=beta*a;
% NumSections=floor(fiberLen/ContactLen);
L=fiberLen; % fiber length in m
for i=1:N
    NumNeighbor=size(fiber(i).nodes,2);
    allcontact=[];
    beta=abs(normrnd(beta_mean,beta_dev));
    betas(end+1)=beta;
    ContactLen=beta*a;
    for j=1:NumNeighbor    %neighboring fibers of fiber i
        contact=[];
        NeighborNode=fiber(i).nodes(j);
        if NeighborNode>i
            startpt=rand*ContactLen;
            endpt=startpt;
            while endpt<=L
                contact(end+1)=endpt;
                endpt=endpt+ContactLen;
            end
%             NumContacts=floor(L/ContactLen);
%             previous=rand*ContactLen;
%             contact(1)=previous;
%             if NumContacts>=2
%                 for m=2:NumContacts
%                     contact(m)=previous+ContactLen; %contact(m)=previous+ContactLen*normrnd(0,0.01);
%                     previous=contact(m);
%                 end
%             end
            sizeb=size(contact,2);
            NumContacts=sizeb;
            allcontact=[allcontact,contact];  % all contact points on fiber i
            fiber(i).contactNeighbor(end+1:end+sizeb)=NeighborNode;  %
            fiber(NeighborNode).Contacts(end+1:end+sizeb)=contact;
            fiber(NeighborNode).contactNeighbor(end+1:end+sizeb)=i;
        end
    end
    allcontact=[fiber(i).Contacts,allcontact];  % all contact pts including those inherited from previous fibers (NeighborNode<i)
    allcontact1=unique(allcontact);
    fiber(i).Contacts=allcontact1;
    if size(allcontact1,1)~=0
        for m=1:size(allcontact1,2)   % find contact neighbors for each contact point.
            loc=find(allcontact==allcontact1(m));
            fiber(i).pts{m}=fiber(i).contactNeighbor(loc);
        end
    end
end    %all fibers built
%             end
%             if curr_node==N+1
%                  plot([fiber(i).center(1) max_x],[fiber(i).center(2) fiber(i).center(2)],'r*-','LineWidth',3);
%
%             end
% fiber.BoundX1=BoundX1;
% fiber.BoundX2=BoundX2;
% fiber.BoundY1=BoundY1;
% fiber.BoundY2=BoundY2;
% finish finding BC nodes
%%% consider fiber breakage
if NumBreak~=0
for i=1:N
    iNumBreak=randi(NumBreak,1);
    ContactVec=fiber(i).Contacts;
    BreakPts=min(ContactVec)+(max(ContactVec)-min(ContactVec))*rand(iNumBreak,1);
    BreakPts=unique(BreakPts);
    locBP=zeros(iNumBreak,1);
    for NumBP=1:iNumBreak
        locBP(NumBP,1)=find(ContactVec>BreakPts(NumBP),1);
    end
    fiber(i).Breakage=locBP;
end
end
%%
R=cell(N,N);
for i=1:N
    for j=1:N
        NumRows=size(fiber(i).Contacts,2);
        NumColumns=size(fiber(j).Contacts,2);
        R{i,j}=zeros(NumRows,NumColumns);
    end
end
G=R;       % GV=K
% finish initializing
%%% build fibers resistors and contact resistors
for i=1:N
    NumContacts=size(fiber(i).Contacts,2); % note Contacts is a row vector
    ContactVec=fiber(i).Contacts;
    % R matrix
    % R for fiber sections
    for j=1:NumContacts-1
         RLen=fiber(i).Contacts(j+1)-fiber(i).Contacts(j);
            A=pi*fiber(i).radius^2;
            R{i,i}(j,j+1)=rf*RLen/A;
            R{i,i}(j+1,j)=rf*RLen/A;    % resistance between two sections on one fiber
            G{i,i}(j,j+1)=-1/R{i,i}(j,j+1);% G(i,j)=-1/R
            G{i,i}(j+1,j)=-1/R{i,i}(j+1,j);% G(i,j)=-1/R
    end
     %%%% change R into a large value where fiber breakage happens.
     if NumBreak
     for NumBP=1:size(fiber(i).Breakage,1)
         BreakLoc=fiber(i).Breakage(NumBP);
         R{i,i}(BreakLoc-1,BreakLoc)=RBreakage;
         R{i,i}(BreakLoc,BreakLoc-1)=RBreakage;
         G{i,i}(BreakLoc-1,BreakLoc)=-1/RBreakage;% G(i,j)=-1/R
         G{i,i}(BreakLoc,BreakLoc-1)=-1/RBreakage;% G(i,j)=-1/R
     end
     end
    % R for contacts
    for j=1:NumContacts
                  num_pt=size(fiber(i).pts{j},2);
            for k=1:num_pt
                neighbor_pt=fiber(i).pts{j}(k);
                ind=find(fiber(neighbor_pt).Contacts==ContactVec(j));
                R{i,neighbor_pt}(j,ind)=Rc; %Contact Resistance between fibers
                G{i,neighbor_pt}(j,ind)=-1/Rc;
            end
            fiberi=R{i,i}(j,:);
            fiberi=fiberi(fiberi~=0);
            sum=0;
            for m=1:size(fiberi,2)
                sum=sum+1/fiberi(m);
            end
            Gfiberi=sum;
            sum1=0;
            for n=1:num_pt
                neighbor_pt=fiber(i).pts{j}(n);
                ind=find(fiber(neighbor_pt).Contacts==ContactVec(j));
                sum1=sum1+1/R{i,neighbor_pt}(j,ind);
            end
            Gfiberj=sum1;
            G{i,i}(j,j)=Gfiberi+Gfiberj;
    end
end
%%%% change R into a large value where fiber breakage happens.
% change R into a matrix to apply Kirchoff's Law.
%% Apply longitudinal BC
% BC1=5;
% BC2=0;
% for i=1:N
%     K{i,1}=zeros(size(fiber(i).Contacts,2),1);
% end
% for i=1:N %size(BoundZ1,2)
%     Ki=zeros(size(fiber(i).Contacts,2),1);
%     Ki(1)=BC1;
%     Ki(end)=BC2; %% boundary condition
%     K{i,1}=Ki;
% end
% for i=1:N
%     %Ncontacts=size(fiber(i).Contacts,2);
%     for j=1:N
%         G{i,j}(1,:)=0;
%         G{i,j}(end,:)=0;
%     end
% end
% for i=1:N
%     G{i,i}(1,1)=1;
%     G{i,i}(end,end)=1;
% end
% %% Solve GV=K
% K=cell2mat(K);
% %R=cell2mat(R);
% G=cell2mat(G);
% Voltage2=G\K;
% Mrow=zeros(N,1);
% for i=1:N
%     Mrow(i)=size(fiber(i).Contacts,2);
% end
% Voltage3=mat2cell(Voltage2,Mrow);
% %% calculate longitudinal currents
% totcur1=0;
% totcur2=0;
% cur1=[];
% cur2=[];
% for i=1:N
%     Res1=R{i,i}(1,2);
%     Vdiff1=BC1-Voltage3{i}(2);
%     cur1(end+1)=Vdiff1/Res1;
%     % injecting current
%     Res2=R{i,i}(end-1,end);
%     Vdiff2=Voltage3{i}(end)-BC2;
%     cur2(end+1)=Vdiff2/Res2;
%     % outgoing current
%     totcur1=totcur1+cur1(end);
%     totcur2=totcur2+cur2(end);
% end
% Res=(BC1-BC2)/totcur1;
% rho=xlen*Res*ylen/fiberLen;
% % End longitudinal calculations
%% Apply through-thickness BC
rous=[];
K=cell(N,1);
BC1=5;
BC2=0;
for i=1:N
    K{i,1}=zeros(size(fiber(i).Contacts,2),1);
end
% K=zeros(size(R,1),1)
for i=1:size(BoundX1,2)
    K{BoundX1(i),1}=BC1*ones(size(fiber(BoundX1(i)).Contacts,2),1);%% boundary condition
    fiberlabel=BoundX1(i);
    for j=1:N
        if j==fiberlabel
            G{fiberlabel,j}=eye(size(fiber(fiberlabel).Contacts,2));
        else
            G{fiberlabel,j}=zeros(size(fiber(fiberlabel).Contacts,2),size(fiber(j).Contacts,2));
        end
    end
    %     for j=1:size(fiber(BoundX1(i)).Contacts,1)
    %     G{fiberlabel,fiberlabel}(j,j)=1;
    %     end
end
for i=1:size(BoundX2,2)
    K{BoundX2(i),1}=BC2*ones(size(fiber(BoundX2(i)).Contacts,2),1);
    fiberlabel=BoundX2(i);
    for j=1:N
        if j==fiberlabel
            G{fiberlabel,j}=eye(size(fiber(fiberlabel).Contacts,2));
        else
            G{fiberlabel,j}=zeros(size(fiber(fiberlabel).Contacts,2),size(fiber(j).Contacts,2));
        end
    end
    %     for j=1:size(fiber(BoundX2(i)).Contacts,1)
    %     G{fiberlabel,fiberlabel}(j,j)=1;
    %     end
end
%% Solve GV=K
K=cell2mat(K);
G=cell2mat(G);
Voltage2=G\K;
Mrow=zeros(N,1);
for i=1:N
    Mrow(i)=size(fiber(i).Contacts,2);
end
Voltage3=mat2cell(Voltage2,Mrow);
%% calculate through-thickness currents
% 1. outgoing currents
totcur1=0;
totcur2=0;
cur1=[];
cur2=[];
for i=1:size(BoundX1,2)
    fiberlabel=BoundX1(i);
    num_pt=size(fiber(fiberlabel).Contacts,2);
    for j=1:num_pt
        %Vdiff=BC1-Voltage3{j}
        num_contact=size(fiber(fiberlabel).pts{j},2);
        for k=1:num_contact
            neighbor_fiber=fiber(fiberlabel).pts{j}(k);
            neighbor_pt=find(fiber(neighbor_fiber).Contacts==fiber(fiberlabel).Contacts(j));
            Vdiff=BC1-Voltage3{neighbor_fiber}(neighbor_pt);
            Res=R{fiberlabel,neighbor_fiber}(j,neighbor_pt);
            cur1(end+1)=Vdiff/Res;
            totcur1=totcur1+cur1(end);
        end
    end
end
for i=1:size(BoundX2,2)
    fiberlabel=BoundX2(i);
    num_pt=size(fiber(fiberlabel).Contacts,2);
    for j=1:num_pt
        %Vdiff=BC1-Voltage3{j}
        num_contact=size(fiber(fiberlabel).pts{j},2);
        for k=1:num_contact
            neighbor_fiber=fiber(fiberlabel).pts{j}(k);
            neighbor_pt=find(fiber(neighbor_fiber).Contacts==fiber(fiberlabel).Contacts(j));
            Vdiff=Voltage3{neighbor_fiber}(neighbor_pt)-BC2;
            Res=R{fiberlabel,neighbor_fiber}(j,neighbor_pt);
            cur2(end+1)=Vdiff/Res;
            totcur2=totcur2+cur2(end);
        end
    end
end
totcur1;
totcur2;
Res=(BC1-BC2)/totcur1;
rho=fiberLen*Res*ylen/xlen;
% % save ResData