Description of runLTspice
Home > v08 > helper > runLTspice.m
runLTspice
PURPOSE
% Run LTSpice and reduce data
SYNOPSIS
function [Vin,Is,data1] = runLTspice(NetList)
DESCRIPTION
% Run LTSpice and reduce data
CROSS-REFERENCE INFORMATION
This function calls:
ReadRAW function [LineContent,NVariables, NValues] = ReadRAW(filepath)
ReadRAW function [LineContent,NVariables, NValues] = ReadRAW(filepath)
This function is called by:
Function
Laminate1
SOURCE CODE
function [Vin,Is,data1] = runLTspice(NetList)
%% Run LTSpice and reduce data
NetListID= strcat(NetList,'.cir');
SystemCMD = ['scad3.exe',' -b -ascii ',NetListID];
p=system(SystemCMD);
% waitfor(p);
filepath = [NetList,'.raw'];
[Vin,Is,data1]=ReadRAW(filepath);
% current_out = str2num(getLastLine(filepath))
% Resistance = abs(1/current_out)
% switch Direction
%     case 1
%         Rho_x = Resistance*Spec_Th*Spec_Wid/Spec_Len
%         Rho=Rho_x;
%     case 2
%         Rho_y = Resistance*Spec_Th*Spec_Len/Spec_Wid
%         Rho=Rho_y;
%     case 3
%         Rho_z = Resistance*Spec_Len*Spec_Wid/Spec_Th
%         Rho=Rho_z;
% end
%% write results to txt file
% ResultID= [NetList,'-Results.txt'];
% fid=fopen(ResultID,'a'); % wt means overwrite existing file named with NetListID
% % To open a file in text mode, append 't' to the permission string,
% fprintf(fid,'%d %f %f %f %f %f %f \n',Direction,Resistance,Rho,Spec_Len,Spec_Wid,Spec_Th,Connectivity);
% ST = fclose(fid);