Description of RvsPressure
Home > v08 > helper > RvsPressure.m
RvsPressure
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
ContactForce % Force at each contact point.
ContactR % contact resistance
ContactForce % Force at each contact point.
ContactR % contact resistance
This function is called by:
SOURCE CODE
VF=0.55
beta=350
fiberRadius=3.5e-6
E=276e9
rf=1.8e-5
Pressure=8e5
Fc = ContactForce(VF,beta,Pressure,fiberRadius);
Rc = ContactR(fiberRadius,Fc,E,rf)