Description of Sensitivity_Study_Taguchi
Home > v08 > helper > Sensitivity_Study_Taguchi.m
Sensitivity_Study_Taguchi
PURPOSE
% Sensitivity study of 3D Resistor Network MOdel using Taguchi Technique
SYNOPSIS
This is a script file.
DESCRIPTION
% Sensitivity study of 3D Resistor Network MOdel using Taguchi Technique
% by Hong Yu, hongy@udel.edu  April 2014
CROSS-REFERENCE INFORMATION
This function calls:
ContactForce % Force at each contact point.
ContactR % contact resistance
ContactForce % Force at each contact point.
ContactR % contact resistance
Func_RNetwork_Z % this function is used when the input fibermat is from generated fiber data (not from SEM).
This function is called by:
SOURCE CODE
%% Sensitivity study of 3D Resistor Network MOdel using Taguchi Technique
%% by Hong Yu, hongy@udel.edu  April 2014
Resfid1='Sensitivity_Diameter.txt' % Results file name
fid=fopen(Resfid1,'a');
fprintf(fid,'Sensitivity Study _ Diameter \n'); % print simulation title
Taguchi=[...
    1 1 1 1 1;...
    1 2 2 2 2;...
    1 3 3 3 3;...
    1 4 4 4 4;...
    2 1 2 3 4;...
    2 2 1 4 3;...
    2 3 4 1 2;...
    2 4 3 2 1;...
    3 1 3 4 2;...
    3 2 4 3 1;...
    3 3 1 2 4;...
    3 4 2 1 3;...
    4 1 4 2 3;...
    4 2 3 1 4;...
    4 3 2 4 1;...
    4 4 1 3 2;] % Tqguchi Matrix, 5 parameters at 4 levels.
Taguchi=[...
    1 2 2 3 3;...
    2 2 2 3 3;...
%     3 2 2 3 3;...
%     4 2 2 3 3;...
%     5 2 2 3 3;...
%     6 2 2 3 3;...
    3 2 2 3 3;] % Tqguchi Matrix, 5 parameters at 4 levels.
FDs=1e-6*[8.5 9 9.5]; % fiber diameter
PPs=1e5*[2 4 6 8]; % processing pressure
FWs=[100 300 500 700]; % fiber waviness
FRs=1e-5*[1.0 1.4 1.8 2.0]; % fiber resistivity
VFs=[0.45 0.5 0.55 0.6]; % volume fraction
fiberLen=1.5e-3; % specimen length
E=231e9; %fiber modulus
specimen=1;
NumBreak=0;
RBreakage=1e10;
for i=1:size(Taguchi,1)
    clf;
    fiberRadius=0.5*FDs(Taguchi(i,1));
    Pressure=PPs(Taguchi(i,2));
    beta=FWs(Taguchi(i,3));
    rf=FRs(Taguchi(i,4));
    VF=VFs(Taguchi(i,5));
    Fc = ContactForce(VF,beta,Pressure,fiberRadius);
    Rc = ContactR(fiberRadius,Fc,E,rf);
    fibermat=strcat('vf_',num2str(VF),'_spec',num2str(specimen),'.mat');
    [rho,fiber,VF,NumContacts]=Func_RNetwork_Z(fibermat,fiberLen,beta,fiberRadius,NumBreak,Rc,rf,RBreakage)
    %[rho,fiber,VF,NumContacts]=Func_RNetwork1(fibermat,fiberLen,beta,fiberRadius,NumBreak,Rc,rf,RBreakage);
fid=fopen(Resfid1,'a');
fprintf(fid,...
    '%d %f %1.8f %f %f %f %f %f %d\n',...
    i,rho,fiberRadius,Pressure,beta,rf,VF,Rc,NumContacts);
%     '%f %f %f %1.4f %f %2.10f %d %f\n',...
%     Pressure,rho,Rc,VF,fiberLen,fiberRadius,NumContacts,beta_mean);
end