Description of showTree
Home > v08 > helper > showTree.m
showTree
PURPOSE
[mtree,treecontainer] = uitree('v0', 'Root',root);
SYNOPSIS
function showTree(allHandles,allData) %materialBrowserLayout
DESCRIPTION
[mtree,treecontainer] = uitree('v0', 'Root',root);
CROSS-REFERENCE INFORMATION
This function calls:
treeNode_callback
set TEMPLATE/SET Edit data stored in a Template object
This function is called by:
addFiber_callback
addLamina_callback
addLaminate_callback
removeFiber_callback
removeLamina_callback
CFRP_GUI_v08 GUI for 3D resistor network
SOURCE CODE
 function showTree(allHandles,allData) %materialBrowserLayout
        %[mtree,treecontainer] = uitree('v0', 'Root',root);
        mtree=allData.mtree
        treecontainer = allData.treeContainer
        set(treecontainer,'Parent',allHandles.treePanel);
        set(mtree, 'NodeSelectedCallback', {@treeNode_callback,allHandles,allData})
        root=mtree.Root;
        mtree.expand(root);
        %mtree.expand(FiberNode);
    end