Description of SIM_Comparison_R_VF_AS4
Home > v08 > helper > SIM_Comparison_R_VF_AS4.m
SIM_Comparison_R_VF_AS4
PURPOSE
% convergence test: Rz; Square Packing; IM7
SYNOPSIS
This is a script file.
DESCRIPTION
% convergence test: Rz; Square Packing; IM7
% 3D Resistor Network Modle by Hong Yu
% copyright: Hong Yu,hongy@udel.edu 2013
CROSS-REFERENCE INFORMATION
This function calls:
ContactForce_Exp
ContactR % contact resistance
ContactForce_Exp
ContactR % contact resistance
Func_RNetwork_Z % this function is used when the input fibermat is from generated fiber data (not from SEM).
This function is called by:
SOURCE CODE
%% convergence test: Rz; Square Packing; IM7
%% 3D Resistor Network Modle by Hong Yu
%% copyright: Hong Yu,hongy@udel.edu 2013
Resfid1='SIM_Comparison_R-VF.txt'; % Results file name
fid=fopen(Resfid1,'a');
fprintf(fid,'R-VF AS4 \n');
VFs=[0.4 0.45 0.5 0.55 0.6];
rhos=[];
for i=1:length(VFs)
    clf
    VF=VFs(i);
%clear all
%Resfid1='SIM_Convergence_IM7.txt'; % Results file name
%% Input parameters
%% fiber property
fiberRadius=3.5e-6; % radius of fiber, 2.6um for IM7; 3.5 for AS4
rf=1.7e-5;
E=231e9; % carbon fiber modulus. IM7: 276 GPa
%% processing
beta_mean=350;
beta_dev=0;
%Pressure=8e5; % Processing pressure: 8 bar
%% model configuration parameter
%perc=1.5*fiberRadius;
%ContactsPerFiber=5;
NumBreak=0;
RBreakage=1e10;
fiberLen=2e-3;
V0=0.42;
Va=0.8;
beta=350;
% frow=10;
% fcolumn=10;
%% model
%fibermat='vf_0.55_spec1.mat';
[Fc,Pressure] = ContactForce_Exp(V0,Va,VF,beta,E,fiberRadius);
%Fc = ContactForce(VF,beta_mean,Pressure,fiberRadius);
Rc = ContactR(fiberRadius,Fc,E,rf);
% % 1. Square packing; uncomment to run simulation.
% VF=0.55;
% SquarePacking(frow,fcolumn,VF,fiberRadius);
% fibermat='PerfectFiber.mat';
% % 2. Hexagonal packing; uncomment to run simulation.
% VF=0.57;
% HexPacking(frow,fcolumn,VF,fiberRadius);
% fibermat='PerfectFiber.mat';
%3. Random Packing
fibermat='vf_0.6_spec2.mat';
specimen=1;
fibermat=strcat('vf_',num2str(VF),'_spec',num2str(specimen),'.mat');
% %4. From image; uncomment to run simulation.
% imgname='laser4.png';
% xmin_ratio=0.3;xmax_ratio=0.7;ymin_ratio=0.2;ymax_ratio=0.7;
% readIMG(imgname,xmin_ratio,xmax_ratio,ymin_ratio,ymax_ratio);
% fibermat='fiberSEM2.mat';
% calculate rho
[rho,fiber,VF,NumContacts]=Func_RNetwork_Z(fibermat,fiberLen,beta_mean,fiberRadius,NumBreak,Rc,rf,RBreakage);
rhos(end+1)=rho;
fid=fopen(Resfid1,'a');
fprintf(fid,...
    '%f %f %f %1.4f %f %2.10f %d %f\n',...
    Pressure,rho,Rc,VF,fiberLen,fiberRadius,NumContacts,beta_mean);
end
plot(rhos,VFs);
               %             HexPacking(frow,fcolumn,VF0,fiberRadius);