Description of SIM_Convergence_Square_IM7[Conflict 1]
Home > v08 > helper > SIM_Convergence_Square_IM7[Conflict 1].m
SIM_Convergence_Square_IM7[Conflict 1]
PURPOSE
% convergence test: Rz; Square Packing; IM7
SYNOPSIS
This is a script file.
DESCRIPTION
% convergence test: Rz; Square Packing; IM7
% 3D Resistor Network Modle by Hong Yu
% copyright: Hong Yu,hongy@udel.edu 2013
CROSS-REFERENCE INFORMATION
This function calls:
ContactForce % Force at each contact point.
ContactR % contact resistance
ContactForce % Force at each contact point.
ContactR % contact resistance
Func_RNetwork_Z % this function is used when the input fibermat is from generated fiber data (not from SEM).
HexPacking % square packing
This function is called by:
SOURCE CODE
%% convergence test: Rz; Square Packing; IM7
%% 3D Resistor Network Modle by Hong Yu
%% copyright: Hong Yu,hongy@udel.edu 2013
Resfid1='SIM_Convergence_Comparison.txt' % Results file name
fid=fopen(Resfid1,'a');
fprintf(fid,'average a; hex; fiberLen=2mm  \n');
tic
for Nsim=1:1
%clear all
clf
%Resfid1='SIM_Convergence_IM7.txt'; % Results file name
%% Input parameters
%% fiber property
fiberRadius=2.6e-6; % radius of fiber, 2.6um for IM7; 3.5 for AS4
rf=1.8e-5;
E=276e9; % carbon fiber modulus. IM7: 276 GPa
%% processing
beta_mean=350;
beta=beta_mean;
beta_dev=0;
Pressure=8e5; % Processing pressure: 8 bar
%% model configuration parameter
%perc=1.5*fiberRadius;
%ContactsPerFiber=5;
NumBreak=0;
RBreakage=1e10;
%ContactsPerFiber=2;
fiberLen=2e-3;
VF=0.6;
frow=10;
fcolumn=10;
%% model
%fibermat='vf_0.55_spec1.mat';
Fc = ContactForce(VF,beta_mean,Pressure,fiberRadius);
Rc = ContactR(fiberRadius,Fc,E,rf);
% % 1. Square packing; uncomment to run simulation.
% VF=0.525;
% SquarePacking(frow,fcolumn,VF,fiberRadius);
% fibermat='PerfectFiber.mat';
% 2. Hexagonal packing; uncomment to run simulation.
VF=0.57;
HexPacking(frow,fcolumn,VF,fiberRadius);
fibermat='PerfectFiber.mat';
% %3. Random Packing
% fibermat='vf_0.6_spec3.mat';
%
% %4. From image; uncomment to run simulation.
% imgname='laser4.png';
% xmin_ratio=0.0;xmax_ratio=1;ymin_ratio=0.0;ymax_ratio=1;
% readIMG(imgname,xmin_ratio,xmax_ratio,ymin_ratio,ymax_ratio);
% fibermat='fiberSEM2.mat';
% calculate rho
[rho,fiber,VF,NumContacts]=Func_RNetwork_Z(fibermat,fiberLen,beta,fiberRadius,NumBreak,Rc,rf,RBreakage)
%[rho,fiber,VF,NumContacts,fiberLen]=Func_RNetwork_Z(fibermat,ContactsPerFiber,beta,fiberRadius,NumBreak,Rc,rf,RBreakage);
%[rho,fiber,VF,NumContacts]=Func_RNetwork_Z(fibermat,fiberLen,beta_mean,fiberRadius,NumBreak,Rc,rf,RBreakage);
%% running time
time=toc
%% writing output
fid=fopen(Resfid1,'a');
fprintf(fid,...
    '%f %f %f %1.4f %f %2.10f %d %f %f\n',...
    Pressure,rho,Rc,VF,fiberLen,fiberRadius,NumContacts,beta_mean,time);
end
               %             HexPacking(frow,fcolumn,VF0,fiberRadius);