Description of SIM_Pressure_IM7_Gutowski
Home > v08 > helper > SIM_Pressure_IM7_Gutowski.m
SIM_Pressure_IM7_Gutowski
PURPOSE
% Statistical representation: beta
SYNOPSIS
This is a script file.
DESCRIPTION
% Statistical representation: beta
% 3D Resistor Network Modle by Hong Yu
% copyright: Hong Yu,hongy@udel.edu 2013
% IM7 random fiber
CROSS-REFERENCE INFORMATION
This function calls:
ContactForce_Exp
ContactR % contact resistance
ContactForce_Exp
ContactR % contact resistance
RNetwork_beta_Dis % Important!!! Before use, check in which direction the rho is calculated. (longitudinal or through-thickness)
This function is called by:
SOURCE CODE
%% Statistical representation: beta
%% 3D Resistor Network Modle by Hong Yu
%% copyright: Hong Yu,hongy@udel.edu 2013
%% IM7 random fiber
Resfid1='Pressure_IM7_ExpPressure.txt' % Results file name
fid=fopen(Resfid1,'a');
fprintf(fid,'Experimental Pressure VF relation with Gutowski eqn \n');
vfs=[0.4 0.45 0.5 0.55 0.6]; %volume fractions
%% Input parameters
%% fiber property
fiberRadius=3.5e-6; % radius of fiber, 2.6um for IM7; 3.5 for AS4
rf=1.6e-5;
E=238e9; % carbon fiber modulus. IM7: 276 GPa
%% processing
beta_mean=378*3;
beta=beta_mean;
beta_dev=0;
%Pressure=0.5e5; % Processing pressure: 8 bar
V0=0.4;
Va=0.85;
%% model configuration parameter
perc=1.5*fiberRadius;
%ContactsPerFiber=5;
NumBreak=0;
RBreakage=1e10;
fiberLen=2.5e-3;
for vfi=1:length(vfs)
    vf=vfs(vfi);
    for specimen=1:1
        fibermat=strcat('vf_',num2str(vf),'_spec',num2str(specimen),'.mat');
%         Fc = ContactForce_Exp(V0,Va,vf,beta,E);
        [Fc,Pressure] = ContactForce_Exp(V0,Va,vf,beta,E,fiberRadius);
        Rc = ContactR(fiberRadius,Fc,E,rf);
        [rho,fiber,VF,NumContacts,betas]=RNetwork_beta_Dis(fibermat,fiberLen,beta_mean,beta_dev,fiberRadius,NumBreak,Rc,rf,RBreakage);
        fid=fopen(Resfid1,'a');
        fprintf(fid,...
            '%f %f %f %1.4f %f %2.10f %d %f\n',...
            Pressure,rho,Rc,VF,fiberLen,fiberRadius,NumContacts,beta_mean);
    end
end
% for Nsim=1:8
% clear all
% clf
% Resfid1='SIM_Pressure_IM7.txt'; % Results file name
% %% Input parameters
% %% fiber property
% fiberRadius=2.6e-6; % radius of fiber, 2.6um for IM7; 3.5 for AS4
% rf=1.8e-5;
% E=276e9; % carbon fiber modulus. IM7: 276 GPa
% %% processing
% beta_mean=350;
% beta_dev=0;
% Pressure=0.5e5; % Processing pressure: 8 bar
% V0=0.3;
% Va=0.8;
% %% model configuration parameter
% perc=1.5*fiberRadius;
% %ContactsPerFiber=5;
% NumBreak=0;
% RBreakage=1e10;
% fiberLen=1e-3;
% VF=0.55
% %% model
% fibermat='vf_0.55_spec1.mat';
% % Fc = ContactForce(VF,beta_mean,Pressure,fiberRadius);
% Fc = ContactForce_Exp(V0,Va,VF,beta,E)
% Rc = ContactR(fiberRadius,Fc,E,rf);
% [rho,fiber,VF,NumContacts,betas]=RNetwork_beta_Dis(fibermat,fiberLen,beta_mean,beta_dev,fiberRadius,NumBreak,Rc,rf,RBreakage);
% fid=fopen(Resfid1,'a');
% fprintf(fid,...
%     '%f %f %f %1.4f %f %2.10f %d %f\n',...
%     Pressure,rho,Rc,VF,fiberLen,fiberRadius,NumContacts,beta_mean);
% end
%         %     Resfid1=strcat('Res','vf_',num2str(vf),'_spec',num2str(specimen),'.txt');
%         %     Resfid2=strcat('Res_ave','vf_',num2str(vf),'_spec',num2str(specimen),'.txt');
%
%
% %tic
% %% input parameters
% % Resfid1='Stat_beta_IM7.txt' % Results file name
% % %Resfid2='CompareModels_ave.txt'
% % fid1=fopen(Resfid1,'a')
% % fprintf(fid1,'%s \n','Stat_beta_IM7')
% % % fid2=fopen(Resfid2,'a')
% % % fprintf(fid2,'%s \n','IM7-Random-a_ave')
% %
% % % Resfid1='Res_IM7_random_perc.txt' % Results file name
% % % Resfid2='Res_IM7_random_perc_ave.txt'
% % % Resfid3='DistanceDistribution.txt'
% % fiberRadius=2.6e-6; % radius of fiber, 2.6um for IM7; 3.5 for AS4
% % % fiberLen=2e-3;
% % perc=1.5*fiberRadius;
% % %beta=350;
% % NumBreak=0;
% % % Rc=36;
% % rf=1.8e-5;
% % RBreakage=1e10;
% % ContactsPerFiber=5;
% % Pressure=0.8e6; % Processing pressure: 8 bar
% % E=276e9; % carbon fiber modulus. IM7: 276 GPa
% %% input simulated fibers
% %vfmatrix=[0.55]; %volume fractions
% % tempsimsize=size(vfmatrix);
% % simsize=tempsimsize(2);
% simsize=size(vfmatrix,2);
% %final_result=zeros(10*simsize,2); %first column is vf second column is resistance
% %average_result=zeros(simsize,3);
% iteration=0;
%
%
%     Fc = ContactForce(VF,beta,Pressure,fiberRadius);
% Rc = ContactR(fiberRadius,Fc,E,rf);
% % fid=fopen(Resfid1,'a');
% % fprintf(fid,'\n');
% % fid=fopen(Resfid2,'a');
% % fprintf(fid,'\n');
% % tot_iter=simsize*10
% for simnumber=1:simsize
% %     fid=fopen(Resfid3,'a');
% %     fprintf(fid,'\n')
% %     fid=fopen(Resfid1,'a');
% %     fprintf(fid,'\n')
%
%     rhos=[];
%     Res_dist_all=[];
%     for specimen=1:1
%         vf=vfmatrix(simnumber);
% %         Rc=360/vf;
% %         Rc=(0.6-vf)*15+0.001;
% Rc=1e-6;
% %         Rc=0.02/(vf-0.4+0.02);
%         fibermat=strcat('vf_',num2str(vf),'_spec',num2str(specimen),'.mat');
%
% %         [rho0,fiber,VF,NumContacts,SampleLen,Res_dist]=RNetwork_Random(fibermat,ContactsPerFiber,beta,fiberRadius,perc,NumBreak,Rc,rf,RBreakage);
%         [rho0,fiber,VF,NumContacts,SampleLen,a_value]=RNetwork_Random3(fibermat,ContactsPerFiber,beta,fiberRadius,perc,NumBreak,Rc,rf,RBreakage);
%         rho0
% %         ave_a=mean(Res_dist);
% %         [rho0,fiber,VF,NumContacts]=Func_RNetwork1(fibermat,fiberLen,beta,fiberRadius,perc,NumBreak,Rc,rf,RBreakage);
% %         rhos(specimen)=rho0;
%         rhos(end+1)=rho0;
% %         Res_dist_all=[Res_dist_all Res_dist];
%         iteration=iteration+1;
% %         progress=['progress:' num2str(iteration/tot_iter*100) ' %'];
% %         disp(progress)
% %         fid=fopen(Resfid1,'a');
% %         time1=toc;
% %         fprintf(fid,'%f %d %f %2.10f %d %f %f %d %f %f\n',VF,specimen,SampleLen,fiberRadius,NumContacts,ave_a,Rc,beta,rho0,time1);
% %         fprintf(fid,...
% %             '%1.4f %d %f %2.10f %d %f %f %f\n',...
% %             VF,specimen,fiberLen,fiberRadius,NumContacts,beta,rho0,time1);
%         %     Resfid1=strcat('Res','vf_',num2str(vf),'_spec',num2str(specimen),'.txt');
%         %     Resfid2=strcat('Res_ave','vf_',num2str(vf),'_spec',num2str(specimen),'.txt');
%     end
%     aveRho=mean(rhos);
% %     fid=fopen(Resfid1,'a');
% %     time2=toc;
% %     fprintf(fid,'%f %f %2.10f %d %f %f %d %f %f\n',VF,SampleLen,fiberRadius,NumContacts,ave_a,Rc,beta,aveRho,time2);
% %     fid=fopen(Resfid3,'a')
% %     dlmwrite(Resfid3,Res_dist_all,'-append')
% %     fprintf(fid,'%1.4f %f %2.10f %d %f %f %f \n',...
% %                   vf,fiberLen,fiberRadius,NumContacts,beta,aveRho,time2);
% end