Description of SIM_Compare_Combine_GUI_table
Home > v08 > helper > SIM_Compare_Combine_GUI_table.m
SIM_Compare_Combine_GUI_table
PURPOSE
SIM_COMPARE_COMBINE_GUI_TABLE MATLAB code for SIM_Compare_Combine_GUI_table.fig
SYNOPSIS
function varargout = SIM_Compare_Combine_GUI_table(varargin)
DESCRIPTION
 SIM_COMPARE_COMBINE_GUI_TABLE MATLAB code for SIM_Compare_Combine_GUI_table.fig
      SIM_COMPARE_COMBINE_GUI_TABLE, by itself, creates a new SIM_COMPARE_COMBINE_GUI_TABLE or raises the existing
      singleton*.
      H = SIM_COMPARE_COMBINE_GUI_TABLE returns the handle to a new SIM_COMPARE_COMBINE_GUI_TABLE or the handle to
      the existing singleton*.
      SIM_COMPARE_COMBINE_GUI_TABLE('CALLBACK',hObject,eventData,handles,...) calls the local
      function named CALLBACK in SIM_COMPARE_COMBINE_GUI_TABLE.M with the given input arguments.
      SIM_COMPARE_COMBINE_GUI_TABLE('Property','Value',...) creates a new SIM_COMPARE_COMBINE_GUI_TABLE or raises the
      existing singleton*.  Starting from the left, property value pairs are
      applied to the GUI before SIM_Compare_Combine_GUI_table_OpeningFcn gets called.  An
      unrecognized property name or invalid value makes property application
      stop.  All inputs are passed to SIM_Compare_Combine_GUI_table_OpeningFcn via varargin.
      *See GUI Options on GUIDE's Tools menu.  Choose "GUI allows only one
      instance to run (singleton)".
 See also: GUIDE, GUIDATA, GUIHANDLES
CROSS-REFERENCE INFORMATION
This function calls:
ContactForce_Exp
ContactR % contact resistance
ContactForce_Exp
ContactR % contact resistance
Func_RNetwork_Z % this function is used when the input fibermat is from generated fiber data (not from SEM).
HexPacking % square packing
SquarePacking % square packing
get TEMPLATE/GET Access data stored in a Template object
set TEMPLATE/SET Edit data stored in a Template object
This function is called by:
SUBFUNCTIONS
function SIM_Compare_Combine_GUI_table_OpeningFcn(hObject, eventdata, handles, varargin)
function varargout = SIM_Compare_Combine_GUI_table_OutputFcn(hObject, eventdata, handles)
function vfs_Callback(hObject, eventdata, handles)
function vfs_CreateFcn(hObject, eventdata, handles)
function v0_Callback(hObject, eventdata, handles)
function v0_CreateFcn(hObject, eventdata, handles)
function va_Callback(hObject, eventdata, handles)
function va_CreateFcn(hObject, eventdata, handles)
function beta_Callback(hObject, eventdata, handles)
function beta_CreateFcn(hObject, eventdata, handles)
function e_Callback(hObject, eventdata, handles)
function e_CreateFcn(hObject, eventdata, handles)
function fiberradius_Callback(hObject, eventdata, handles)
function fiberradius_CreateFcn(hObject, eventdata, handles)
function rf_Callback(hObject, eventdata, handles)
function rf_CreateFcn(hObject, eventdata, handles)
function fiberrad_Callback(hObject, eventdata, handles)
function fiberrad_CreateFcn(hObject, eventdata, handles)
function solve1_Callback(hObject, eventdata, handles)
function uitable10_CellEditCallback(hObject, eventdata, handles)
function edit_vfs_Callback(hObject, eventdata, handles)
function edit_vfs_CreateFcn(hObject, eventdata, handles)
function edit_fiberradius_Callback(hObject, eventdata, handles)
function edit_fiberradius_CreateFcn(hObject, eventdata, handles)
function edit_fiberrad_Callback(hObject, eventdata, handles)
function edit_fiberrad_CreateFcn(hObject, eventdata, handles)
function edit_beta_Callback(hObject, eventdata, handles)
function edit_beta_CreateFcn(hObject, eventdata, handles)
function edit_va_Callback(hObject, eventdata, handles)
function edit_va_CreateFcn(hObject, eventdata, handles)
function edit_e_Callback(hObject, eventdata, handles)
function edit_e_CreateFcn(hObject, eventdata, handles)
function edit_v0_Callback(hObject, eventdata, handles)
function edit_v0_CreateFcn(hObject, eventdata, handles)
function edit_rf_Callback(hObject, eventdata, handles)
function edit_rf_CreateFcn(hObject, eventdata, handles)
function uitable11_CellEditCallback(hObject, eventdata, handles)
function table_Callback(hObject, eventdata, handles)
function edit18_Callback(hObject, eventdata, handles)
function edit18_CreateFcn(hObject, eventdata, handles)
function edit19_Callback(hObject, eventdata, handles)
function edit19_CreateFcn(hObject, eventdata, handles)
function edit20_Callback(hObject, eventdata, handles)
function edit20_CreateFcn(hObject, eventdata, handles)
function numbreak_Callback(hObject, eventdata, handles)
function numbreak_CreateFcn(hObject, eventdata, handles)
function rbreakage_Callback(hObject, eventdata, handles)
function rbreakage_CreateFcn(hObject, eventdata, handles)
function fiberlen_Callback(hObject, eventdata, handles)
function fiberlen_CreateFcn(hObject, eventdata, handles)
function edit24_Callback(hObject, eventdata, handles)
function edit24_CreateFcn(hObject, eventdata, handles)
function betamean_Callback(hObject, eventdata, handles)
function betamean_CreateFcn(hObject, eventdata, handles)
function edit27_Callback(hObject, eventdata, handles)
function edit27_CreateFcn(hObject, eventdata, handles)
function betadev_Callback(hObject, eventdata, handles)
function betadev_CreateFcn(hObject, eventdata, handles)
function edit29_Callback(hObject, eventdata, handles)
function edit29_CreateFcn(hObject, eventdata, handles)
function edit30_Callback(hObject, eventdata, handles)
function edit30_CreateFcn(hObject, eventdata, handles)
function fcolumntag_Callback(hObject, eventdata, handles)
function fcolumntag_CreateFcn(hObject, eventdata, handles)
function frowtag_Callback(hObject, eventdata, handles)
function frowtag_CreateFcn(hObject, eventdata, handles)
function enter_Callback(hObject, eventdata, handles)
function enter_CreateFcn(hObject, eventdata, handles)
function popup_Callback(hObject, eventdata, handles)
function popup_CreateFcn(hObject, eventdata, handles)
function Untitled_1_Callback(hObject, eventdata, handles)
function axes2_CreateFcn(hObject, eventdata, handles)
function pushbutton5_Callback(hObject, eventdata, handles)
function popup1_Callback(hObject, eventdata, handles)
function popup1_CreateFcn(hObject, eventdata, handles)
function uitable1_CellEditCallback(hObject, eventdata, handles)
SOURCE CODE
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            function varargout = SIM_Compare_Combine_GUI_table(varargin)
% SIM_COMPARE_COMBINE_GUI_TABLE MATLAB code for SIM_Compare_Combine_GUI_table.fig
%      SIM_COMPARE_COMBINE_GUI_TABLE, by itself, creates a new SIM_COMPARE_COMBINE_GUI_TABLE or raises the existing
%      singleton*.
%
%      H = SIM_COMPARE_COMBINE_GUI_TABLE returns the handle to a new SIM_COMPARE_COMBINE_GUI_TABLE or the handle to
%      the existing singleton*.
%
%      SIM_COMPARE_COMBINE_GUI_TABLE('CALLBACK',hObject,eventData,handles,...) calls the local
%      function named CALLBACK in SIM_COMPARE_COMBINE_GUI_TABLE.M with the given input arguments.
%
%      SIM_COMPARE_COMBINE_GUI_TABLE('Property','Value',...) creates a new SIM_COMPARE_COMBINE_GUI_TABLE or raises the
%      existing singleton*.  Starting from the left, property value pairs are
%      applied to the GUI before SIM_Compare_Combine_GUI_table_OpeningFcn gets called.  An
%      unrecognized property name or invalid value makes property application
%      stop.  All inputs are passed to SIM_Compare_Combine_GUI_table_OpeningFcn via varargin.
%
%      *See GUI Options on GUIDE's Tools menu.  Choose "GUI allows only one
%      instance to run (singleton)".
%
% See also: GUIDE, GUIDATA, GUIHANDLES
% Edit the above text to modify the response to help SIM_Compare_Combine_GUI_table
% Last Modified by GUIDE v2.5 15-Jul-2015 15:41:11
% Begin initialization code - DO NOT EDIT
gui_Singleton = 1;
gui_State = struct('gui_Name',       mfilename, ...
                   'gui_Singleton',  gui_Singleton, ...
                   'gui_OpeningFcn', @SIM_Compare_Combine_GUI_table_OpeningFcn, ...
                   'gui_OutputFcn',  @SIM_Compare_Combine_GUI_table_OutputFcn, ...
                   'gui_LayoutFcn',  [] , ...
                   'gui_Callback',   []);
if nargin && ischar(varargin{1})
    gui_State.gui_Callback = str2func(varargin{1});
end
if nargout
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});
else
    gui_mainfcn(gui_State, varargin{:});
end
% End initialization code - DO NOT EDIT
% --- Executes just before SIM_Compare_Combine_GUI_table is made visible.
function SIM_Compare_Combine_GUI_table_OpeningFcn(hObject, eventdata, handles, varargin)
% This function has no output args, see OutputFcn.
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% varargin   command line arguments to SIM_Compare_Combine_GUI_table (see VARARGIN)
% Choose default command line output for SIM_Compare_Combine_GUI_table
handles.output = hObject;
data = get(handles.uitable1 ,'Data');
data = cell2mat(data);
data = reshape(strtrim(cellstr(num2str(data(:)))), size(data));
data(:,1) = cellfun(@(x) ['<html><table border=0 width=400 bgcolor=#FFF0000><TR><TD>' x '</TD></TR> </table></html>'], data(:,1), 'UniformOutput', false);
data(1,:) = cellfun(@(x) ['<html><table border=0 width=400 bgcolor=#FFF0000><TR><TD>' x '</TD></TR> </table></html>'], data(1,:), 'UniformOutput', false);
set(handles.uitable1,'data',data);
axes(handles.axes1)
xlabel('x')
ylabel('y')
grid on
title('y vs x')
% Update handles structure
guidata(hObject, handles);
% UIWAIT makes SIM_Compare_Combine_GUI_table wait for user response (see UIRESUME)
% uiwait(handles.figure1);
% --- Outputs from this function are returned to the command line.
function varargout = SIM_Compare_Combine_GUI_table_OutputFcn(hObject, eventdata, handles)
% varargout  cell array for returning output args (see VARARGOUT);
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Get default command line output from handles structure
varargout{1} = handles.output;
function vfs_Callback(hObject, eventdata, handles)
% hObject    handle to vfs (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of vfs as text
%        str2double(get(hObject,'String')) returns contents of vfs as a double
% --- Executes during object creation, after setting all properties.
function vfs_CreateFcn(hObject, eventdata, handles)
% hObject    handle to vfs (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function v0_Callback(hObject, eventdata, handles)
% hObject    handle to v0 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of v0 as text
%        str2double(get(hObject,'String')) returns contents of v0 as a double
% --- Executes during object creation, after setting all properties.
function v0_CreateFcn(hObject, eventdata, handles)
% hObject    handle to v0 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function va_Callback(hObject, eventdata, handles)
% hObject    handle to va (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of va as text
%        str2double(get(hObject,'String')) returns contents of va as a double
% --- Executes during object creation, after setting all properties.
function va_CreateFcn(hObject, eventdata, handles)
% hObject    handle to va (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function beta_Callback(hObject, eventdata, handles)
% hObject    handle to beta (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of beta as text
%        str2double(get(hObject,'String')) returns contents of beta as a double
% --- Executes during object creation, after setting all properties.
function beta_CreateFcn(hObject, eventdata, handles)
% hObject    handle to beta (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function e_Callback(hObject, eventdata, handles)
% hObject    handle to e (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of e as text
%        str2double(get(hObject,'String')) returns contents of e as a double
% --- Executes during object creation, after setting all properties.
function e_CreateFcn(hObject, eventdata, handles)
% hObject    handle to e (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function fiberradius_Callback(hObject, eventdata, handles)
% hObject    handle to fiberradius (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of fiberradius as text
%        str2double(get(hObject,'String')) returns contents of fiberradius as a double
% --- Executes during object creation, after setting all properties.
function fiberradius_CreateFcn(hObject, eventdata, handles)
% hObject    handle to fiberradius (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function rf_Callback(hObject, eventdata, handles)
% hObject    handle to rf (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of rf as text
%        str2double(get(hObject,'String')) returns contents of rf as a double
% --- Executes during object creation, after setting all properties.
function rf_CreateFcn(hObject, eventdata, handles)
% hObject    handle to rf (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function fiberrad_Callback(hObject, eventdata, handles)
% hObject    handle to fiberrad (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of fiberrad as text
%        str2double(get(hObject,'String')) returns contents of fiberrad as a double
% --- Executes during object creation, after setting all properties.
function fiberrad_CreateFcn(hObject, eventdata, handles)
% hObject    handle to fiberrad (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
% --- Executes on button press in solve1.
function solve1_Callback(hObject, eventdata, handles)
% hObject    handle to solve1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
%call the Inputs from the uitable
data = get(handles.uitable1 ,'Data');
allVFs = cell2mat(data(:,1));
V0 = cell2mat(data(:,2));
% v0_1=V0(1);
Va = cell2mat(data(:,3));
beta = cell2mat(data(:,4));
E = cell2mat(data(:,5));
fiberRadius = cell2mat(data(:,6));
FiberRad = cell2mat(data(:,7));
rf = cell2mat(data(:,8));
NumBreak = cell2mat(data(:,9));
RBreakage = cell2mat(data(:,10));
fiberLen = cell2mat(data(:,11));
beta_mean = cell2mat(data(:,12));
beta_dev = cell2mat(data(:,13));
frow = cell2mat(data(:,14));
fcolumn = cell2mat(data(:,15));
Enter = get(handles.enter,'String');
% inputs for editbox
% VFs = str2num(get(handles.vfs, 'String'));
% V0 = get(handles.uitable1, 'Data');
% Va = str2num (get(handles.va, 'String'));
% beta = str2num (get(handles.beta, 'String'));
% E = str2num (get(handles.e, 'String'));
% fiberRadius = str2num (get(handles.fiberradius, 'String'));
% FiberRad = str2num (get(handles.fiberrad, 'String'));
% rf = str2num (get(handles.rf, 'String'));
% NumBreak = str2num (get(handles.numbreak, 'String'));
% RBreakage = str2num (get(handles.rbreakage, 'String'));
% fiberLen = str2num (get(handles.fiberlen, 'String'));
% beta_mean = str2num (get(handles.betamean, 'String'));
% beta_dev = str2num (get(handles.betadev, 'String'));
% frow = str2num (get(handles.frowtag, 'String'));
% fcolumn = str2num (get(handles.fcolumntag, 'String'));
% popup-menu to choose the functions
rhos=[];
for i=1:length(VFs)
    VF=VFs(i);
   x = get(handles.popup,'Value');
switch x
    case 1
        h = msgbox('Please Choose a function', 'Error','error');
    case 2
        [Fc,Pressure] = ContactForce_Exp(V0,Va,VF,beta,E,fiberRadius);
Rc = ContactR(fiberRadius,Fc,E,rf);
%1. Random Packing
specimen=1;
fibermat=strcat('vf_',num2str(VF),'_spec',num2str(specimen),'.mat');
    case 3
        [Fc,Pressure] = ContactForce_Exp(V0,Va,VF,beta,E,fiberRadius);
Rc = ContactR(fiberRadius,Fc,E,rf);
%3. Square Packing
SquarePacking(frow,fcolumn,VF,fiberRadius);
fibermat='PerfectFiber.mat';
    case 4
        [Fc,Pressure] = ContactForce_Exp(V0,Va,VF,beta,E,fiberRadius);
Rc = ContactR(fiberRadius,Fc,E,rf);
%3. Hexagonal Packing
HexPacking(frow,fcolumn,VF,fiberRadius);
fibermat='PerfectFiber.mat';
    otherwise
end
[rho,fiber,VF,NumContacts]=Func_RNetwork_Z(fibermat,fiberLen,beta_mean,fiberRadius,NumBreak,Rc,rf,RBreakage);
rhos(end+1)=rho;
end
% % % create the Table
% V0_1  = V0.*ones(1,length(VFs));
% Va_1 = Va.*ones(1,length(VFs));
% beta_1 = beta.*ones(1,length(VFs));
% E_1 = E.*ones(1,length(VFs));
% fiberRadius_1 = fiberRadius.*ones(1,length(VFs));
% FiberRad_1 = FiberRad.*ones(1,length(VFs));
% rf_1 = rf.*ones(1,length(VFs));
% fiberLen_1 = fiberLen.*ones(1,length(VFs));
% RBreakage_1 = RBreakage.*ones(1,length(VFs));
% NumBreak_1 = NumBreak.*ones(1,length(VFs));
% beta_mean_1 = beta_mean.*ones(1,length(VFs));
% beta_dev_1 = beta_dev.*ones(1,length(VFs));
% frow_1 = frow.*ones(1,length(VFs));
% fcolumn_1 = fcolumn.*ones(1,length(VFs));
%
% A = [V0_1;Va_1;beta_1;E_1;fiberRadius_1;FiberRad_1;rf_1;fiberLen_1;RBreakage_1;NumBreak_1;beta_mean_1;beta_dev_1;frow_1;fcolumn_1;VFs;rhos];
%
% fileID = fopen(Enter,'w');
% fprintf(fileID,'%6s,%6s,%6s,%6s,%6s,%6s,%6s,%6s,%6s,%6s,%6s,%6s,%6s,%6s,%6s,%12s\r\n','V0','Va','beta','E',...
% 'fiberRadius','FiberRad','rf','fiberLen','Rbreakage','NumBreak','beta_mean','beta_dev','frow','fcolumn','VFs','rhos');
% % fprintf(fileID,'%6s %6s %6s %6s %6s %6s %6s %6s %6s %6s %6s %6s %6s %12s\n','V0','Va','beta','E',...
% % 'fiberRadius','FiberRad','rf','fiberLen','RBreakage','NumBreak','beta_mean','beta_dev','VFs','rhoz');
% fprintf(fileID,'%6.2f,%6.2f,%6.2f,%2.10f,%2.10f,%2.20f,%2.20f,%6.2f,%6.2f,%6.2f,%6.2f,%6.2f,%6.2f,%6.2f,%6.2f,%12.8f\r\n' ,A);
% fclose(fileID);
%
%
%
% % create Table end
%
% % Define Axes
axes(handles.axes1)
% popup-menu to choose plotting
s = get(handles.popup1,'Value');
switch s
    case 1
        plot(rhos,VFs)
        xlabel('rho')
        ylabel('Volumfraction')
        title('Volumfraction vs rho')
    case 2
        plot(rhos,V0)
        xlabel('rho')
        ylabel('V0')
        title('V0 vs rho')
    case 3
        plot(rhos,Va_1)
        xlabel('rho')
        ylabel('Va')
        title('Va vs rho')
    otherwise
end
grid on
% xlabel('rho')
% ylabel('Volumfraction')
% title('Volumfraction vs rho')
guidata(hObject,handles);
% end Define Axes
% --- Executes when entered data in editable cell(s) in uitable10.
function uitable10_CellEditCallback(hObject, eventdata, handles)
% hObject    handle to uitable10 (see GCBO)
% eventdata  structure with the following fields (see MATLAB.UI.CONTROL.TABLE)
%    Indices: row and column indices of the cell(s) edited
%    PreviousData: previous data for the cell(s) edited
%    EditData: string(s) entered by the user
%    NewData: EditData or its converted form set on the Data property. Empty if Data was not changed
%    Error: error string when failed to convert EditData to appropriate value for Data
% handles    structure with handles and user data (see GUIDATA)
data = get(hObject, 'data');
function edit_vfs_Callback(hObject, eventdata, handles)
% hObject    handle to edit_vfs (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of edit_vfs as text
%        str2double(get(hObject,'String')) returns contents of edit_vfs as a double
% --- Executes during object creation, after setting all properties.
function edit_vfs_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit_vfs (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function edit_fiberradius_Callback(hObject, eventdata, handles)
% hObject    handle to edit_fiberradius (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of edit_fiberradius as text
%        str2double(get(hObject,'String')) returns contents of edit_fiberradius as a double
% --- Executes during object creation, after setting all properties.
function edit_fiberradius_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit_fiberradius (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function edit_fiberrad_Callback(hObject, eventdata, handles)
% hObject    handle to edit_fiberrad (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of edit_fiberrad as text
%        str2double(get(hObject,'String')) returns contents of edit_fiberrad as a double
% --- Executes during object creation, after setting all properties.
function edit_fiberrad_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit_fiberrad (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function edit_beta_Callback(hObject, eventdata, handles)
% hObject    handle to edit_beta (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of edit_beta as text
%        str2double(get(hObject,'String')) returns contents of edit_beta as a double
% --- Executes during object creation, after setting all properties.
function edit_beta_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit_beta (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function edit_va_Callback(hObject, eventdata, handles)
% hObject    handle to edit_va (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of edit_va as text
%        str2double(get(hObject,'String')) returns contents of edit_va as a double
% --- Executes during object creation, after setting all properties.
function edit_va_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit_va (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function edit_e_Callback(hObject, eventdata, handles)
% hObject    handle to edit_e (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of edit_e as text
%        str2double(get(hObject,'String')) returns contents of edit_e as a double
% --- Executes during object creation, after setting all properties.
function edit_e_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit_e (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function edit_v0_Callback(hObject, eventdata, handles)
% hObject    handle to edit_v0 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of edit_v0 as text
%        str2double(get(hObject,'String')) returns contents of edit_v0 as a double
% --- Executes during object creation, after setting all properties.
function edit_v0_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit_v0 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function edit_rf_Callback(hObject, eventdata, handles)
% hObject    handle to edit_rf (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of edit_rf as text
%        str2double(get(hObject,'String')) returns contents of edit_rf as a double
% --- Executes during object creation, after setting all properties.
function edit_rf_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit_rf (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
% --- Executes when entered data in editable cell(s) in uitable11.
function uitable11_CellEditCallback(hObject, eventdata, handles)
% hObject    handle to uitable11 (see GCBO)
% eventdata  structure with the following fields (see MATLAB.UI.CONTROL.TABLE)
%    Indices: row and column indices of the cell(s) edited
%    PreviousData: previous data for the cell(s) edited
%    EditData: string(s) entered by the user
%    NewData: EditData or its converted form set on the Data property. Empty if Data was not changed
%    Error: error string when failed to convert EditData to appropriate value for Data
% handles    structure with handles and user data (see GUIDATA)
% --- Executes on button press in table.
function table_Callback(hObject, eventdata, handles)
% hObject    handle to table (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
function edit18_Callback(hObject, eventdata, handles)
% hObject    handle to edit18 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of edit18 as text
%        str2double(get(hObject,'String')) returns contents of edit18 as a double
% --- Executes during object creation, after setting all properties.
function edit18_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit18 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function edit19_Callback(hObject, eventdata, handles)
% hObject    handle to edit19 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of edit19 as text
%        str2double(get(hObject,'String')) returns contents of edit19 as a double
% --- Executes during object creation, after setting all properties.
function edit19_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit19 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function edit20_Callback(hObject, eventdata, handles)
% hObject    handle to edit20 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of edit20 as text
%        str2double(get(hObject,'String')) returns contents of edit20 as a double
% --- Executes during object creation, after setting all properties.
function edit20_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit20 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function numbreak_Callback(hObject, eventdata, handles)
% hObject    handle to numbreak (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of numbreak as text
%        str2double(get(hObject,'String')) returns contents of numbreak as a double
% --- Executes during object creation, after setting all properties.
function numbreak_CreateFcn(hObject, eventdata, handles)
% hObject    handle to numbreak (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function rbreakage_Callback(hObject, eventdata, handles)
% hObject    handle to rbreakage (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of rbreakage as text
%        str2double(get(hObject,'String')) returns contents of rbreakage as a double
% --- Executes during object creation, after setting all properties.
function rbreakage_CreateFcn(hObject, eventdata, handles)
% hObject    handle to rbreakage (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function fiberlen_Callback(hObject, eventdata, handles)
% hObject    handle to fiberlen (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of fiberlen as text
%        str2double(get(hObject,'String')) returns contents of fiberlen as a double
% --- Executes during object creation, after setting all properties.
function fiberlen_CreateFcn(hObject, eventdata, handles)
% hObject    handle to fiberlen (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function edit24_Callback(hObject, eventdata, handles)
% hObject    handle to edit24 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of edit24 as text
%        str2double(get(hObject,'String')) returns contents of edit24 as a double
% --- Executes during object creation, after setting all properties.
function edit24_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit24 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function betamean_Callback(hObject, eventdata, handles)
% hObject    handle to betamean (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of betamean as text
%        str2double(get(hObject,'String')) returns contents of betamean as a double
% --- Executes during object creation, after setting all properties.
function betamean_CreateFcn(hObject, eventdata, handles)
% hObject    handle to betamean (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function edit27_Callback(hObject, eventdata, handles)
% hObject    handle to edit27 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of edit27 as text
%        str2double(get(hObject,'String')) returns contents of edit27 as a double
% --- Executes during object creation, after setting all properties.
function edit27_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit27 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function betadev_Callback(hObject, eventdata, handles)
% hObject    handle to betadev (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of betadev as text
%        str2double(get(hObject,'String')) returns contents of betadev as a double
% --- Executes during object creation, after setting all properties.
function betadev_CreateFcn(hObject, eventdata, handles)
% hObject    handle to betadev (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function edit29_Callback(hObject, eventdata, handles)
% hObject    handle to edit29 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of edit29 as text
%        str2double(get(hObject,'String')) returns contents of edit29 as a double
% --- Executes during object creation, after setting all properties.
function edit29_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit29 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function edit30_Callback(hObject, eventdata, handles)
% hObject    handle to edit30 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of edit30 as text
%        str2double(get(hObject,'String')) returns contents of edit30 as a double
% --- Executes during object creation, after setting all properties.
function edit30_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit30 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function fcolumntag_Callback(hObject, eventdata, handles)
% hObject    handle to fcolumntag (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of fcolumntag as text
%        str2double(get(hObject,'String')) returns contents of fcolumntag as a double
% --- Executes during object creation, after setting all properties.
function fcolumntag_CreateFcn(hObject, eventdata, handles)
% hObject    handle to fcolumntag (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function frowtag_Callback(hObject, eventdata, handles)
% hObject    handle to frowtag (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of frowtag as text
%        str2double(get(hObject,'String')) returns contents of frowtag as a double
% --- Executes during object creation, after setting all properties.
function frowtag_CreateFcn(hObject, eventdata, handles)
% hObject    handle to frowtag (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function enter_Callback(hObject, eventdata, handles)
% hObject    handle to enter (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of enter as text
%        str2double(get(hObject,'String')) returns contents of enter as a double
% --- Executes during object creation, after setting all properties.
function enter_CreateFcn(hObject, eventdata, handles)
% hObject    handle to enter (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
1000 %       See ISPC and COMPUTER.
1001 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1002     set(hObject,'BackgroundColor','white');
1003 end
1004
1005
1006 % --- Executes on selection change in popup.
1007 function popup_Callback(hObject, eventdata, handles)
1008 % hObject    handle to popup (see GCBO)
1009 % eventdata  reserved - to be defined in a future version of MATLAB
1010 % handles    structure with handles and user data (see GUIDATA)
1011
1012 % Hints: contents = cellstr(get(hObject,'String')) returns popup contents as cell array
1013 %        contents{get(hObject,'Value')} returns selected item from popup
1014 %
1015 val=get(hObject,'value');
1016 axes(handles.axes2);
1017
1018 switch val
1019
1020     case 1
1021
1022          cla(handles.axes2);
1023          cla(handles.axes1);
1024
1025     case 2
1026
1027         imshow('Random.jpg');
1028         cla(handles.axes1);
1029
1030     case 3
1031
1032          imshow('Square.jpg');
1033          cla(handles.axes1);
1034
1035     case 4
1036
1037         imshow('Hexagonal.jpg');
1038         cla(handles.axes1);
1039
1040     otherwise
1041 end
1042
1043         guidata(hObject,handles);
1044
1045
1046
1047
1048 % --- Executes during object creation, after setting all properties.
1049 function popup_CreateFcn(hObject, eventdata, handles)
1050 % hObject    handle to popup (see GCBO)
1051 % eventdata  reserved - to be defined in a future version of MATLAB
1052 % handles    empty - handles not created until after all CreateFcns called
1053
1054 % Hint: popupmenu controls usually have a white background on Windows.
1055 %       See ISPC and COMPUTER.
1056 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1057     set(hObject,'BackgroundColor','white');
1058 end
1059
1060
1061 % --------------------------------------------------------------------
1062 function Untitled_1_Callback(hObject, eventdata, handles)
1063 % hObject    handle to Untitled_1 (see GCBO)
1064 % eventdata  reserved - to be defined in a future version of MATLAB
1065 % handles    structure with handles and user data (see GUIDATA)
1066
1067
1068
1069 % --- Executes during object creation, after setting all properties.
1070 function axes2_CreateFcn(hObject, eventdata, handles)
1071 % hObject    handle to axes2 (see GCBO)
1072 % eventdata  reserved - to be defined in a future version of MATLAB
1073 % handles    empty - handles not created until after all CreateFcns called
1074
1075 % Hint: place code in OpeningFcn to populate axes2
1076
1077
1078 % end
1079
1080
1081 % --- Executes on button press in pushbutton5.
1082 function pushbutton5_Callback(hObject, eventdata, handles)
1083 % hObject    handle to pushbutton5 (see GCBO)
1084 % eventdata  reserved - to be defined in a future version of MATLAB
1085 % handles    structure with handles and user data (see GUIDATA)
1086 cla(handles.axes1);
1087
1088
1089 % --- Executes on selection change in popup1.
1090 function popup1_Callback(hObject, eventdata, handles)
1091 % hObject    handle to popup1 (see GCBO)
1092 % eventdata  reserved - to be defined in a future version of MATLAB
1093 % handles    structure with handles and user data (see GUIDATA)
1094
1095 % Hints: contents = cellstr(get(hObject,'String')) returns popup1 contents as cell array
1096 %        contents{get(hObject,'Value')} returns selected item from popup1
1097
1098
1099 % --- Executes during object creation, after setting all properties.
1100 function popup1_CreateFcn(hObject, eventdata, handles)
1101 % hObject    handle to popup1 (see GCBO)
1102 % eventdata  reserved - to be defined in a future version of MATLAB
1103 % handles    empty - handles not created until after all CreateFcns called
1104
1105 % Hint: popupmenu controls usually have a white background on Windows.
1106 %       See ISPC and COMPUTER.
1107 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1108     set(hObject,'BackgroundColor','white');
1109 end
1110
1111
1112 % --- Executes when entered data in editable cell(s) in uitable1.
1113 function uitable1_CellEditCallback(hObject, eventdata, handles)
1114 % hObject    handle to uitable1 (see GCBO)
1115 % eventdata  structure with the following fields (see MATLAB.UI.CONTROL.TABLE)
1116 %    Indices: row and column indices of the cell(s) edited
1117 %    PreviousData: previous data for the cell(s) edited
1118 %    EditData: string(s) entered by the user
1119 %    NewData: EditData or its converted form set on the Data property. Empty if Data was not changed
1120 %    Error: error string when failed to convert EditData to appropriate value for Data
1121 % handles    structure with handles and user data (see GUIDATA)
1122
1123
1124 q=eventdata.Indices;
1125 X=get(handles.uitable1,'Data');
1126 if q(1)== 1 || q(2) == 1
1127     X(q(1),q(2)) = cellfun(@(x) ['<html><table border=0 width=400 bgcolor=#FFF000><TR><TD>' x '</TD></TR> </table></html>'], X(q(1),q(2)), 'UniformOutput', false);
1128     set(handles.uitable1,'Data', X);
1129 end
1130
1131