Description of SIM_Compare_Combine_GUI
Home > v08 > helper > SIM_Compare_Combine_GUI.m
SIM_Compare_Combine_GUI
PURPOSE
SIM_COMPARE_COMBINE_GUI MATLAB code for SIM_Compare_Combine_GUI.fig
SYNOPSIS
function varargout = SIM_Compare_Combine_GUI(varargin)
DESCRIPTION
 SIM_COMPARE_COMBINE_GUI MATLAB code for SIM_Compare_Combine_GUI.fig
      SIM_COMPARE_COMBINE_GUI, by itself, creates a new SIM_COMPARE_COMBINE_GUI or raises the existing
      singleton*.
      H = SIM_COMPARE_COMBINE_GUI returns the handle to a new SIM_COMPARE_COMBINE_GUI or the handle to
      the existing singleton*.
      SIM_COMPARE_COMBINE_GUI('CALLBACK',hObject,eventData,handles,...) calls the local
      function named CALLBACK in SIM_COMPARE_COMBINE_GUI.M with the given input arguments.
      SIM_COMPARE_COMBINE_GUI('Property','Value',...) creates a new SIM_COMPARE_COMBINE_GUI or raises the
      existing singleton*.  Starting from the left, property value pairs are
      applied to the GUI before SIM_Compare_Combine_GUI_OpeningFcn gets called.  An
      unrecognized property name or invalid value makes property application
      stop.  All inputs are passed to SIM_Compare_Combine_GUI_OpeningFcn via varargin.
      *See GUI Options on GUIDE's Tools menu.  Choose "GUI allows only one
      instance to run (singleton)".
 See also: GUIDE, GUIDATA, GUIHANDLES
CROSS-REFERENCE INFORMATION
This function calls:
ContactForce_Exp
ContactR % contact resistance
ContactForce_Exp
ContactR % contact resistance
Func_RNetwork_Z % this function is used when the input fibermat is from generated fiber data (not from SEM).
HexPacking % square packing
SquarePacking % square packing
get TEMPLATE/GET Access data stored in a Template object
set TEMPLATE/SET Edit data stored in a Template object
This function is called by:
SUBFUNCTIONS
function SIM_Compare_Combine_GUI_OpeningFcn(hObject, eventdata, handles, varargin)
function varargout = SIM_Compare_Combine_GUI_OutputFcn(hObject, eventdata, handles)
function vfs_Callback(hObject, eventdata, handles)
function vfs_CreateFcn(hObject, eventdata, handles)
function v0_Callback(hObject, eventdata, handles)
function v0_CreateFcn(hObject, eventdata, handles)
function va_Callback(hObject, eventdata, handles)
function va_CreateFcn(hObject, eventdata, handles)
function beta_Callback(hObject, eventdata, handles)
function beta_CreateFcn(hObject, eventdata, handles)
function e_Callback(hObject, eventdata, handles)
function e_CreateFcn(hObject, eventdata, handles)
function fiberradius_Callback(hObject, eventdata, handles)
function fiberradius_CreateFcn(hObject, eventdata, handles)
function rf_Callback(hObject, eventdata, handles)
function rf_CreateFcn(hObject, eventdata, handles)
function fiberrad_Callback(hObject, eventdata, handles)
function fiberrad_CreateFcn(hObject, eventdata, handles)
function solve1_Callback(hObject, eventdata, handles)
function uitable10_CellEditCallback(hObject, eventdata, handles)
function edit_vfs_Callback(hObject, eventdata, handles)
function edit_vfs_CreateFcn(hObject, eventdata, handles)
function edit_fiberradius_Callback(hObject, eventdata, handles)
function edit_fiberradius_CreateFcn(hObject, eventdata, handles)
function edit_fiberrad_Callback(hObject, eventdata, handles)
function edit_fiberrad_CreateFcn(hObject, eventdata, handles)
function edit_beta_Callback(hObject, eventdata, handles)
function edit_beta_CreateFcn(hObject, eventdata, handles)
function edit_va_Callback(hObject, eventdata, handles)
function edit_va_CreateFcn(hObject, eventdata, handles)
function edit_e_Callback(hObject, eventdata, handles)
function edit_e_CreateFcn(hObject, eventdata, handles)
function edit_v0_Callback(hObject, eventdata, handles)
function edit_v0_CreateFcn(hObject, eventdata, handles)
function edit_rf_Callback(hObject, eventdata, handles)
function edit_rf_CreateFcn(hObject, eventdata, handles)
function uitable11_CellEditCallback(hObject, eventdata, handles)
function table_Callback(hObject, eventdata, handles)
function edit18_Callback(hObject, eventdata, handles)
function edit18_CreateFcn(hObject, eventdata, handles)
function edit19_Callback(hObject, eventdata, handles)
function edit19_CreateFcn(hObject, eventdata, handles)
function edit20_Callback(hObject, eventdata, handles)
function edit20_CreateFcn(hObject, eventdata, handles)
function numbreak_Callback(hObject, eventdata, handles)
function numbreak_CreateFcn(hObject, eventdata, handles)
function rbreakage_Callback(hObject, eventdata, handles)
function rbreakage_CreateFcn(hObject, eventdata, handles)
function fiberlen_Callback(hObject, eventdata, handles)
function fiberlen_CreateFcn(hObject, eventdata, handles)
function edit24_Callback(hObject, eventdata, handles)
function edit24_CreateFcn(hObject, eventdata, handles)
function betamean_Callback(hObject, eventdata, handles)
function betamean_CreateFcn(hObject, eventdata, handles)
function edit27_Callback(hObject, eventdata, handles)
function edit27_CreateFcn(hObject, eventdata, handles)
function betadev_Callback(hObject, eventdata, handles)
function betadev_CreateFcn(hObject, eventdata, handles)
function edit29_Callback(hObject, eventdata, handles)
function edit29_CreateFcn(hObject, eventdata, handles)
function edit30_Callback(hObject, eventdata, handles)
function edit30_CreateFcn(hObject, eventdata, handles)
function fcolumntag_Callback(hObject, eventdata, handles)
function fcolumntag_CreateFcn(hObject, eventdata, handles)
function frowtag_Callback(hObject, eventdata, handles)
function frowtag_CreateFcn(hObject, eventdata, handles)
function enter_Callback(hObject, eventdata, handles)
function enter_CreateFcn(hObject, eventdata, handles)
function popup_Callback(hObject, eventdata, handles)
function popup_CreateFcn(hObject, eventdata, handles)
function Untitled_1_Callback(hObject, eventdata, handles)
function axes2_CreateFcn(hObject, eventdata, handles)
function pushbutton5_Callback(hObject, eventdata, handles)
SOURCE CODE
function varargout = SIM_Compare_Combine_GUI(varargin)
% SIM_COMPARE_COMBINE_GUI MATLAB code for SIM_Compare_Combine_GUI.fig
%      SIM_COMPARE_COMBINE_GUI, by itself, creates a new SIM_COMPARE_COMBINE_GUI or raises the existing
%      singleton*.
%
%      H = SIM_COMPARE_COMBINE_GUI returns the handle to a new SIM_COMPARE_COMBINE_GUI or the handle to
%      the existing singleton*.
%
%      SIM_COMPARE_COMBINE_GUI('CALLBACK',hObject,eventData,handles,...) calls the local
%      function named CALLBACK in SIM_COMPARE_COMBINE_GUI.M with the given input arguments.
%
%      SIM_COMPARE_COMBINE_GUI('Property','Value',...) creates a new SIM_COMPARE_COMBINE_GUI or raises the
%      existing singleton*.  Starting from the left, property value pairs are
%      applied to the GUI before SIM_Compare_Combine_GUI_OpeningFcn gets called.  An
%      unrecognized property name or invalid value makes property application
%      stop.  All inputs are passed to SIM_Compare_Combine_GUI_OpeningFcn via varargin.
%
%      *See GUI Options on GUIDE's Tools menu.  Choose "GUI allows only one
%      instance to run (singleton)".
%
% See also: GUIDE, GUIDATA, GUIHANDLES
% Edit the above text to modify the response to help SIM_Compare_Combine_GUI
% Last Modified by GUIDE v2.5 29-Jun-2015 13:02:58
% Begin initialization code - DO NOT EDIT
gui_Singleton = 1;
gui_State = struct('gui_Name',       mfilename, ...
                   'gui_Singleton',  gui_Singleton, ...
                   'gui_OpeningFcn', @SIM_Compare_Combine_GUI_OpeningFcn, ...
                   'gui_OutputFcn',  @SIM_Compare_Combine_GUI_OutputFcn, ...
                   'gui_LayoutFcn',  [] , ...
                   'gui_Callback',   []);
if nargin && ischar(varargin{1})
    gui_State.gui_Callback = str2func(varargin{1});
end
if nargout
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});
else
    gui_mainfcn(gui_State, varargin{:});
end
% End initialization code - DO NOT EDIT
% --- Executes just before SIM_Compare_Combine_GUI is made visible.
function SIM_Compare_Combine_GUI_OpeningFcn(hObject, eventdata, handles, varargin)
% This function has no output args, see OutputFcn.
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% varargin   command line arguments to SIM_Compare_Combine_GUI (see VARARGIN)
% Choose default command line output for SIM_Compare_Combine_GUI
handles.output = hObject;
clc
axes(handles.axes1)
xlabel('x')
ylabel('y')
grid on
title('y vs x')
% Update handles structure
guidata(hObject, handles);
% UIWAIT makes SIM_Compare_Combine_GUI wait for user response (see UIRESUME)
% uiwait(handles.figure1);
% --- Outputs from this function are returned to the command line.
function varargout = SIM_Compare_Combine_GUI_OutputFcn(hObject, eventdata, handles)
% varargout  cell array for returning output args (see VARARGOUT);
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Get default command line output from handles structure
varargout{1} = handles.output;
function vfs_Callback(hObject, eventdata, handles)
% hObject    handle to vfs (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of vfs as text
%        str2double(get(hObject,'String')) returns contents of vfs as a double
% --- Executes during object creation, after setting all properties.
function vfs_CreateFcn(hObject, eventdata, handles)
% hObject    handle to vfs (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function v0_Callback(hObject, eventdata, handles)
% hObject    handle to v0 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of v0 as text
%        str2double(get(hObject,'String')) returns contents of v0 as a double
% --- Executes during object creation, after setting all properties.
function v0_CreateFcn(hObject, eventdata, handles)
% hObject    handle to v0 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function va_Callback(hObject, eventdata, handles)
% hObject    handle to va (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of va as text
%        str2double(get(hObject,'String')) returns contents of va as a double
% --- Executes during object creation, after setting all properties.
function va_CreateFcn(hObject, eventdata, handles)
% hObject    handle to va (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function beta_Callback(hObject, eventdata, handles)
% hObject    handle to beta (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of beta as text
%        str2double(get(hObject,'String')) returns contents of beta as a double
% --- Executes during object creation, after setting all properties.
function beta_CreateFcn(hObject, eventdata, handles)
% hObject    handle to beta (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function e_Callback(hObject, eventdata, handles)
% hObject    handle to e (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of e as text
%        str2double(get(hObject,'String')) returns contents of e as a double
% --- Executes during object creation, after setting all properties.
function e_CreateFcn(hObject, eventdata, handles)
% hObject    handle to e (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function fiberradius_Callback(hObject, eventdata, handles)
% hObject    handle to fiberradius (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of fiberradius as text
%        str2double(get(hObject,'String')) returns contents of fiberradius as a double
% --- Executes during object creation, after setting all properties.
function fiberradius_CreateFcn(hObject, eventdata, handles)
% hObject    handle to fiberradius (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function rf_Callback(hObject, eventdata, handles)
% hObject    handle to rf (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of rf as text
%        str2double(get(hObject,'String')) returns contents of rf as a double
% --- Executes during object creation, after setting all properties.
function rf_CreateFcn(hObject, eventdata, handles)
% hObject    handle to rf (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function fiberrad_Callback(hObject, eventdata, handles)
% hObject    handle to fiberrad (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of fiberrad as text
%        str2double(get(hObject,'String')) returns contents of fiberrad as a double
% --- Executes during object creation, after setting all properties.
function fiberrad_CreateFcn(hObject, eventdata, handles)
% hObject    handle to fiberrad (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
% --- Executes on button press in solve1.
function solve1_Callback(hObject, eventdata, handles)
% hObject    handle to solve1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
handels=guidata(hObject);
VFs = str2num(get(handels.vfs, 'String'));
V0 = str2num (get(handels.v0, 'String'));
Va = str2num (get(handels.va, 'String'));
beta = str2num (get(handels.beta, 'String'));
E = str2num (get(handels.e, 'String'));
fiberRadius = str2num (get(handels.fiberradius, 'String'));
FiberRad = str2num (get(handels.fiberrad, 'String'));
rf = str2num (get(handels.rf, 'String'));
NumBreak = str2num (get(handels.numbreak, 'String'));
RBreakage = str2num (get(handels.rbreakage, 'String'));
fiberLen = str2num (get(handels.fiberlen, 'String'));
beta_mean = str2num (get(handels.betamean, 'String'));
beta_dev = str2num (get(handels.betadev, 'String'));
frow = str2num (get(handels.frowtag, 'String'));
fcolumn = str2num (get(handels.fcolumntag, 'String'));
Enter = get(handles.enter,'String');
% model
%fibermat='vf_0.55_spec1.mat';
rhos=[];
for i=1:length(VFs)
    VF=VFs(i);
   x = get(handels.popup,'Value');
switch x
    case 1
        h = msgbox('Please Choose a function', 'Error','error');
    case 2
        [Fc,Pressure] = ContactForce_Exp(V0,Va,VF,beta,E,fiberRadius);
Rc = ContactR(fiberRadius,Fc,E,rf);
%1. Random Packing
specimen=1;
fibermat=strcat('vf_',num2str(VF),'_spec',num2str(specimen),'.mat');
    case 3
        [Fc,Pressure] = ContactForce_Exp(V0,Va,VF,beta,E,fiberRadius);
Rc = ContactR(fiberRadius,Fc,E,rf);
%3. Square Packing
SquarePacking(frow,fcolumn,VF,fiberRadius);
fibermat='PerfectFiber.mat';
    case 4
        [Fc,Pressure] = ContactForce_Exp(V0,Va,VF,beta,E,fiberRadius);
Rc = ContactR(fiberRadius,Fc,E,rf);
%3. Hexagonal Packing
HexPacking(frow,fcolumn,VF,fiberRadius);
fibermat='PerfectFiber.mat';
    otherwise
end
[rho,fiber,VF,NumContacts]=Func_RNetwork_Z(fibermat,fiberLen,beta_mean,fiberRadius,NumBreak,Rc,rf,RBreakage);
rhos(end+1)=rho;
end
% % % create the Table
V0_1  = V0.*ones(1,length(VFs));
Va_1 = Va.*ones(1,length(VFs));
beta_1 = beta.*ones(1,length(VFs));
E_1 = E.*ones(1,length(VFs));
fiberRadius_1 = fiberRadius.*ones(1,length(VFs));
FiberRad_1 = FiberRad.*ones(1,length(VFs));
rf_1 = rf.*ones(1,length(VFs));
fiberLen_1 = fiberLen.*ones(1,length(VFs));
RBreakage_1 = RBreakage.*ones(1,length(VFs));
NumBreak_1 = NumBreak.*ones(1,length(VFs));
beta_mean_1 = beta_mean.*ones(1,length(VFs));
beta_dev_1 = beta_dev.*ones(1,length(VFs));
frow_1 = frow.*ones(1,length(VFs));
fcolumn_1 = fcolumn.*ones(1,length(VFs));
A = [V0_1;Va_1;beta_1;E_1;fiberRadius_1;FiberRad_1;rf_1;fiberLen_1;RBreakage_1;NumBreak_1;beta_mean_1;beta_dev_1;frow_1;fcolumn_1;VFs;rhos];
fileID = fopen(Enter,'w');
fprintf(fileID,'%6s,%6s,%6s,%6s,%6s,%6s,%6s,%6s,%6s,%6s,%6s,%6s,%6s,%6s,%6s,%12s\r\n','V0','Va','beta','E',...
'fiberRadius','FiberRad','rf','fiberLen','Rbreakage','NumBreak','beta_mean','beta_dev','frow','fcolumn','VFs','rhos');
% fprintf(fileID,'%6s %6s %6s %6s %6s %6s %6s %6s %6s %6s %6s %6s %6s %12s\n','V0','Va','beta','E',...
% 'fiberRadius','FiberRad','rf','fiberLen','RBreakage','NumBreak','beta_mean','beta_dev','VFs','rhoz');
fprintf(fileID,'%6.2f,%6.2f,%6.2f,%2.10f,%2.10f,%2.20f,%2.20f,%6.2f,%6.2f,%6.2f,%6.2f,%6.2f,%6.2f,%6.2f,%6.2f,%12.8f\r\n' ,A);
fclose(fileID);
%
%
%
% % create Table end
%
% % Define Axes
axes(handels.axes1)
s = get(handels.popup1,'Value');
switch s
    case 1
        plot(rhos,VFs)
        grid on
        xlabel('rho')
        ylabel('Volumfraction')
        title('Volumfraction vs rho')
    case 2
        plot(rhos,V0)
        grid on
        xlabel('rho')
        ylabel('V0')
        title('V0 vs rho')
    case 3
        plot(rhos,Va)
        grid on
        xlabel('rho')
        ylabel('Va')
        title('Va vs rho')
    otherwise
end
guidata(hObject,handels);
% end Define Axes
% --- Executes when entered data in editable cell(s) in uitable10.
function uitable10_CellEditCallback(hObject, eventdata, handles)
% hObject    handle to uitable10 (see GCBO)
% eventdata  structure with the following fields (see MATLAB.UI.CONTROL.TABLE)
%    Indices: row and column indices of the cell(s) edited
%    PreviousData: previous data for the cell(s) edited
%    EditData: string(s) entered by the user
%    NewData: EditData or its converted form set on the Data property. Empty if Data was not changed
%    Error: error string when failed to convert EditData to appropriate value for Data
% handles    structure with handles and user data (see GUIDATA)
data = get(hObject, 'data');
function edit_vfs_Callback(hObject, eventdata, handles)
% hObject    handle to edit_vfs (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of edit_vfs as text
%        str2double(get(hObject,'String')) returns contents of edit_vfs as a double
% --- Executes during object creation, after setting all properties.
function edit_vfs_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit_vfs (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function edit_fiberradius_Callback(hObject, eventdata, handles)
% hObject    handle to edit_fiberradius (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of edit_fiberradius as text
%        str2double(get(hObject,'String')) returns contents of edit_fiberradius as a double
% --- Executes during object creation, after setting all properties.
function edit_fiberradius_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit_fiberradius (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function edit_fiberrad_Callback(hObject, eventdata, handles)
% hObject    handle to edit_fiberrad (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of edit_fiberrad as text
%        str2double(get(hObject,'String')) returns contents of edit_fiberrad as a double
% --- Executes during object creation, after setting all properties.
function edit_fiberrad_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit_fiberrad (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function edit_beta_Callback(hObject, eventdata, handles)
% hObject    handle to edit_beta (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of edit_beta as text
%        str2double(get(hObject,'String')) returns contents of edit_beta as a double
% --- Executes during object creation, after setting all properties.
function edit_beta_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit_beta (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function edit_va_Callback(hObject, eventdata, handles)
% hObject    handle to edit_va (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of edit_va as text
%        str2double(get(hObject,'String')) returns contents of edit_va as a double
% --- Executes during object creation, after setting all properties.
function edit_va_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit_va (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function edit_e_Callback(hObject, eventdata, handles)
% hObject    handle to edit_e (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of edit_e as text
%        str2double(get(hObject,'String')) returns contents of edit_e as a double
% --- Executes during object creation, after setting all properties.
function edit_e_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit_e (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function edit_v0_Callback(hObject, eventdata, handles)
% hObject    handle to edit_v0 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of edit_v0 as text
%        str2double(get(hObject,'String')) returns contents of edit_v0 as a double
% --- Executes during object creation, after setting all properties.
function edit_v0_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit_v0 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function edit_rf_Callback(hObject, eventdata, handles)
% hObject    handle to edit_rf (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of edit_rf as text
%        str2double(get(hObject,'String')) returns contents of edit_rf as a double
% --- Executes during object creation, after setting all properties.
function edit_rf_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit_rf (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
% --- Executes when entered data in editable cell(s) in uitable11.
function uitable11_CellEditCallback(hObject, eventdata, handles)
% hObject    handle to uitable11 (see GCBO)
% eventdata  structure with the following fields (see MATLAB.UI.CONTROL.TABLE)
%    Indices: row and column indices of the cell(s) edited
%    PreviousData: previous data for the cell(s) edited
%    EditData: string(s) entered by the user
%    NewData: EditData or its converted form set on the Data property. Empty if Data was not changed
%    Error: error string when failed to convert EditData to appropriate value for Data
% handles    structure with handles and user data (see GUIDATA)
% --- Executes on button press in table.
function table_Callback(hObject, eventdata, handles)
% hObject    handle to table (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
function edit18_Callback(hObject, eventdata, handles)
% hObject    handle to edit18 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of edit18 as text
%        str2double(get(hObject,'String')) returns contents of edit18 as a double
% --- Executes during object creation, after setting all properties.
function edit18_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit18 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function edit19_Callback(hObject, eventdata, handles)
% hObject    handle to edit19 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of edit19 as text
%        str2double(get(hObject,'String')) returns contents of edit19 as a double
% --- Executes during object creation, after setting all properties.
function edit19_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit19 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function edit20_Callback(hObject, eventdata, handles)
% hObject    handle to edit20 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of edit20 as text
%        str2double(get(hObject,'String')) returns contents of edit20 as a double
% --- Executes during object creation, after setting all properties.
function edit20_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit20 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function numbreak_Callback(hObject, eventdata, handles)
% hObject    handle to numbreak (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of numbreak as text
%        str2double(get(hObject,'String')) returns contents of numbreak as a double
% --- Executes during object creation, after setting all properties.
function numbreak_CreateFcn(hObject, eventdata, handles)
% hObject    handle to numbreak (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function rbreakage_Callback(hObject, eventdata, handles)
% hObject    handle to rbreakage (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of rbreakage as text
%        str2double(get(hObject,'String')) returns contents of rbreakage as a double
% --- Executes during object creation, after setting all properties.
function rbreakage_CreateFcn(hObject, eventdata, handles)
% hObject    handle to rbreakage (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function fiberlen_Callback(hObject, eventdata, handles)
% hObject    handle to fiberlen (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of fiberlen as text
%        str2double(get(hObject,'String')) returns contents of fiberlen as a double
% --- Executes during object creation, after setting all properties.
function fiberlen_CreateFcn(hObject, eventdata, handles)
% hObject    handle to fiberlen (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function edit24_Callback(hObject, eventdata, handles)
% hObject    handle to edit24 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of edit24 as text
%        str2double(get(hObject,'String')) returns contents of edit24 as a double
% --- Executes during object creation, after setting all properties.
function edit24_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit24 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function betamean_Callback(hObject, eventdata, handles)
% hObject    handle to betamean (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of betamean as text
%        str2double(get(hObject,'String')) returns contents of betamean as a double
% --- Executes during object creation, after setting all properties.
function betamean_CreateFcn(hObject, eventdata, handles)
% hObject    handle to betamean (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function edit27_Callback(hObject, eventdata, handles)
% hObject    handle to edit27 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of edit27 as text
%        str2double(get(hObject,'String')) returns contents of edit27 as a double
% --- Executes during object creation, after setting all properties.
function edit27_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit27 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function betadev_Callback(hObject, eventdata, handles)
% hObject    handle to betadev (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of betadev as text
%        str2double(get(hObject,'String')) returns contents of betadev as a double
% --- Executes during object creation, after setting all properties.
function betadev_CreateFcn(hObject, eventdata, handles)
% hObject    handle to betadev (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function edit29_Callback(hObject, eventdata, handles)
% hObject    handle to edit29 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of edit29 as text
%        str2double(get(hObject,'String')) returns contents of edit29 as a double
% --- Executes during object creation, after setting all properties.
function edit29_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit29 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function edit30_Callback(hObject, eventdata, handles)
% hObject    handle to edit30 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of edit30 as text
%        str2double(get(hObject,'String')) returns contents of edit30 as a double
% --- Executes during object creation, after setting all properties.
function edit30_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit30 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function fcolumntag_Callback(hObject, eventdata, handles)
% hObject    handle to fcolumntag (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of fcolumntag as text
%        str2double(get(hObject,'String')) returns contents of fcolumntag as a double
% --- Executes during object creation, after setting all properties.
function fcolumntag_CreateFcn(hObject, eventdata, handles)
% hObject    handle to fcolumntag (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function frowtag_Callback(hObject, eventdata, handles)
% hObject    handle to frowtag (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of frowtag as text
%        str2double(get(hObject,'String')) returns contents of frowtag as a double
% --- Executes during object creation, after setting all properties.
function frowtag_CreateFcn(hObject, eventdata, handles)
% hObject    handle to frowtag (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function enter_Callback(hObject, eventdata, handles)
% hObject    handle to enter (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of enter as text
%        str2double(get(hObject,'String')) returns contents of enter as a double
% --- Executes during object creation, after setting all properties.
function enter_CreateFcn(hObject, eventdata, handles)
% hObject    handle to enter (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
% --- Executes on selection change in popup.
function popup_Callback(hObject, eventdata, handles)
% hObject    handle to popup (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: contents = cellstr(get(hObject,'String')) returns popup contents as cell array
%        contents{get(hObject,'Value')} returns selected item from popup
%
val=get(hObject,'value');
axes(handles.axes2);
switch val
    case 1
         set(handles.fcolumntag,'Visible','on');
         set(handles.frowtag,'Visible','on');
         cla(handles.axes2);
         cla(handles.axes1);
    case 2
        set(handles.fcolumntag,'Visible','off');
        set(handles.frowtag,'Visible','off');
        imshow('Random.jpg');
        cla(handles.axes1);
    case 3
         set(handles.fcolumntag,'Visible','on');
         set(handles.frowtag,'Visible','on');
         imshow('Square.jpg');
1000          cla(handles.axes1);
1001
1002     case 4
1003         set(handles.fcolumntag,'Visible','on');
1004         set(handles.frowtag,'Visible','on');
1005         imshow('Hexagonal.jpg');
1006         cla(handles.axes1);
1007
1008     otherwise
1009 end
1010
1011         guidata(hObject,handles);
1012
1013
1014
1015
1016 % --- Executes during object creation, after setting all properties.
1017 function popup_CreateFcn(hObject, eventdata, handles)
1018 % hObject    handle to popup (see GCBO)
1019 % eventdata  reserved - to be defined in a future version of MATLAB
1020 % handles    empty - handles not created until after all CreateFcns called
1021
1022 % Hint: popupmenu controls usually have a white background on Windows.
1023 %       See ISPC and COMPUTER.
1024 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1025     set(hObject,'BackgroundColor','white');
1026 end
1027
1028
1029 % --------------------------------------------------------------------
1030 function Untitled_1_Callback(hObject, eventdata, handles)
1031 % hObject    handle to Untitled_1 (see GCBO)
1032 % eventdata  reserved - to be defined in a future version of MATLAB
1033 % handles    structure with handles and user data (see GUIDATA)
1034
1035
1036
1037 % --- Executes during object creation, after setting all properties.
1038 function axes2_CreateFcn(hObject, eventdata, handles)
1039 % hObject    handle to axes2 (see GCBO)
1040 % eventdata  reserved - to be defined in a future version of MATLAB
1041 % handles    empty - handles not created until after all CreateFcns called
1042
1043 % Hint: place code in OpeningFcn to populate axes2
1044
1045
1046 % end
1047
1048
1049 % --- Executes on button press in pushbutton5.
1050 function pushbutton5_Callback(hObject, eventdata, handles)
1051 % hObject    handle to pushbutton5 (see GCBO)
1052 % eventdata  reserved - to be defined in a future version of MATLAB
1053 % handles    structure with handles and user data (see GUIDATA)
1054 cla(handles.axes1);