Description of SquarePacking
Home > v08 > helper > SquarePacking.m
SquarePacking
PURPOSE
% square packing
SYNOPSIS
function PerfectFiber = SquarePacking(frow,fcolumn,VF,fiberRadius)
DESCRIPTION
% square packing
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
GenerateFiber2D % Example usage:
GenerateFiber2D % Example usage:
RNetworkGUI1 RNETWORKGUI1 MATLAB code for RNetworkGUI1.fig
ResistorNetwork_COMSOL % Resistor Network Model in COMSOL
RvsPressure2 % convergence test: Rz; Square Packing; IM7
SIM_Compare_Combine_GUI SIM_COMPARE_COMBINE_GUI MATLAB code for SIM_Compare_Combine_GUI.fig
SIM_Compare_Combine_GUI_table SIM_COMPARE_COMBINE_GUI_TABLE MATLAB code for SIM_Compare_Combine_GUI_table.fig
SIM_Compare_Square_GUI SIM_COMPARE_SQUARE_GUI MATLAB code for SIM_Compare_Square_GUI.fig
SIM_Convergence_Square_IM7[Conflict 2] % convergence test: Rz; Square Packing; IM7
SIM_IM7_VF_Square
SOURCE CODE
function PerfectFiber = SquarePacking(frow,fcolumn,VF,fiberRadius)
%% square packing
rad=fiberRadius;
a=rad*(sqrt(pi/(VF))-2); % square packingfiber= struct('x',[], 'y',[], 'radius', []);
for i=1:frow
    for j=1:fcolumn
        fnum=(i-1)*fcolumn+j;
%          fnum=(i-1)*fcolumn+j;
%                             fiber(fnum).center=[(j-1)*(2*rad+a) (i-1)*(2*rad+a)];
%         fiber(fnum).center=[(j-1)*(2*rad+2*a)+normrnd(0,a) (i-1)*(2*rad+2*a)++normrnd(0,a)];
%         fiber.x(fnum,1)=sqrt(3)*(j-1)*(rad+a/2);
%         fiber.y(fnum,1)=(1-mod(j,2))*(rad+a/2)+(i-1)*2*(rad+a/2); %hex packing
        fiber.x(1,fnum)=(j-1)*(2*rad+a);
        fiber.y(1,fnum)=(i-1)*(2*rad+a); % square packing
% B=((fcolumn-1)*sqrt(3)/2+frow-1)*2*rad;
% A=(frow-1)*(fcolumn-1)*sqrt(3)/2;
% C=4*rad^2-(frow*fcolumn*pi*rad^2)/VF;
% a=-2*rad+(-B+sqrt(B^2-4*A*C))/(2*A);  %hex packing
% a=fiberRadius*(sqrt(pi/(2*sqrt(3)*VF))-1);  % triangle arragement of fibers
% max_x=(2*a+2*rad)*(fcolumn-1);
% max_y=(2*a+2*rad)*(frow-1);
        fiber.radius(1,fnum)=rad;
    end
end
% fiber.x;
% fiber.y
PerfectFiber=fiber;
save PerfectFiber
%save PerfectFiber fiber
% for i=1:frow
%                         for j=1:fcolumn
%                             fnum=(i-1)*fcolumn+j;
%                              fiber(fnum).center=[sqrt(3)*(j-1)*(rad+a/2) (1-mod(j,2))*(rad+a/2)+(i-1)*2*(rad+a/2)];
% %                             fiber(fnum).center=[(j-1)*(2*rad+a) (i-1)*(2*rad+a)];
%                             fiber(fnum).radius=rad;
%
%                             %          fiber(fnum).center=[sqrt(3)*(j-1)*(rad+a/2) (1-mod(i,2))*(rad+a/2)+(i-1)*2*(rad+a/2)];
%                             %         fiber(fnum).center=[-(mod(i,2)-1)*(rad+a)+  (j-1)*(2*rad+2*a) (i-1)*(rad+a)*sqrt(3)];
%                             %          fiber(fnum).center=[-(mod(i,2)-1)*(rad+a)+(j-1)*(2*rad+2*a)+normrnd(0,0.1*a) (i-1)*(rad+a)*sqrt(3)+normrnd(0,0.1*a)];
%                             %          fiber(fnum).radius=rad;
%                         end
%                     end