Description of ThreeDNetwork2
Home > v08 > helper > ThreeDNetwork2.m
ThreeDNetwork2
PURPOSE
aa=[1 2 3 5 9]
SYNOPSIS
This is a script file.
DESCRIPTION
 aa=[1 2 3 5 9]
 bb=[2 4 7 6]
 c=[aa,bb]
 %sort(c)
 unique(c)
 [lia,locaa]=ismember(aa,c)
 [lia,locbb]=ismember(bb,c)
CROSS-REFERENCE INFORMATION
This function calls:
createnode UNTITLED2 Summary of this function goes here
dangling UNTITLED2 Summary of this function goes here
deletenode UNTITLED Summary of this function goes here
This function is called by:
SOURCE CODE
% aa=[1 2 3 5 9]
% bb=[2 4 7 6]
% c=[aa,bb]
% %sort(c)
% unique(c)
% [lia,locaa]=ismember(aa,c)
% [lia,locbb]=ismember(bb,c)
clear all
clc
%load('fiber.mat')
%vf=0.6
% load fiber from .mat
% model parameters
rf=1.5e-5   %resistivity of fiber
Rc=10 % contact resistance
%N=4
L=0.015; % fiber length in m
% ContactLen=1e-3;
% ContactLens=1e-3*[0.5 1 1.5 2 2.5 3 3.5 4 5 6 7 8 9 10];
ContactLens=1e-3*[5];
for iter=1:size(ContactLens,2)
    ContactLen=ContactLens(iter);
% %%% load fiber data from fiberSEM
%      load('fiberSEM.mat')
%      scale=55.4/5.2;
%      max_x=918/scale;
%      max_y=706/scale;
%      perc=3;
%     N=size(fiber,2);
% %     for i=1:N
% %         if size(fiber(i).nodes,2)==0
% %             fiber(i)=[];
% %         end
% %     end
% %      N=size(fiber,2);
% %     for i=1:N
% %     fiber(i).nodes=createnode(fiber,i,perc,N);
% %     end
%     fiber1= struct('center',[], 'radius',[], 'nodes', [],'Contacts',[],'contactNeighbor',[],'pts',{});
% %     fiber(N) = struct('center',[], 'radius',[], 'nodes', []);
%     %scale=max_x/semlength
% %     perc=perc*scale
% % fiber1=fiber
% %
% % fiber1.center=fiber.center/scale;
% % fiber1.radius=fiber.radius/scale;
% %
%     N=size(fiber,2)
%     for i=1:N
%     fiber1(i).center(1)=fiber(i).center(1)/scale;
%     fiber1(i).center(2)=fiber(i).center(2)/scale;
%     fiber1(i).radius=fiber(i).radius/scale;
%     fiber1(i).nodes=fiber(i).nodes;
%     end
%     fiber=fiber1;
%
%
%
% %%% finish loading fiber data
%%% build fiber from SEM image
% % close all;
% % clear all;
% A=imread('laser2.jpg');
% b=im2bw(A);
% I = rgb2gray(A);
% threshold = graythresh(I);
% bw = im2bw(I,threshold);
% imshow(bw);
% bw = bwareaopen(bw,30);
% [centers r]= imfindcircles(bw,[20 50]);  %PARAMETER  [radius range]
% imshow(bw);
% viscircles(centers, r,'EdgeColor','r');
% figure;
% imshow(A);
% viscircles(centers, r,'EdgeColor','r','LineWidth',1);
% im_dimensions=size(bw);
%
% scale=55.4/5.2;
% perc=3; %percolation distance PARAMETER (in um)
% % V_left=5; %left Voltage PARAMETER
% % V_right=0;  %right voltage PARAMETER
% max_x=im_dimensions(2)/scale; %Left boundary coordinates
% max_y=im_dimensions(1)/scale;
%
% % SampleLength=max_x/scale
% % SampleWidth=max_y/scale
%
%
%
% N=size(r);
% N=N(1);
% % fiber(N) = struct('center',[], 'radius',[], 'nodes', []);
% fiber=struct('center',[], 'radius',[], 'nodes', [],'Contacts',[],'contactNeighbor',[],'pts',{});
% %scale=max_x/semlength
% % perc=perc*scale
%
% for i=1:N
%     fiber(i).center(1)=1e-6*centers(i,1)/scale;
%     fiber(i).center(2)=1e-6*centers(i,2)/scale;
%     fiber(i).radius=1e-6*r(i)/scale;
% end
%
% for i=1:N
%     fiber(i).nodes=createnode(fiber,i,perc,N);
% end
% % hold on
% % deleting dangling bonds within electrodes:
% while(dangling(fiber,N,max_x))
% for i=1:N
%      num=size(fiber(i).nodes);
%     num_nodes=num(2);
%     if(num_nodes==1) && (fiber(i).center(1)>2*fiber(i).radius) && (fiber(i).center(1)<max_x-2*fiber(i).radius)
%         fiber=deletenode(fiber,i,N);
%     end
% end
% end
%%% finish building fiber
    % load fiber data
load('vf_0.6_spec2.mat');
Np=size(fiber.x);
N=Np(2);
%fiber1(N) = struct('center',[], 'radius',[], 'nodes', []);
fiber1= struct('center',[], 'radius',[], 'nodes', [],'Contacts',[],'contactNeighbor',[],'pts',{});
xmat=fiber.x;
ymat=fiber.y;
rmat=fiber.radius;
perc=1.0*fiber.radius(1);
max_x=20e-5; %Left boundary coordinates
max_y=20e-5; %Left boundary coordinates
for i=1:N
    fiber1(i).center(1)=1e-5*xmat(i);
    fiber1(i).center(2)=1e-5*ymat(i);
    fiber1(i).radius=1e-5*rmat(i);
end
for i=1:N
    fiber1(i).nodes=createnode(fiber1,i,perc,N);
end
while(dangling(fiber1,N,max_x))
for i=1:N
     num=size(fiber1(i).nodes);
    num_nodes=num(2);
    if(num_nodes==1) && (fiber1(i).center(1)>2*fiber1(i).radius) && (fiber1(i).center(1)<max_x-2*fiber1(i).radius)
        fiber1=deletenode(fiber1,i,N);
    end
end
end
%fiber= struct('center',[], 'radius',[], 'nodes', [],'Contacts',[],'contactNeighbor',[],'pts',{});
fiber=fiber1;
% end loading data
%
% % create a model system for testing
% max_x=18e-6
% max_y=18e-6
% fiber= struct('center',[], 'radius',[], 'nodes', [],'Contacts',[],'contactNeighbor',[],'pts',{});
% center=1e-6*[3 3;9 3; 15 3; 3 9;9 9;15 9;3 15;9 15;15 15]
% radius=1e-6*0.5*[5 5 5 5 5 5 5 5 5]'
% N=size(center,1)   %number of fibers
% for i=1:N
%     fiber(i).center=center(i,:);
%     fiber(i).radius=radius(i);
% end
% fiber(1).nodes=[2  4]
% fiber(2).nodes=[1 3 5]
% fiber(3).nodes=[2]
% fiber(4).nodes=[1 5]
% fiber(5).nodes=[2 4 6]
% fiber(6).nodes=[5]
% fiber(7).nodes=[8]
% fiber(8).nodes=[7 9]
% fiber(9).nodes=[8]
% % finish model system
%
%
% fiber(1).nodes=[2]
% fiber(2).nodes=[1 3]
% fiber(3).nodes=[2]
% fiber(4).nodes=[5]
% fiber(5).nodes=[4 6]
% fiber(6).nodes=[5]
% fiber(7).nodes=[8]
% fiber(8).nodes=[7 9]
% fiber(9).nodes=[8]
% fiber(1)
% N=size(fiber)
% N=N(2)
% for i=1:N
%     fiber(i).Contacts=[];
% end
% find contact points on all fibers
for i=1:N
    NumNeighbor=size(fiber(i).nodes,2);
%     NumNeighbor=NumNeighbor(2);
    allcontact=[];
    contact=[];
%     contactNeighbor=[];
    for j=1:NumNeighbor    %contact pts with each neighbor
        NeighborNode=fiber(i).nodes(j);
        if NeighborNode>i
%             NumContacts=1
            NumContacts=floor(L/ContactLen);
           % ContactLoc(j).contact(1)=rand*ContactLen;
            %contact(1)=rand*ContactLen
            previous=rand*ContactLen;
            contact(1)=previous;
%             previous=0;
            for m=2:NumContacts
                contact(m)=previous+normrnd(ContactLen,1);
%                 contact(m)=previous+abs(normrnd(ContactLen,1));
                %contact(m)=contact(m-1)+abs(normrnd(ContactLen,1));
                previous=contact(m);
                %ContactLoc(j).con?tact(m)=ContactLoc(j).contact(m-1)+rand*ContactLen+normrnd(ContactLen,1);
            end
%             sizea=size(fiber(i).Contacts,2);
            sizeb=size(contact,2);
            allcontact=[allcontact,contact];  % all contact points on fiber i
            fiber(i).contactNeighbor(end+1:end+sizeb)=NeighborNode;  %
%
%              fiber(i).Contacts(sizea+1:sizea+sizeb,1)=contact';
%              fiber(i).Contacts(sizea+1:sizea+sizeb,2)=NeighborNode;
%              sizeaa=size(fiber(NeighborNode).Contacts,1);
            fiber(NeighborNode).Contacts(end+1:end+sizeb)=contact;
            fiber(NeighborNode).contactNeighbor(end+1:end+sizeb)=i;
        end
    end
    allcontact=[fiber(i).Contacts,allcontact];  % all contact pts including those inherited from previous fibers (NeighborNode<i)
    allcontact1=unique(allcontact);
    fiber(i).Contacts=allcontact1;
%     if size(allcontact1,2)~=size(allcontact,2)
if size(allcontact1,1)~=0
    for m=1:size(allcontact1,2)   % find contact neighbors for each contact point.
        loc=find(allcontact==allcontact1(m));
        fiber(i).pts{m}=fiber(i).contactNeighbor(loc);
    end
end
%              fiber(NeighborNode).Contacts=allcontact1;
%              fiber(NeighborNode).pts{m}=contactNeighbor(loc);
%     fiber(i).Contacts=unique(fiber(i).Contacts,'rows');
end    %all fibers built
% finish finding contact points
%%% initialize network
R=cell(N,N);
for i=1:N
%     NumContacts=size(fiber(i).Contacts,1);
%     R{i,i}=zeros(NumContacts);
    for j=1:N
        NumRows=size(fiber(i).Contacts,2);
        NumColumns=size(fiber(j).Contacts,2);
        R{i,j}=zeros(NumRows,NumColumns);
    end
%     iContacts=fiber(i).Contacts;
%     for j=1:NumContacts
%         sizea=size(fiber(i).Contacts,1);
%         sizeb=size(fiber(iContacts(j,2)).Contacts,1);
%         R{i,iContacts(j,2)}=zeros(sizea,sizeib);
%     end
end
G=R;  % GV=K
% finish initializing
% find BC nodes
% BoundZ1=[];
% BoundZ2=[];
BoundX1=[];
BoundX2=[];
BoundY1=[];
BoundY2=[];
for i=1:N
    if (fiber(i).center(1)<=2*fiber(i).radius)
        %fiber1(i).nodes=[fiber1(i).nodes 0]; %left boundary
        BoundX1(end+1)=i;
    end
    if (fiber(i).center(1)>=max_x-2*fiber(i).radius)
        %fiber1(i).nodes=[fiber1(i).nodes N+1]; % right boundary
        BoundX2(end+1)=i;
    end
    if (fiber(i).center(2)<=2*fiber(i).radius)
        %fiber1(i).nodes=[fiber1(i).nodes 0]; %left boundary
        BoundY1(end+1)=i;
    end
    if (fiber(i).center(1)>=max_y-2*fiber(i).radius)
        %fiber1(i).nodes=[fiber1(i).nodes N+1]; % right boundary
        BoundY2(end+1)=i;
    end
end
% finish finding BC nodes
%%% build fibers resistors and contact resistors
for i=1:N
    NumContacts=size(fiber(i).Contacts,2); % note Contacts is a row vector
%     NumNeighbor=NumNeighbor(1);
    iContacts=fiber(i).Contacts;
    for j=1:NumContacts
        if j==NumContacts
            num_pt=size(fiber(i).pts{j},2);
            for k=1:num_pt
                neighbor_pt=fiber(i).pts{j}(k);
                ind=find(fiber(neighbor_pt).Contacts==iContacts(j));
                R{i,neighbor_pt}(j,ind)=Rc; %Contact Resistance between fibers
                G{i,neighbor_pt}(j,ind)=-1/Rc;
            end
            fiberi=R{i,i}(j,:);
            fiberi=fiberi(fiberi~=0);
            sum=0;
             for m=1:size(fiberi,2)
                sum=sum+1/fiberi(m);
            end
            Gfiberi=sum;
            sum1=0;
            for n=1:num_pt
                neighbor_pt=fiber(i).pts{j}(n);
                ind=find(fiber(neighbor_pt).Contacts==iContacts(j));
                sum1=sum1+1/R{i,neighbor_pt}(j,ind);
            end
            Gfiberj=sum1;
            G{i,i}(j,j)=Gfiberi+Gfiberj;
%
%             loc=find(iContacts(j)
% %             [boolen, ind]=ismember(iContacts(j,1),fiber(iContacts(j,2)).Contacts(:,1)); %
% %             R{i,iContacts(j,2)}(j,ind)=Rc; % Contact Resistance.
%             G{i,iContacts(j,2)}(j,ind)=-1/100;
%                       fiberi=R{i,i}(j,:);
%             fiberi=fiberi(fiberi~=0);
%             sum=0;
%             for m=1:size(fiberi,1)
%                 sum=sum+1/fiberi(m);
%             end
%             Gfiberi=sum
%             fiberj=R{i,iContacts(j,2)}(j,:)
%             Gfiberj=1/fiberj(fiberj~=0);
%             G{i,i}(j,j)=Gfiberi+Gfiberj;
        else
            RLen=fiber(i).Contacts(j+1)-fiber(i).Contacts(j);
            A=pi*fiber(i).radius^2;
            R{i,i}(j,j+1)=rf*RLen/A;
            R{i,i}(j+1,j)=rf*RLen/A;    % resistance between two sections on one fiber
            G{i,i}(j,j+1)=-1/R{i,i}(j,j+1);% G(i,j)=-1/R
            G{i,i}(j+1,j)=-1/R{i,i}(j+1,j);% G(i,j)=-1/R
            num_pt=size(fiber(i).pts{j},2);
            for k=1:num_pt
                neighbor_pt=fiber(i).pts{j}(k);
                ind=find(fiber(neighbor_pt).Contacts==iContacts(j));
                R{i,neighbor_pt}(j,ind)=Rc; %Contact Resistance.
                G{i,neighbor_pt}(j,ind)=-1/Rc;  % G(i,j)=-1/R
            end
            fiberi=R{i,i}(j,:);
            fiberi=fiberi(fiberi~=0);
            sum=0;
            for m=1:size(fiberi,2)
                sum=sum+1/fiberi(m);
            end
            Gfiberi=sum;
            sum1=0;
            for n=1:num_pt
                neighbor_pt=fiber(i).pts{j}(n);
                ind=find(fiber(neighbor_pt).Contacts==iContacts(j));
                sum1=sum1+1/R{i,neighbor_pt}(j,ind);
            end
            Gfiberj=sum1;
            G{i,i}(j,j)=Gfiberi+Gfiberj;  % elements on diagonal of G. G(i,i)=sum(1/R)
%
%
%             [boolen, ind]=ismember(iContacts(j,1),fiber(iContacts(j,2)).Contacts(:,1));
%             R{i,iContacts(j,2)}(j,ind)=100;
%             G{i,iContacts(j,2)}(j,ind)=-1/R{i,iContacts(j,2)}(j,ind);
%             fiberi=R{i,i}(j,:);
%             fiberi=fiberi(fiberi~=0);
%
%             sum=0;
%             for m=1:size(fiberi,1)
%                 sum=sum+1/fiberi(m);
%             end
%             Gfiberi=sum;
%
%             fiberj=R{i,iContacts(j,2)}(j,:);
%
%             Gfiberj=1/fiberj(fiberj~=0);
%             G{i,i}(j,j)=Gfiberi+Gfiberj;
        end
    end
end
% change R into a matrix to apply Kirchoff's Law.
%%% Apply BC
K=cell(N,1);
BC1=5;
BC2=0;
for i=1:N
    K{i,1}=zeros(size(fiber(i).Contacts,2),1);
end
% K=zeros(size(R,1),1)
for i=1:size(BoundX1,2)
    K{BoundX1(i),1}=BC1*ones(size(fiber(BoundX1(i)).Contacts,2),1);
    fiberlabel=BoundX1(i);
    for j=1:N
        if j==fiberlabel
            G{fiberlabel,j}=eye(size(fiber(fiberlabel).Contacts,2));
        else
            G{fiberlabel,j}=zeros(size(fiber(fiberlabel).Contacts,2),size(fiber(j).Contacts,2));
        end
    end
%     for j=1:size(fiber(BoundX1(i)).Contacts,1)
%     G{fiberlabel,fiberlabel}(j,j)=1;
%     end
end
for i=1:size(BoundX2,2)
    K{BoundX2(i),1}=BC2*ones(size(fiber(BoundX2(i)).Contacts,2),1);
        fiberlabel=BoundX2(i);
            for j=1:N
        if j==fiberlabel
            G{fiberlabel,j}=eye(size(fiber(fiberlabel).Contacts,2));
        else
            G{fiberlabel,j}=zeros(size(fiber(fiberlabel).Contacts,2),size(fiber(j).Contacts,2));
        end
    end
%     for j=1:size(fiber(BoundX2(i)).Contacts,1)
%     G{fiberlabel,fiberlabel}(j,j)=1;
%     end
end
K=cell2mat(K);
%R=cell2mat(R);
G=cell2mat(G);
Voltage2=G\K;
Mrow=zeros(N,1);
for i=1:N
    Mrow(i)=size(fiber(i).Contacts,2);
end
Voltage3=mat2cell(Voltage2,Mrow);
%%% calculate currents
% 1. outgoing currents
totcur1=0;
totcur2=0;
cur1=[];
cur2=[];
for i=1:size(BoundX1,2)
    fiberlabel=BoundX1(i);
    num_pt=size(fiber(fiberlabel).Contacts,2);
    for j=1:num_pt
        %Vdiff=BC1-Voltage3{j}
        num_contact=size(fiber(fiberlabel).pts{j},2);
        for k=1:num_contact
            neighbor_fiber=fiber(fiberlabel).pts{j}(k);
            neighbor_pt=find(fiber(neighbor_fiber).Contacts==fiber(fiberlabel).Contacts(j));
            Vdiff=BC1-Voltage3{neighbor_fiber}(neighbor_pt);
            Res=R{fiberlabel,neighbor_fiber}(j,neighbor_pt);
            cur1(end+1)=Vdiff/Res;
            totcur1=totcur1+cur1(end);
        end
    end
end
for i=1:size(BoundX2,2)
    fiberlabel=BoundX2(i);
    num_pt=size(fiber(fiberlabel).Contacts,2);
    for j=1:num_pt
        %Vdiff=BC1-Voltage3{j}
        num_contact=size(fiber(fiberlabel).pts{j},2);
        for k=1:num_contact
            neighbor_fiber=fiber(fiberlabel).pts{j}(k);
            neighbor_pt=find(fiber(neighbor_fiber).Contacts==fiber(fiberlabel).Contacts(j));
            Vdiff=Voltage3{neighbor_fiber}(neighbor_pt)-BC2;
            Res=R{fiberlabel,neighbor_fiber}(j,neighbor_pt);
            cur2(end+1)=Vdiff/Res;
            totcur2=totcur2+cur2(end);
        end
    end
end
totcur1
totcur2
Res=5/totcur1;
rou=L*Res*max_y/max_x
Results=[ContactLens(iter) rou];
fid=fopen('threeD-RN.txt','a');
fprintf(fid,'%f %d\n',Results);
fclose(fid);
end
% G1=G;
% [G1 indices]=removezeros(G1);
% [G1 indices2]=removezeros(G1');
% G1=G1';
% voltages=(G1^-1)*(K(indices));
% Final_Voltages=zeros(1,N);
% Final_Voltages(indices)=voltages
%  %voltage=G\K
%
%
%
%
%