Description of ThreeDNetwork
Home > v08 > helper > ThreeDNetwork.m
ThreeDNetwork
PURPOSE
aa=[1 2 3 5 9]
SYNOPSIS
This is a script file.
DESCRIPTION
 aa=[1 2 3 5 9]
 bb=[2 4 7 6]
 c=[aa,bb]
 %sort(c)
 unique(c)
 [lia,locaa]=ismember(aa,c)
 [lia,locbb]=ismember(bb,c)
CROSS-REFERENCE INFORMATION
This function calls:
createnode UNTITLED2 Summary of this function goes here
dangling UNTITLED2 Summary of this function goes here
deletenode UNTITLED Summary of this function goes here
removezeros UNTITLED3 Summary of this function goes here
This function is called by:
SOURCE CODE
% aa=[1 2 3 5 9]
% bb=[2 4 7 6]
% c=[aa,bb]
% %sort(c)
% unique(c)
% [lia,locaa]=ismember(aa,c)
% [lia,locbb]=ismember(bb,c)
clear all
%load('fiber.mat')
%vf=0.6
load('vf_0.6_spec2.mat')
Np=size(fiber.x);
N=Np(2);
fiber1(N) = struct('center',[], 'radius',[], 'nodes', []);
xmat=fiber.x;
ymat=fiber.y;
rmat=fiber.radius;
perc=1.0*fiber.radius(1);
max_x=20; %Left boundary coordinates
max_y=20; %Left boundary coordinates
for i=1:N
    fiber1(i).center(1)=xmat(i);
    fiber1(i).center(2)=ymat(i);
    fiber1(i).radius=rmat(i);
end
for i=1:N
    fiber1(i).nodes=createnode(fiber1,i,perc,N);
end
while(dangling(fiber1,N,max_x))
for i=1:N
     num=size(fiber1(i).nodes);
    num_nodes=num(2);
    if(num_nodes==1) && (fiber1(i).center(1)>2*fiber1(i).radius) && (fiber1(i).center(1)<max_x-2*fiber1(i).radius)
        fiber1=deletenode(fiber1,i,N);
    end
end
end
fiber=fiber1;
rf=1   %resistivity of fiber
%N=4    %number of fibers
L=10; % fiber length in um
% fiber= struct('center',[], 'radius',[], 'nodes', [],'ContactLoc',[]);
% center=[1 1; 2 1; 1 2; 2 2]
% radius=[0.5 0.5 0.5 0.5]'
% for i=1:N
%     fiber(i).center=center(i,:);
%     fiber(i).radius=radius(i);
% end
% fiber(1).nodes=[2 3 4]
% fiber(2).nodes=[1 3 4]
% fiber(3).nodes=[1 2 4]
% fiber(4).nodes=[1 2 3]
% fiber(1)
% N=size(fiber)
% N=N(2)
R=cell(N,N)
for i=1:N
    fiber(i).Contacts=[];
end
for i=1:N
    NumNeighbor=size(fiber(i).nodes);
    NumNeighbor=NumNeighbor(2);
    %fiber(i).Contacts=[]
    allcontact=[];
    for j=1:NumNeighbor    %contact pts with each neighbor
        NeighborNode=fiber(i).nodes(j);
        if NeighborNode>i
            ContactLen=4;
            NumContacts=floor(L/ContactLen);
           % ContactLoc(j).contact(1)=rand*ContactLen;
            %contact(1)=rand*ContactLen
            previous=rand*ContactLen;
            for m=1:NumContacts
                contact(m)=previous+abs(normrnd(ContactLen,1));
                %contact(m)=contact(m-1)+abs(normrnd(ContactLen,1));
                previous=contact(m);
                %ContactLoc(j).con?tact(m)=ContactLoc(j).contact(m-1)+rand*ContactLen+normrnd(ContactLen,1);
            end
            allcontact=[allcontact,contact];
            sizea=size(fiber(i).Contacts,1);
            sizeb=size(contact,2);
             fiber(i).Contacts(sizea+1:sizea+sizeb,1)=contact';
             fiber(i).Contacts(sizea+1:sizea+sizeb,2)=NeighborNode;
             sizeaa=size(fiber(NeighborNode).Contacts,1);
            fiber(NeighborNode).Contacts(sizeaa+1:sizeaa+sizeb,1)=contact';
            fiber(NeighborNode).Contacts(sizeaa+1:sizeaa+sizeb,2)=i;
        end
    end
    fiber(i).Contacts=unique(fiber(i).Contacts,'rows');
end    %all fibers built
% fiber(1).ContactNodes{3}
% fiber(1).Contacts ;
%%% initializing network
for i=1:N
%     NumContacts=size(fiber(i).Contacts,1);
%     R{i,i}=zeros(NumContacts);
    for j=1:N
        NumRows=size(fiber(i).Contacts,1);
        NumColumns=size(fiber(j).Contacts,1);
        R{i,j}=zeros(NumRows,NumColumns);
    end
%     iContacts=fiber(i).Contacts;
%     for j=1:NumContacts
%         sizea=size(fiber(i).Contacts,1);
%         sizeb=size(fiber(iContacts(j,2)).Contacts,1);
%         R{i,iContacts(j,2)}=zeros(sizea,sizeb);
%     end
end
G=R;
%%% build fibers resistors and contact resistors
for i=1:N
    NumContacts=size(fiber(i).Contacts,1);
%     NumNeighbor=NumNeighbor(1);
    iContacts=fiber(i).Contacts;
    for j=1:NumContacts
        if j==NumContacts
            [boolen, ind]=ismember(iContacts(j,1),fiber(iContacts(j,2)).Contacts(:,1));
            R{i,iContacts(j,2)}(j,ind)=100;
            G{i,iContacts(j,2)}(j,ind)=-1/100;
                      fiberi=R{i,i}(j,:);
            fiberi=fiberi(fiberi~=0);
            sum=0;
            for m=1:size(fiberi,1)
                sum=sum+1/fiberi(m);
            end
            Gfiberi=sum
            fiberj=R{i,iContacts(j,2)}(j,:)
            Gfiberj=1/fiberj(fiberj~=0);
            G{i,i}(j,j)=Gfiberi+Gfiberj;
        else
            RLen=fiber(i).Contacts(j+1,1)-fiber(i).Contacts(j,1);
            A=pi*fiber(i).radius^2;
            R{i,i}(j,j+1)=rf*RLen/A;
            R{i,i}(j+1,j)=rf*RLen/A;
            G{i,i}(j,j+1)=-1/R{i,i}(j,j+1);
            G{i,i}(j+1,j)=-1/R{i,i}(j+1,j);
            [boolen, ind]=ismember(iContacts(j,1),fiber(iContacts(j,2)).Contacts(:,1));
            R{i,iContacts(j,2)}(j,ind)=100;
            G{i,iContacts(j,2)}(j,ind)=-1/R{i,iContacts(j,2)}(j,ind);
            fiberi=R{i,i}(j,:);
            fiberi=fiberi(fiberi~=0);
            sum=0;
            for m=1:size(fiberi,1)
                sum=sum+1/fiberi(m);
            end
            Gfiberi=sum;
            fiberj=R{i,iContacts(j,2)}(j,:);
            Gfiberj=1/fiberj(fiberj~=0);
            G{i,i}(j,j)=Gfiberi+Gfiberj;
        end
    end
end
% change R into a matrix to apply Kirchoff's Law.
%%% Apply BC
BoundZ1=[];
BoundZ2=[];
BoundX1=[];
BoundX2=[];
BoundY1=[];
BoundY2=[];
max_x=20
max_y=20
for i=1:N
    if (fiber(i).center(1)<=2*fiber(i).radius)
        %fiber1(i).nodes=[fiber1(i).nodes 0]; %left boundary
        BoundX1(end+1)=i;
    end
    if (fiber(i).center(1)>=max_x-2*fiber(i).radius)
        %fiber1(i).nodes=[fiber1(i).nodes N+1]; % right boundary
        BoundX2(end+1)=i;
    end
    if (fiber(i).center(2)<=2*fiber(i).radius)
        %fiber1(i).nodes=[fiber1(i).nodes 0]; %left boundary
        BoundY1(end+1)=i;
    end
    if (fiber(i).center(1)>=max_y-2*fiber(i).radius)
        %fiber1(i).nodes=[fiber1(i).nodes N+1]; % right boundary
        BoundY2(end+1)=i;
    end
end
K=cell(N,1);
BC1=5
BC2=0
for i=1:N
    K{i,1}=zeros(size(fiber(i).Contacts,1),1);
end
% K=zeros(size(R,1),1)
for i=1:size(BoundX1,2)
    K{BoundX1(i),1}=BC1*ones(size(fiber(BoundX1(i)).Contacts,1),1);
    fiberlabel=BoundX1(i);
    for j=1:N
        if j==fiberlabel
            G{fiberlabel,j}=eye(size(fiber(fiberlabel).Contacts,1));
        else
            G{fiberlabel,j}=zeros(size(fiber(fiberlabel).Contacts,1),size(fiber(j).Contacts,1));
        end
    end
%     for j=1:size(fiber(BoundX1(i)).Contacts,1)
%     G{fiberlabel,fiberlabel}(j,j)=1;
%     end
end
for i=1:size(BoundX2,2)
    K{BoundX2(i),1}=BC2*ones(size(fiber(BoundX2(i)).Contacts,1),1);
        fiberlabel=BoundX2(i);
            for j=1:N
        if j==fiberlabel
            G{fiberlabel,j}=eye(size(fiber(fiberlabel).Contacts,1));
        else
            G{fiberlabel,j}=zeros(size(fiber(fiberlabel).Contacts,1),size(fiber(j).Contacts,1));
        end
    end
%     for j=1:size(fiber(BoundX2(i)).Contacts,1)
%     G{fiberlabel,fiberlabel}(j,j)=1;
%     end
end
K=cell2mat(K);
R=cell2mat(R);
G=cell2mat(G);
G1=G;
[G1 indices]=removezeros(G1);
[G1 indices2]=removezeros(G1');
G1=G1';
voltages=(G1^-1)*(K(indices));
Final_Voltages=zeros(1,N);
Final_Voltages(indices)=voltages
 %voltage=G\K