Description of traverse
Home > v08 > helper > traverse.m
traverse
PURPOSE
UNTITLED3 Summary of this function goes here
SYNOPSIS
function [ output_args ] = traverse(node,fiber1,N)
DESCRIPTION
UNTITLED3 Summary of this function goes here
   Detailed explanation goes here
CROSS-REFERENCE INFORMATION
This function calls:
traverse UNTITLED3 Summary of this function goes here
This function is called by:
kirchoff Script to solve a complicated KVL network
traverse UNTITLED3 Summary of this function goes here
SOURCE CODE
function [ output_args ] = traverse(node,fiber1,N)
%UNTITLED3 Summary of this function goes here
%   Detailed explanation goes here
global isconnected
isconnected(node)=1;
nextnodes=fiber1(node).nodes;
nextnodes=nextnodes(nextnodes>0);
nextnodes=nextnodes(nextnodes<=N);
tempsize=size(nextnodes);
sizen=tempsize(2);
for i=1:sizen
    nextnode=nextnodes(i);
    if(isconnected(nextnode)==0)
        traverse(nextnode,fiber1,N);
    end
end
output_args=0;
end