Description of treeNode_callback
Home > v08 > helper > treeNode_callback.m
treeNode_callback
PURPOSE
SYNOPSIS
function treeNode_callback(tree,ev,allHandles,allData)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
addFiber
addFiber_callback
addLamina
addLaminate
addLaminate_callback
removeFiber_callback
removeLamina_callback
runSimulation_callback
showFiber
showLamina
char TEMPLATE Convert a template object in a one line description string
This function is called by:
showTree [mtree,treecontainer] = uitree('v0', 'Root',root);
SUBFUNCTIONS
function p = node2path(node)
SOURCE CODE
function treeNode_callback(tree,ev,allHandles,allData)
fiberLibObj = allData.fiberLib;
laminaLibObj = allData.laminaLib;
laminateLibObj = allData.laminateLib;
nodes = tree.getSelectedNodes;
tableHandle =allHandles.materialPropertyTable;
choosePackOrderTable = allHandles.choosePackOrderTable;
chooseFiberTable =allHandles.chooseFiberTable;
%chooseFiberTable =allHandles.chooseFiberTable;
add2LibBtn = allHandles.add2LibBtn;
removeFromLibBtn = allHandles.removeFromLibBtn;
 runBtn=allHandles.runSimulationBtn;
 parameterTable = allHandles.simulationParameterTable;
if ~isempty(nodes)
    node = nodes(1);
    p = node2path(node);
    selectedNode = p{end};
    if length(p) == 2
        runBtn.Visible='off';
        add2LibBtn.Visible = 'off';% show add2Lib btn. s
        removeFromLibBtn.Visible = 'off';
         parameterTable.Visible ='off';
        switch selectedNode
            case 'Fiber'
                choosePackOrderTable.Visible ='off';
                chooseFiberTable.Visible ='off';
                allData.fiberLib.showOnGui(tableHandle);
            case 'Lamina'
                allData.laminaLib.showOnGui(tableHandle);
            case 'Laminate'
                choosePackOrderTable.Visible ='off';
                chooseFiberTable.Visible ='off';
                allData.laminateLib.showOnGui(tableHandle);
        end
    end
    if length(p)==3
        selectedNode =p{end};
        switch p{2}
            case 'Fiber'
                runBtn.Visible='off';
                parameterTable.Visible ='off';
                if strcmp(selectedNode, 'Add Fiber')
                    addFiber(allHandles,allData);
                    add2LibBtn.Callback = {@addFiber_callback,allHandles,allData};
                else
                    showFiber(selectedNode,allHandles,allData)
                    removeFromLibBtn.Callback = {@removeFiber_callback,allHandles,allData};
                end
            case 'Lamina'
                runBtn.Visible='off';
                parameterTable.Visible ='off';
                 if strcmp(selectedNode, 'Add Lamina')
                     addLamina(allHandles,allData);
                 else
                     showLamina(selectedNode,allHandles,allData);
                      removeFromLibBtn.Callback = {@removeLamina_callback,allHandles,allData};
                 end
            case 'Laminate'
%                 choosePackOrderTable.Visible ='off';
%                 chooseFiberTable.Visible ='off';
                if strcmp(selectedNode, 'Add Laminate')
                      runBtn.Visible='off';
                      parameterTable.Visible ='on';
                    addLaminate(selectedNode,allHandles,allData);
                    add2LibBtn.Callback = {@addLaminate_callback,allHandles,allData};
                    tableHandle.ColumnEditable = true;
%
%                     add2LibBtn.Visible = 'on';% show add2Lib btn. s
%                     removeFromLibBtn.Visible ='off';
                   % tableHandle = allHandles.materialPropertyTable;
                   % showAddFiber(selectedNode,handles,allData);
                else
                       runBtn.Visible='on';
                        runBtn.Callback = {@runSimulation_callback,selectedNode,allHandles,allData};
                     add2LibBtn.Visible = 'off';% hide add2Lib btn. s
                     removeFromLibBtn.Visible ='on';
                    [~,index]=ismember(selectedNode,laminateLibObj.itemNames)
                    itemObj =laminateLibObj.itemArray(index);
                    itemObj.showOnGui(allHandles);
                 end
                %displayLaminateInfo(selectedNode,allHandles,allData);
        end
    end
end
    function p = node2path(node)
        path = node.getPath;
        for i=1:length(path);
            p{i} = char(path(i).getName);
            % disp(p{i})
        end
        if length(p) > 1
            path = fullfile(p{:});
        else
            path = p{1};
        end
        %selectedNode =p{end};
    end
end