Description of Laminate1
Home > v08 > @Laminate1 > Laminate1.m
Laminate1
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
runLTspice RUNLTSPICE internal function, no need to call
Laminate1
runLTspice RUNLTSPICE call LTspice to solve resistor network.
transientNetlist11 TRANSIENTNETLIST1 Summary of this function goes here
readTransientRAW readTransientRAW method of Laminate; to read SPICE output .raw data and
runLTspice % Run LTSpice and reduce data
set TEMPLATE/SET Edit data stored in a Template object
This function is called by:
Laminate1
LaminateLib
addLaminate
addLaminate_callback
demo1
SUBFUNCTIONS
function obj = Laminate1(val)
function showOnGui(obj,allHandles)
function xResistivity = getXResistivity(obj)
function yResistivity = getYResistivity(obj)
function zResistivity = getZResistivity(obj)
function resistivityTensor = getResistivityTensor(obj)
function [voltage,current,resistance] = transientAnalysis(obj)
function results = compute(obj)
SOURCE CODE
classdef Laminate1
    %% usage example:
    % a=Fiber('AS4')
    % b= Fiber('IM7')
    % AS4prop =a.property
    properties
        propertyCell = {};
        parameterCell = {};
        propertyStruct = struct;
        parameterStruct = struct;
        propertyTable = table
    end
    methods
        netlist = transientNetlist11(obj);
        function obj = Laminate1(val)
            %obj.propertyStruct=struct;
            if nargin>0
                obj.propertyStruct.name = val;
            else
                obj.propertyStruct.name ='myLaminate1';
            end
            obj.propertyStruct.pressure='8.0e5';
            obj.propertyStruct.dimension = '[1e-2 1e-3 1e-3]';
            obj.propertyStruct.laminaArray = {'AS4 VF=0.5';'AS4 VF=0.5';'AS4 VF=0.5';'AS4 VF=0.5'};
            obj.propertyStruct.layupArray = {0;0;0;0};
            obj.propertyStruct.connectivityArray ={0.1;0.1;0.1;0.1};
            obj.parameterStruct.analysisType = 'Transient';
            obj.parameterStruct.voltageInputTable = '0 0 10u 117 20u 141 30u 143 40u 137 50u 117 60u 93 70u 69 80u 43 90u 23 100u 0';
            obj.parameterStruct.stopTime = '50u';
            obj.parameterStruct.breakdownTemperature = '1000';
        end
        rawData=runLTspice(obj,NetList)
        function showOnGui(obj,allHandles)
            set(allHandles.materialPropertyLayout,'Height',[-1,-1,5])
            table1 = allHandles.materialPropertyTable;
            table1.ColumnEditable = [];
            table1.Visible = 'on';
            table1Data = {obj.propertyStruct.name;obj.propertyStruct.pressure;obj.propertyStruct.dimension};
            table1.Data = table1Data;
            table1.ColumnName ={'Property Value','Description'}
            table1.RowName = {'Laminate Name','Processing Pressure (Pa)','Dimension (m)'};
            table2 =  allHandles.chooseFiberTable;
            table2.ColumnEditable = false;
            table2.RowName ='numbered';
            table2.Visible ='on';
            propertyData =[obj.propertyStruct.laminaArray,obj.propertyStruct.layupArray,obj.propertyStruct.connectivityArray];
            table2.Data = propertyData;
            parameterTable = allHandles.simulationParameterTable;
            table2.ColumnName = {'Lamina','Layup','Ply Connectivity'};
            %ColumnName =[];
            parameterTable.Visible ='on';
            parameterTable.ColumnEditable = true;
            parameterTable.Data = struct2cell(obj.parameterStruct);
            parameterTable.RowName = {'Analysis Type','Voltage Waveform','Stop Time (s)',...
                'Breakdown Temperature'};
        end
        %
        %showOnGui  :method of Laminate1; to display data on GUI
        %obj.showOnGui(tableHandle)
        % tableHandle is the handle of uitable where data is to be
        % plotted
        % % Example:
        %  L =Laminate1()
        %  figure
        %  t1 = uitable
        %  L.showOnGui(t1)
        % see also uitable
        % ---copyright 2014-2016 Hong Yu,hongy@udel.edu ----
        %
        function xResistivity = getXResistivity(obj)
            xResistivity =rand()/1000;
        end
        function yResistivity = getYResistivity(obj)
            if 1
                yResistivity = rand()
                %pause(0.9)
                return
            end
            yResistivity = obj.getZResistivity;
        end
        function zResistivity = getZResistivity(obj)
            if 1
                zResistivity = rand()
                return
            end
        end
        function  resistivityTensor = getResistivityTensor(obj)
            xResistivity = obj.getXResistivity;
            yResistivity = obj.getYResistivity;
            zResistivity =obj.getZResistivity;
            resistivityTensor =[xResistivity yResistivity zResistivity];
        end
        function [voltage,current,resistance] = transientAnalysis(obj)
            voltage = obj.propertyStruct.inputTable
        end
        function results = compute(obj)
            %COMPUTE : method of Laminate; compute through-thickness resistivty
            % no input required.
            % Example:
            % L = Laminate()
            % L.compute()
            %
            % first write SPICE netlist with Laminate.transientNetList
            % then solve it by calling LTSPICE with Laminate.runLTspice
            % at last reduce data with readTransientRAW
            %
            % see also Laminate, transientNetList, runLTspice,readTransientRAW
            netlist = obj.transientNetlist11;  % save .cir in SPICE_I nOut folder
            %netlist = 'laminateNetlist'
            NetList =['SPICE\',netlist];
            rawData = obj.runLTspice(NetList);
            results = readTransientRAW(rawData);
%             timeArray = results(2:end-1,1);
%             voltageArray = results(2:end-1,2);
%             currentArray = results(2:end-1,3);
%             resistanceArray = results(2:end-1,4);
%             figure
%             line(timeArray,voltageArray,'LineWidth',5)
%             ax1=gca;
%             ax1_pos = ax1.Position; % position of first axes
%             line(timeArray,currentArray,'Parent',ax1,'Color','r','LineWidth',5)
%             ax2 = axes('Position',ax1_pos,...
%                 'XAxisLocation','bottom',...
%                 'YAxisLocation','right',...
%                 'Color','none');
%             line(timeArray,resistanceArray,'Parent',ax2,'Color','g','LineWidth',5,'Marker','+','LineWidth',3)
        end
    end
end
        % obj.propertyStruct.plyConnectivity =1.0;
        % choose between 'SteadyState' an2d 'Transient'
        %obj.propertyStruct.dimension = '[8e-3 2e-3 1e-3]';
        %obj.propertyStruct.towRhoArray = '[3.5e-5 1 1]';
        %obj.propertyStruct.layUp = '[0 0]';
        %obj.propertyStruct.interPlyResistance = 1000; % resistance of interply contacts
        %obj.propertyStruct.contactSpan = 1e-3;
        %nLayer = 4; % number of Layers in each ply
        % contactRAfterBreakdown = 100;
        %interPlyRAfterBreakdown = 1000;
        %voltageInputTable = [0 0 90e-6 10 100e-3 0];
        %obj.propertyStruct.name ='myLaminate1';
        %obj.propertyStruct.type = 'cross-ply';
        %obj.propertyStruct.layup = '[0,0]';
        %             table1 = struct2table(obj.propertyStruct);
        %             obj.propertyTable = table1;
        %
        %             obj.parameterStruct.stopTime = '1.0';
        %             obj.parameterStruct.analysisType = 'Transient';
        %             obj.parameterStruct.withJouleHeating = true;
        %             obj.parameterStruct.voltageWaveform ='[0,1,1,2,2,10,3,20,4,0]';
        %netlist= transientNetList11(obj)
            %             tempCell = struct2cell(obj.propertyStruct)
        %             %tempCell{2}=obj.propertyStruct.fiber.propertyStruct.name;
        %             for i = 1:length(tempCell)
        %                 item = tempCell{i}
        %                 if isnumeric(item)
        %                     tempCell{i} = mat2str(item,3)
        %                 end
        %             end
        %             tableHandle.Data=tempCell;
        %             tableHandle.ColumnName ={};
        %             colNames = {'Lamina Name','Fiber','Volume Fraction','Pressure','Pack Order','Dimension'};
        %             tableHandle.RowName =colNames;
        %         end
% property = struct({'Name','Diameter','Electrical Resistivity'
%property = struct
%field='name'
%value='as4'
%property = struct(field,value)
%property.name ='AS4'
%          property.Diameter = 5e-5
%          property.ElectricalResistivity
%          property.ThermalConductivity
%          property.EModulus