Description of ContactForce
Home > v08 > @Function > ContactForce.m
ContactForce
PURPOSE
% Force at each contact point.
SYNOPSIS
function Fc = ContactForce(VF,beta,Pressure,fiberRadius)
DESCRIPTION
% Force at each contact point.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
Function
Interface_layer_simulation % 3D Resistor Network Modle by Hong Yu
RvsPressure
SIM_Convergence_Square_IM7[Conflict 1] % convergence test: Rz; Square Packing; IM7
SIM_Convergence_Square_IM7[Conflict 2] % convergence test: Rz; Square Packing; IM7
SIM_Convergence_Square_IM7[Conflict 3] % convergence test: Rz; Square Packing; IM7
SIM_Convergence_Square_IM7[Conflict] % convergence test: Rz; Square Packing; IM7
SIM_Pressure_IM7 % Statistical representation: beta
SIM_beta_Dis_IM7 % Statistical representation: beta
Sensitivity_Study_Taguchi % Sensitivity study of 3D Resistor Network MOdel using Taguchi Technique
SOURCE CODE
function Fc = ContactForce(VF,beta,Pressure,fiberRadius)
%% Force at each contact point.
a=fiberRadius*(sqrt(pi/VF)-2); % fiber spacing
Fc=Pressure*(2*fiberRadius+a)*a*beta;