Description of Function
Home > v08 > @Function > Function.m
Function
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
Connect_Theta
ContactForce % Force at each contact point.
ContactR % contact resistance
Func_RhoZ_LTspice % example usage: copy the code inside " if 1==0 ... end" and run.
Function
GenerateFiber2D % Example usage:
LTspice2Matlab
ReadRAW function [LineContent,NVariables, NValues] = ReadRAW(filepath)
runLTspice RUNLTSPICE internal function, no need to call
transientData TRANSIENTDATA extract transient data from SPICE RAW data file
runLTspice RUNLTSPICE call LTspice to solve resistor network.
ContactForce % Force at each contact point.
ContactR % contact resistance
Func_RhoZ_LTspice % example usage: copy the code inside " if 1==0 ... end" and run.
GenerateFiber2D % Example usage:
ReadRAW function [LineContent,NVariables, NValues] = ReadRAW(filepath)
runLTspice % Run LTSpice and reduce data
This function is called by:
Function
SOURCE CODE
classdef Function
    methods(Static)
         runLTspice(NetListID);
           result = transientData(spiceRawData);
        raw_data = LTspice2Matlab( filename, varargin )
        rho = Func_RhoZ_LTspice(NetList,fibermat,fiberLen,beta,fiberRadius,NumBreak,Rc,rf,RBreakage);
        fiber2D = GenerateFiber2D(Spec_Wid,Spec_Th,VF,fiberRadius,PackOrder);
        Fc = ContactForce(VF,beta,Pressure,fiberRadius);
        Rc = ContactR(fiberRadius,Fc,E,rf);
        [Vin,data,data1]=ReadRAW(infile);
        connectivity = Connect_Theta(theta,Lc)
    end
end