Description of LaminateLib
Home > v08 > @LaminateLib > LaminateLib.m
LaminateLib
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
Laminate1
LaminateLib
This function is called by:
LaminateLib
CFRP_GUI_v08 GUI for 3D resistor network
SUBFUNCTIONS
function obj = LaminateLib()
function obj = addItem(obj,itemObj)
function obj = deleteItem(obj,itemObj)
function showOnGui(obj,tableHandle)
function itemNames = getNames(obj)
SOURCE CODE
classdef LaminateLib
    %%% table in the form:
    %   Name      AS4        IM7
    % beta           400         350
    % resistivity   1.5e-5   1.6e-5
    %   ...             ....          ....
    %%%
    %     properties %(Dependent)
    %
    %        %libTable =table; % fiberLib is a Table
    %     end
    properties
        itemNames ={}
        itemArray=[]
        % libStruct = struct;
    end
    methods
        %         function obj = FiberLib()
        %             %              fiberAS4 = Fiber1('AS4')
        %             %              fiberIM7 = Fiber1('IM7')
        %             %              fiberLibStruct = [fiberAS4.materialProperty fiberIM7.materialProperty]
        %             obj.fiberLibTable = table
        %         end
        function obj = LaminateLib()
            obj.itemArray = [Laminate1()];
            obj.itemNames = {'AS4 [0]8','IM7 [0/90]s'};
            for i=1:length(obj.itemNames)
                itemName = obj.itemNames{i};
                itemObj=Laminate1(itemName);
                obj.itemArray(i)=itemObj;
            end
        end
        function obj = addItem(obj,itemObj)
            itemName = itemObj.propertyStruct.name;
            [hasItem,~] = ismember(itemName,obj.itemNames);
            errMsg=['NameError: laminate name "' itemName '" already existed; please pick another name!'];
            assert(~hasItem,errMsg);
            obj.itemNames{end+1} = itemName;
            obj.itemArray(end+1) = itemObj;
        end
        function obj = deleteItem(obj,itemObj)
            %[~,index]=ismember(fiberc
            itemName = itemObj.propertyStruct.name;
            [hasItem,index] = ismember(itemName,obj.itemNames);
            errMsg= 'laminate to be deleted is not found in current laminate libary!';
            assert(hasItem,errMsg)
            obj.itemArray(index)=[];
            obj.itemNames(index)=[];
        end
        function showOnGui(obj,tableHandle)
            data = obj.itemNames';
            tableHandle.Data=data;
            tableHandle.RowName = 'numbered';
            tableHandle.ColumnName={'Laminate Name'};
        end
        function itemNames = getNames(obj)
            itemNames = obj.itemNames;
        end
    end
end
% classdef LaminateLib
%     %%% Table in the form:
%     %   Name      AS4        IM7
%     % beta           400         350
%     % resistivity   1.5e-5   1.6e-5
%     %   ...             ....          ....
%     %%%
%     properties
%        libTable =table % fiberLib is a Table
%        libStruct = struct
%     end
%     methods
%         function obj = LaminateLib()
%             laminate1 = Laminate1('laminate AS4')
%             laminate2= Laminate1('lamiante IM7')
%             libStruct = [laminate1.propertyStruct;laminate2.propertyStruct]
%             obj.libTable = [laminate1.propertyTable;laminate2.propertyTable];
%             %obj.libTable = struct2table(laminaLibStruct)
%         end
%         function obj = set.libTable(obj,tableObj)
%             obj.libTable = tableObj
%         end
%         function value = get.libTable(obj)
%             value = obj.libTable
%         end
%
%         function names = getNames(obj)
%             names = table2cell(obj.libTable(:,1));
%         end
%         function obj = addItem(obj,newItem)
%             prevTable = obj.Table
%             newItemTable = struct2table(newItem.materialProperty)
%             newTable = [prevTable;newItemTable]
%             obj.Table = newTable
%         end
%         function obj = deleteItem(obj)
%         end
%         function showOnGui(obj,panelHandle)
%         end
%
%     end
% end