Description of FiberLib
Home > v08 > @FiberLib > FiberLib.m
FiberLib
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
Fiber1
FiberLib
This function is called by:
FiberLib
CFRP_GUI_v08 GUI for 3D resistor network
SUBFUNCTIONS
function obj = FiberLib()
function obj = addItem(obj,fiberObj)
function obj = deleteItem(obj,fiberObj)
function showOnGui(obj,tableHandle)
SOURCE CODE
classdef FiberLib
    %%% table in the form:
    %   Name      AS4        IM7
    % beta           400         350
    % resistivity   1.5e-5   1.6e-5
    %   ...             ....          ....
    %%%
%     properties (Dependent)
%         libTable =table % fiberLib is a Table
%     end
    properties
        itemArray = []
        itemNames = {}
    end
    methods
        function obj = FiberLib()
            obj.itemArray = [Fiber1()];
            obj.itemNames = {'AS4','IM7'};
            for i=1:length(obj.itemNames)
                item = obj.itemNames{i};
                class(item)
                fiberObj=Fiber1(item);
                obj.itemArray(i)=fiberObj;
            end
        end
        function obj = addItem(obj,fiberObj)
            itemName = fiberObj.propertyStruct.name;
            [hasItem,~] = ismember(itemName,obj.itemNames);
            errMsg=['NameError: fiber name "' itemName '" already existed; please pick another name!'];
            assert(~hasItem,errMsg);
            obj.itemNames{end+1} = itemName;
            obj.itemArray(end+1) = fiberObj;
        end
        function obj = deleteItem(obj,fiberObj)
             %[~,index]=ismember(fiberc
             itemName = fiberObj.propertyStruct.name;
             [hasItem,index] = ismember(itemName,obj.itemNames);
             if ~hasItem
                 disp 'fiber to be deleted is not found in current fiber libary!'
             end
             obj.itemArray(index)=[];
             obj.itemNames(index)=[];
        end
        function showOnGui(obj,tableHandle)
            data = obj.itemNames';
            tableHandle.Data=data;
            tableHandle.RowName = 'numbered';
            tableHandle.ColumnName={'Fiber Name'};
        end
    end
end
%obj.libStruct(i)=fiberObj.propertyStruct;
%            for item=itemNames
%                class(item)
%            end
%obj.libStruct = [fiberAS4.propertyStruct fiberIM7.propertyStruct]
%obj.Table = struct2table(fiberLibStruct)
%         function obj = set.libTable(obj,tableObj)
%             obj.libTable = tableObj
%         end
%         function value = get.libTable(obj)
%             value = struct2table(obj.libStruct)
%             %value = obj.Table
%         end
%
%         function names = getNames(obj)
%             %%% returns a cell
%             names = table2cell(obj.libTable(:,1));
%         end
%         function obj = FiberLib()
%             %              fiberAS4 = Fiber1('AS4')
%             %              fiberIM7 = Fiber1('IM7')
%             %              fiberLibStruct = [fiberAS4.propertyStruct fiberIM7.propertyStruct]
%             obj.fiberLibTable = table
%         end
%             fiberAS4 = Fiber1('AS4')
%             fiberIM7 = Fiber1('IM7')
%             itemArray = [fiberAS4 fiberIM7]
%             prevTable = obj.libTable
%             newItemTable = struct2table(newItem.propertyStruct)
%             newTable = [prevTable;newItemTable]
%             obj.libTable = newTable